### ISSUE TITLE
Css missing height property or using %-values for the height causes High CPU

### ISSUE THREAD

**Issue by telion2** [dhilt/ngx-ui-scroll#104]
Similar to #98 

Its more a ease of Use thing. 
Basically if you dont limit the area where the scroller can be displayed using css for example, uiScroll will try to render everything. 
Consider: 
```
//template
<div class="viewport">
    <div *uiScroll="let elements of AdapterDatasource">
      <div class="elem">{{elements.text}}</div>
    </div>
  </div>
//CSS
.viewport{
   overflow-y:auto; 
   overflow-anchor:none; 
   height:200px;     //If this line is missing, Browsers skyrocket their CPU usage
   padding:0.5em
}
``` 
I generally don't think of it as a major issue, but I want to warn the people that this can happen. 
I think is more a missuse of this package, however new users are likly to fall in this pitfall. 

Btw. this also happens if the parent html element has no absolute height in pixels and you use % values in .viewport. 
e.g.: 
```
<div style="height: 500px"> //absolute height required here if % are used in .viewport
<div class="viewport">
    <div *uiScroll="let elements of AdapterDatasource">
      <div class="elem">{{elements.text}}</div>
    </div>
  </div>
</div>
.viewport{
   overflow-y:auto; 
   overflow-anchor:none; 
   height:50%;     //only possible with parent of absolute height
   padding:0.5em
}
```
This could be a bit more annoying for the developer, especially if the website should be responsive and if the project is a bit bigger. 
Here a repro of it: https://stackblitz.com/edit/angular-hwtptc
Tip: open it in Firefox, because Firefox can handle resource hungry websites better than Chrome.

**Comment by telion2** [comment]
I think it updating the docs with a warning about the height requirements could be enough.

**Comment by dhilt** [comment]
README update:

> ...the viewport is a scrollable area of finite height (if the viewport's height is not constrained, it will pull the entire content of the datasource and no scrollbar will appear)

**Comment by nicksav** [comment]
Guys, so basically no solution for responsive page?
How to make middle container to adjust?
![image](https://user-images.githubusercontent.com/9266365/90848290-dcb73e80-e3af-11ea-9b99-70c950f2d01f.png)
