### ISSUE TITLE
How to Scroll down as we append new record to data source??

### ISSUE THREAD

**Issue by mariah123** [dhilt/ngx-ui-scroll#106]
I have implemented ngx-ui-scroll in my chat project and it fulfills all of my requirements. However, I want it to scroll-down as I append a new record to data source. How to do that ???

**Comment by dhilt** [comment]
@mariah123 Hey, I just created demo for your situation -- https://stackblitz.com/edit/angular-ngx-ui-scroll-1-2-0-append-autoscroll

The thing is we need to scroll to the viewport' bottom after new item is appended:

```
    this.datasource.adapter.append({ ... });
    const viewportElement = document.getElementById('my-viewport');
    const sub = this.datasource.adapter.isLoading$.subscribe(isLoading => {
      if (!isLoading) {
        viewportElement.scrollTop = viewportElement.scrollHeight;
        sub.unsubscribe();
      }
    });
```
Since append is asynchronous process, we use `isLoading$` prop to provide scrolling only when the UiScroll stops.

**Comment by mariah123** [comment]
Thanks for providing the solution

**Comment by DaveLomber** [comment]
@dhilt sometimes it does not work as intended

either using 

    this.datasource.adapter.fix({ scrollPosition: this.messageList.scrollHeight });

or 

     this.messageList.scrollTop = this.messageList.scrollHeight;

it just does not scroll enough and left 10-50 pixels to the bottom

probably it relates to internal logic changes to scrollHeight value 
I'm just trying to figure it out..

**Comment by StriderRanger** [comment]
@DaveLomber I had a similar situation where there was an extra padding, and scrolling to bottom by the first load of the list was sometimes missing some pixels to the bottom of the list.
In my case, my list has items that are filled asynchronously, and by the time they are fully filled, the ui-scroll was not up to date with the new height of the items, therefore the padding-forward was not accurately calculated.
There is [this sample](https://stackblitz.com/edit/angular-ngx-ui-scroll-extra-padding-async-check-resizeobserver) that is related to #111, where I used the [resize-observer](https://github.com/juggle/resize-observer) lib, as was suggested by @dhilt.
Hope it helps.

**Comment by DaveLomber** [comment]
@StriderRanger aha, then this does explains this mystery to me!
Thank you for the clarification

**Comment by DaveLomber** [comment]
In my case it was with image attachments

so it was 

      img {
        max-height: 200px;
      }

and I replaced with 

      img {
        height: 200px;
      }

which did a trick

I can't believe it's so simple...
