### ISSUE TITLE
Fetching new data when BOF is reached

### ISSUE THREAD

**Issue by mariah123** [dhilt/ngx-ui-scroll#110]
I am trying to fetch new data and prepend it when bof reached scrolling up. But unable to resolve where to put this check actually.

**Comment by dhilt** [comment]
@mariah123 First, you may prepend new items in some other way than by user's demand (say, scrolling up to the topmost border). For example, there could be a process telling you that you have some new items that are not in the initial datasource (speaking of chat it might be socket-notification from server). Then you just call `Adapter.prepend(newItems, true)` and don't care about scroll position and BOF.

But if you don't know the exact time of new items availability, and want to try to request new items by meeting the edge of the your current dataset (and the edge of the viewport), you may try following approach:

```
const { adapter } = this.datasource;

// viewport's scroll event subscription
const viewportElement = document.getElementById('my-viewport');
const onViewportScroll$ = fromEvent(viewportElement, 'scroll')
  .pipe(
    map(() => viewportElement.scrollTop),
    startWith(viewportElement.scrollTop)
  );

// listen for viewport's scrollTop + uiScroll isLoading
this.prependSubscription$ = combineLatest(onViewportScroll$, adapter.isLoading$)
  .pipe(
    filter(([scrollTop, isLoading]) =>
      scrollTop === 0 && !isLoading && adapter.bof
    ),
    debounceTime(40)
  )
  .subscribe(() => {
    /* prepend logic; do not forget to sync new items with datasource */
  });
```

Here we prepend new items only when we are at the topmost position, the BOF is reached and scroller relaxes. Here is the demo I prepared for this case: https://stackblitz.com/edit/angular-ngx-ui-scroll-1-2-2-auto-prepend-when-bof

**Comment by DaveLomber** [comment]
A super cool feature would be observable eof$ / bof$, which will solve the issue in the most elegant way :)

**Comment by dhilt** [comment]
@DaveLomber Generally eof/bof case could be easily handled right inside the `Datasource.get` implementation. You pass index-count items array to the ui-scroll, you know if the result array' length is less than `count`, you know the borders and can run any custom process based on this knowledge.

But perhaps it's not a bad idea to arrange new Observables on the Adapter object... Let me think a bit!

**Comment by DaveLomber** [comment]
Thanks

that's what I'm doing currently with `Datasource.get`.

With observable eof$ / bof$ it will be just more elegant and self-explanatory solution.

And let me please go a little bit deeper with this. In reality, when working on chat apps, where it needs to implement messages stream, it's not required to get a callback once a eof$ is reached, but it's required to get it a bit earlier, e.g. when there are only 2/3 screens of data left to show. 

In this case it will be super cool to introduce one more param: `eofThreshold/bofThreshold ` which can have same value as `padding`. So what devs want is to get a call of `eof$` when 2/3 screens are left to show, so the new data can be retrieved before real eof.

As a quick hint what it all means - we can check ReactNative FlatList `onEndReached` and `onEndReachedThreshold` https://facebook.github.io/react-native/docs/flatlist#onendreachedthreshold

**Comment by dhilt** [comment]
@DaveLomber The threshold parameter you want is exactly the [padding setting](https://dhilt.github.io/ngx-ui-scroll/#/settings#padding). The doc speaks of `padding` that it

> determines viewport outlets relative to the viewport's size that need to be filled. For example, 0.5 means that we'll have as many items at a moment as needed to fill out 100% of the visible part of the viewport, + 50% of the viewport size in backward direction and + 50% in forward direction.

If you want trigger new rows fetching when you pass by 2/3 of the viewport outlet, then use `settings.padding` = 0.66. This way you may get bof triggered as early as needed.

**Comment by dhilt** [comment]
v1.3.2 had been released
It contains `Adapter.bof$` and `Adapter.eof$` properties. See [how to use it](https://dhilt.github.io/ngx-ui-scroll/#/adapter#bof-eof).

@mariah123  @DaveLomber

**Comment by DaveLomber** [comment]
Thanks @dhilt !

just tried it

the only one thing I was required to add is an additional check, otherwise I was getting 2 load more requests

```
  this.datasource.adapter.bof$.subscribe(() => {
      if (this.datasource.adapter.bof) {
        this.getMoreMessages();
      }
    });
```

**Comment by dhilt** [comment]
@DaveLomber You cam make it simpler:

```javascript
  this.datasource.adapter.bof$.subscribe(bof => bof && this.getMoreMessages());
```
