### ISSUE TITLE
Problem with 'first' element on scroll area

### ISSUE THREAD

**Issue by boskras** [dhilt/ngx-ui-scroll#113]
Hi,
I've noticed weird behaviour while detecting the first element on ViewPort.

In my app I've got top-bar header which height is **60px**.
Sometimes when I use `reload(_someIndex_)` the first element is not correctly recognized, because previous item bottom boundary is at **60.XXXXXXX px** so literally it's pointing correctly that the first item is the previous one, but I think that it would be nice to have some buffer maybe at least 2-3px? Perfect it'll be to have the possibility to put this into Datasource settings.

Regards

**Comment by dhilt** [comment]
@boskras Please correct me if I didn't catch the idea:

 - you have item N int the top and say 5% of item N-1 above 
 - you do reload by topmost visible item index which is technically N-1
 - after reload you see 100% of item N - 1 (item N is just below)
 - but you'd like to have 100% of item N and throw away 5% of the previous one instead

And the point is the mechanism of the topmost visible item detection could be improved by some new parameter allowing to ignore, say, up to 99.99% of first/last visible item in favour of next item which is 100% visible. Correct?

**Comment by boskras** [comment]
I don't know if I caught what you meant, so I'll write it as I have now :)

1. Settings of Datasource: bufferSize: 2, padding: 0.5
2. My page look: 60px header (topbar), below scrollig list.

Currently when `scroll-area` is reloaded then N-1 element (just above the ScrollViewPort - so not visible for the User) bottom prop value of `getBoundingClientRect()` is 60. In this scenario, everything is fine and the first element is pointed correctly.

BUT

Sometimes when `scroll-area` is reloaded N-1 element bottom prop value of `getBoundingClientRect()` is a very little more than 60 - eg. 60.59XXXXX. Then the first element is pointing to this N-1 - because, in fact, this N-1 element is theoretically at ScrollViewPort (0.XXXpx), but this is not noticeable for User.

My proposition is to add some sort of buffer/dead zone after which the `first` element is detected - eg. it must at least exceed 5px from top of ScrollViewPort

I hope that this explanation is better.
For better understanding please look at attached SS: May is selected at the left menu despite that, in fact, June is the first visible to the user element - this is because May is very very slightly (below 1px) in ScrollViewPort
![first-element-scroll-issue](https://user-images.githubusercontent.com/24208466/72149031-7d696880-33a2-11ea-9d41-48fe5f32dded.png)

**Comment by dhilt** [comment]
@boskras Ok! is it correct that the dead zone you mentioned is alway less than 1px in your case? This way I would assume that it's a matter of fractional calculation somewhere inside the ui-scroll and it would be right idea to treat it as a Bug and fix it.

If no, and we really want to ignore, say, 5% of previous row (okay, up to 99%), then I'll put the Enhancement label to this issue and start thinking on implementation.

**Comment by boskras** [comment]
Sorry for the delay. Now there is no dead-zone at all because even if component appears in ScrollViewPort at a fractional part of the pixel then it's treated like it was first. My proposition is to add this possibility to define that component must at least be visible to the user with a defined amount of pixels.

Currently, I've implemented my own method to detect the element if it appears at least 10 pixels below the upper limit of the ScrollView boundaries

**Comment by dhilt** [comment]
@boskras Great to hear the issue was overcome! I'd like to have a look at what you've done if it's possible... is it the App fix or did you fork the lib and update it? This also might be useful for future users I guess.
