### ISSUE TITLE
Scrolling up doesn't always render items

### ISSUE THREAD

**Issue by lmreicks** [dhilt/ngx-ui-scroll#116]
## Scrolling up not working as expected

Scrolling down seems to work perfectly, but scrolling up will often not update the view leaving a huge whitespace. The whitespace doesn't go away until you scroll way past it.

In the gif, the true/false at the top is adapter.isLoading
![ui-scroll](https://user-images.githubusercontent.com/25748957/72180390-b60e3f80-33ac-11ea-98be-e25d39b4ec53.gif)

#### Component
```typescript

public datasource: Datasource = new Datasource({
	get: (index, count, success) => {
		success(this.getData(index, count));
	},
	settings: {
		startIndex: 0,
		padding: 1
	}
});
...

public getData(index, count) {
	let data = [];
	let start = Math.max(index, 1) - 1;
	let end = Math.min(count + index, this.filteredData.length)
	for (let i = start; i < end; i++) {
		data.push(this.filteredData[i]);
	}
	return data;
}
```

#### Template
```html
<ol class="card-body pl-3 viewport dd-list">
   <my-custom-component  *uiScroll="let item of datasource" [style.height]="item.Height + 'px'"></my-custom-component>
</ol>
```

Is there something I could change in my configuration to fix this?

**Comment by dhilt** [comment]
@lmreicks Thanks for the issue! Looks like it freezes randomly and don't run until something makes it work again. I need to investigate the reasons and your code sample is not enough (it looks ok for me). The best option would be to build a standalone shareable repro, and you may fork [this stackblitz](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-2-2-inverted-datasource) and shift your sample infrastructure (styles, components, filteredData) there.

**Comment by lmreicks** [comment]
@dhilt  I think I figured out the issue. I needed to specify the minIndex to be 0. I was trying to hack around the indexing at 1. I think the default for minIndex and startIndex should be 0, almost every sort of array is indexed at 0, not 1. There should also be a better comment explaining what these variables do. 

Otherwise, great library!! Very easy to set up and it looks awesome! Great work!

**Comment by dhilt** [comment]
👍 good to know you have fixed your issue, please feel free to submit new ones!
