### ISSUE TITLE
Testing issue: 'Cannot read property 'unsubscribe' of undefined' in Workflow finalize

### ISSUE THREAD

**Issue by lmreicks** [dhilt/ngx-ui-scroll#118]
I'm trying to test a component using uiScroll and I'm getting this error for all of the tests. Error is on line 306 of workflow.ts. Any ideas on how to fix it? Also, any general tips on testing? 

I'm using jest (24.8.0) and my set up (roughly):

**Component**
```typescript
public datasource: Datasource = new Datasource({
	get: (index, count) => this.getData().pipe(
		switchMapTo(this.filterService.Filters$),
		map(filters => this.filterData(filters)),
		tap(filtered => this.data = filtered),
		map(filtered => {
			if (filtered == null) {
				return [];
			}
			let data = [];
			let start = Math.max(index, 0);
			let end = Math.min(count + index - 1, filtered.length - 1);
			for (let i = start; i <= end; i++) {
				data.push(filtered[i]);
			}
			return data;
		})
	),
	settings: {
		minIndex: 0,
		startIndex: 0,
		bufferSize: 10,
		padding: 0.3
	}
});
```
**Template**
```html
<div class="card-body viewport">
	<custom-component  *uiScroll="let item of datasource" [style.height]="item.Height + 'px'"></custom-component>
</div>
```

**Comment by dhilt** [comment]
@lmreicks 
Basically, I don't see any problems in your code sample, I believe the this is infrastructure issue and something is wrong with initialization-disposing processes timing.  `Cannot read property 'unsubscribe' of undefined` on the Workflow dispose

https://github.com/dhilt/ngx-ui-scroll/blob/b54e390a82b652dd25d9f49d17c7646be5a7c49b/src/component/workflow.ts#L306

might mean only one thing: initialization of the workflow had not been run properly, which is possible in case you dispose the workflow immediately after its initialization AND the initialization of the workflow is delayed by 1 or more ms ([look here](https://github.com/dhilt/ngx-ui-scroll/blob/b54e390a82b652dd25d9f49d17c7646be5a7c49b/src/component/workflow.ts#L35-L39)).

So you mat try to set `devSettings.initDelay` to 0 (the default is 1: [link](https://github.com/dhilt/ngx-ui-scroll/blob/v1.2.2/src/component/classes/settings.ts#L31); how to set is [here](https://github.com/dhilt/ngx-ui-scroll#development); not sure if it can help) OR dispose the workflow in the next callstack than initialization one (not sure, maybe destroying your test components could be postponed)...

Also I think it might be helpful if you take a look at the lib tests folder (though it is not `jest`):

 - https://github.com/dhilt/ngx-ui-scroll/tree/master/tests
 - https://github.com/dhilt/ngx-ui-scroll/tree/master/tests/scaffolding

You may fork the repo and run tests locally to get how it works.
