### ISSUE TITLE
Adapter.check() does not clean up the state properly

### ISSUE THREAD

**Issue by dhilt** [dhilt/ngx-ui-scroll#123]
Came from https://github.com/dhilt/ngx-ui-scroll/issues/112#issuecomment-575954135.

During the Check process `state.fetch.isReplace` becomes `true` and the value (sometimes) don't reset when the process is done. This breaks further fetch-render chains handling:

https://github.com/dhilt/ngx-ui-scroll/blob/b54e390a82b652dd25d9f49d17c7646be5a7c49b/src/component/processes/render.ts#L33-L39

New fetched items won't be processed until something resets `state.fetch.isReplace` flag.

Need to
 - find out where the state has to be cleaned up
 - fix the case
 - cover it with tests

**Comment by dhilt** [comment]
@StriderRanger v1.2.5 is published, it fixes your last issue

**Comment by StriderRanger** [comment]
@dhilt As always, thank you for your constant support :) I will install v1.2.5 and confirm that it works in my environment.

**Edit:** v1.2.5 is installed and works well
