### ISSUE TITLE
Content alignment in case of lack of items

### ISSUE THREAD

**Issue by soulfly** [dhilt/ngx-ui-scroll#125]
Hi there

we are building a chat app and now face one issue with content alignment when we have only couple messages to display

This is a demo of the issue, by default all items are aligned to top, but in chat apps it should be aligned to bottom 

![Screen Shot 2020-01-23 at 1 43 34 PM](https://user-images.githubusercontent.com/373137/72981858-77ce4280-3de6-11ea-8ca5-392408653fb8.png)

I tried to play with flex boxes and especially with `justify-content: flex-end;` and `align-items: flex-end;` but nothing helped

Could you please suggest the way how we can do it with the lib

**Comment by dhilt** [comment]
@soulfly That's interesting! By default the scroller extends so-called forward padding element to fill out the visible part of the viewport if there are not enough items in the buffer. This method is responsible for paddings adjustment during initialization/reload:

https://github.com/dhilt/ngx-ui-scroll/blob/8538ad737408c0b36ea8fa3a1c64ce27cbd9586a/src/component/classes/paddings.ts#L42-L50

I believe this behaviour might be configurable. Let me think a bit what can be done.

**Comment by soulfly** [comment]
@dhilt please let me know if there are any workarounds we can apply until a new release with the configurable will be pushed

**Comment by dhilt** [comment]
@soulfly I'm afraid this can't be overcome without internal changes... Though maybe you may try to emulate top padding via row of dynamic height:
 - add "height" property to data items; if "height" is not set it should not have an impact on the template
 - say, scroller requests [1..10] items and `datasource.get` will return 2 items with "height" unset: [1..2]
 - wait for the scroller finishes its work, `isLoading$` subscription with `false` value
 - calculate extra height arranged by bottom padding and set the value to the item 2 "height" via `Adapter.fix({ updater })`
 - this way item 2 will be extended to fill out whole visible viewport
 - after this run `Adapter.check()` -- scroller will take dynamic update into account

This is very rough and hacky thought. Hope this helps.

I think I will take this issue this week

**Comment by DaveLomber** [comment]
I think we need to do something like this:

```
      settings: {
        contentAlignment: "bottom" // default is 'top'
      },
```

and internally do some swap like this:

    forwardPadding.size = bwdSize;
    backwardPadding.size = fwdSize;

**Comment by DaveLomber** [comment]
Hi @dhilt 
do you have any updates when will you able to release a new release with this feature?
This is probably I final main frontier at your side
thank you

**Comment by dhilt** [comment]
Just fixed issue https://github.com/dhilt/ngx-ui-scroll/issues/131, so this one may be next

**Comment by dhilt** [comment]
@soulfly There is one suggestion that might relate to this issue (thanks to @DaveLomber, [issue 135](https://github.com/dhilt/ngx-ui-scroll/issues/135)) based on css transform

```css
.viewport {
  width: 100px;
  height: 200px;
  overflow-anchor: none;
  overflow-y: scroll;
  transform: scale(1, -1);
}

.item {
  height: 20px;
  transform: scale(1, -1);
}
```

Change `MAX` to 2 in this demo: https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-3-inverted-by-css

The only trade-off we need to deal with is that the scrolling itself is also being inverted.

**Comment by soulfly** [comment]
Thanks @dhilt 
This is indeed very interesting 

Btw

In past, to revers a scroll on Chrome, I did the following:

display: flex
flex-direction: column-revers;

and this also saved a correct scroll direction 

But, I tried it with the lib and it produces some very strange issues
Is there any reason of it?

**Comment by dhilt** [comment]
@soulfly There is an auto-correction mechanism that handles and sets the scroll position manually many times in runtime. It might conflict with native things...

**Comment by dhilt** [comment]
@soulfly v1.3.4 had been released, it contains "reverse" experimental settings, which might help in your case. I posted the demo describing it: https://dhilt.github.io/ngx-ui-scroll/#/experimental#inverse-setting

Please take a look!

**Comment by soulfly** [comment]
many thanks!
I will have a look and get back with the results

**Comment by soulfly** [comment]
just finally had some time to perform more tests

So far it displays it OK which is awesome 

The only one thing I noticed is a one side effect

When a user switches chats, we do a datasource re-creation :

     this.datasource = null;

     ... 

     this.datasource = new Datasource ({ .... })

so new data comes here

and here we have a loading state tracker 

     this.datasource.adapter.isLoading$.subscribe(isLoading => { ...});

and sometimes when we do this chat switch, it reports `isLoading=true` and never back to `isLoading=false`

I do not see this issue w/o this new invers setting

**Comment by soulfly** [comment]
so far I did a dirty fix - after initial loaded data, I did a 1px scroll which produces `isLoading=false`

      const scrollPosition = this.messageList.nativeElement.scrollTop + 1;
      this.datasource.adapter.fix({ scrollPosition });

**Comment by dhilt** [comment]
@soulfly I'm happy to know the issue is resolved! One thing surprised me in your last comments, I mean `this.datasource = null`. I think this should go in another way and I see two options:

 - replace the logic of `datasource.get` method instead of `datasource` itself when you need to change chat; let the datasource object keep its reference, do whatever you want inside  the `datasource.get` method body;

 - a new API can be provided to give an ability to replace/re-initialize the Datasource on the fly, which can be useful also for changing the settings.

I created a separate issue for the second option: https://github.com/dhilt/ngx-ui-scroll/issues/139.

Nulling the Datasource seems dangerous... anyway, If you want to add something to this last piece, please follow [new issue](https://github.com/dhilt/ngx-ui-scroll/issues/139).

**Comment by soulfly** [comment]
@dhilt let me provide more info on this matter

- actually `this.datasource = null` work pretty well as from what I see. Before it, I did `reload` on chat switch, which also worked pretty well, but I ran into issue when we switch to an empty chat - there were prev chat messages displayed on a chat window, some clearing was not done well I guess.  After switching to `this.datasource = null`  it started to work well. 
- the issue with `isLoading` hanging is started to appear when we added `inverse: true`, and it does not matter what we use - `this.datasource = null`  or `reload` - in both cases it's hanging sometimes in a 'true' state. If we remove the `inverse: true` then it started to work well again 

This is what we can clearly reproduce at our side.
Please let me know if I can help somehow with tracking down this issue. 

Regarding https://github.com/dhilt/ngx-ui-scroll/issues/139 - I think the best option can be to introduce a new method something like `cleanAndReload` - same reload, but with complete state & UI cleaning before reload.

**Comment by dhilt** [comment]
@soulfly The only thing the scroller provides to the host component is the list of items, and the scroller flushes this list on reload, moreover it hides the DOM elements bound with these items before flushing:

https://github.com/dhilt/ngx-ui-scroll/blob/02ae0f9fe8dd98fcf5ba1fd55ae9436f93c4e62a/src/component/classes/buffer.ts#L43-L47

So, speaking of the App UI, there is nothing more to clean up on the scroller end on reload. The issue seems App specific and needs to be investigated in appropriate environment. Also, I think, the most easy and stable approach on the replacement of the scroller-related UI would be to rebuild this UI completely, I mean something like "ng-if" which leads to destroying the Html. So, if it is possible, I would suggest to think about how to destroy the chat view and re-create it on chat switching. Adapter.reload will be excessive in that case, you'll just get a new instance of Scroller.

On the "inverse" problem. I'd like to have a repro (stackblitz or at least more detailed steps), but first could you try [v1.4.1](https://github.com/dhilt/ngx-ui-scroll/releases/tag/v1.4.1)? It fixes some issue for multiple Adapter.reload calls and this way relates to your scenario.

**Comment by soulfly** [comment]
Re inverse problem - seems it's more or less same as here - probably some race conditions 
https://github.com/dhilt/ngx-ui-scroll/issues/130#issuecomment-579795833

Anyway I might need to do more tests

**Comment by soulfly** [comment]
@dhilt probably there will be good to have a public datasource method like `reset` which will do 2 things:
- cleanup UI
- reset the internal state 

Nullify the `this.datasource = null` is obviously a bad idea, so the only one possible thing is to use `reload` when switch chats. 

But even with `reload`  there is an edge case, let me explain it.

Here is what I do currently:
- a user switches a chat 
- we clean the UI by *ngIf
- we got a new data from redux, with new messages (messages.length > 0) and call `reload`, which works pretty well. 
- the one issue here is when a user switches to an empty chat. In this case  no 'reload' call is made. So far it looks good - no messages displayed cause all is cleaned.  But, the internal state of 'datasource' is completely wrong. And If we will call a `append` then the things will be broken.

Having a public datasource `reset` method can help here. I see the following flow using it:
- a user switches a chat 
- we clean DS and the UI by calling `datasource.reset`
- we got a new data from redux, with new messages (messages.length > 0) and call `reload`.
- If no messages - the DS state is reset so we are covered here

**Comment by soulfly** [comment]
@dhilt just want to get back to you with the feedback 
Finally tried 1.6.0 and it looks pretty good:

- 'reset' method works great 
-  no 'isLoading' hanging  (which still was there in 1.5.2)

I will continue testing, bit so far it looks pretty good.

Thank you for all your support!

**Comment by dhilt** [comment]
1.6.0 has very important updates related to how we are handling scroll events, so I'm glad to know if it works better than previous versions. Feel free to open new issues!
