### ISSUE TITLE
Recycling scroll items 

### ISSUE THREAD

**Issue by DaveLomber** [dhilt/ngx-ui-scroll#129]
Hi there

while reading the 'Motivation' section on doc I noticed the following explanation of how the lib deals with scroll items: 'It dynamically destroys elements as they become invisible and recreates them if they become visible again.'

I have a question - is it possible to recycle scroll items instead of destroy/recreate? 
What I noticed is if have 'heavy' children components, then the complete 'recreation' process may produce some lags when scroll. Instead - it would be great to just use the same components, but update only input data.

Is there any possibility to deal with recycling ?

**Comment by dhilt** [comment]
@DaveLomber This could be possible in case we are dealing with items of fixed dimension and yes, it would work faster. I am not sure whether the increase will be significant, but anyway it will be completely different story and right now there is no way to provide such an optimization on the ngx-ui-scroll end. It's an architecture matter and the choosing was done a long time ago.

**Comment by DaveLomber** [comment]
Thanks for the feedback, 
at least it's clear now it's by design :) 

Anyway I'm trying to mitigate any potential lags 
For now I came up with the idea to use

```
      settings: {
        bufferSize: 20,
      },
```

so with new elements it will lag only once per 20 items, instead of e.g. 4 times per 5 items. 
From what I see it works a bit better with this setting 

If you have any other recommendations on how to mitigate any potential lags when use more heavier components - please let me know, will be much appreciated

**Comment by dhilt** [comment]
@DaveLomber  A good practice might be to give `bufferSize` a value corresponds to the viewport visible height. For instance, if the viewport height is 400px and the item heigh is (approximately) 40px, then having `bufferSize` = 10 the scroller should fill out the viewport in a single request. Also, `padding` setting should be taken into account. At last, `bufferSize` defines minimal number of requested items, so when you reach the edge of the buffer, the scroller will request `bufferSize` or more items.

If "lags" relate to asynchronicity during fetching, then it might be relevant to implement some kind of pre-fetch/cache mechanism. Say, you may start requesting first `bufferSize + delta` items _before_ rendering the scroller, _before_ rendering the component containing the scroller or even right on the app start. Then you'll need to update `Datasource.get` logic to deal with this pre-stream if indexes match.
