### ISSUE TITLE
Is it safe to call 'append/prepend' while rendering process ?

### ISSUE THREAD

**Issue by DaveLomber** [dhilt/ngx-ui-scroll#130]
Hi there, 
I would like to discuss one thing re this lib

What I mean by 'rendering process' is the following (probably there is a better term):
- let's say, based on our settings, we have 30 items always added to DOM. 
- when we initialize a data source or call a 'reload' method - a ngx-ui-scroll lib starts to bufferize and renders the items, let's say it does it in 3 steps/calls of 'get' data: 0-9,  10-19, 20-29

And then, in the middle of this process, let's say we call 'append/prepend' method. Is it safe to do it?

Sometimes we notice some blank spaces or wrong positioning, which is not good.
We tried to use 'isLoading$' and  call  'append/prepend' only if it's false, but still sometimes we see some issues.

So my questions are:
- Is it safe to call 'append/prepend' while rendering process ?
- Is there a method like 'isLoading$', but to track where all 3 portions (0-9,  10-19, 20-29) are done?

**Comment by dhilt** [comment]
@DaveLomber It's a good question, yes, these operations are not safe and should be run when the scroller relaxes. In v1.3.0 (released 5 days ago) the similar issue had been solved for the Reload process and now you may run `Adapter.reload` method at any time. But I'm not sure if it is possible for Append/Prepend processes because in that cases we need to deal with current Buffer and updates must be consistent.

3 cycles you mentioned, are they done one by one automatically? If yes, then the scroller handles it during a single workflow run and in this case `isLoading$` is your friend. See [this demo notes](https://dhilt.github.io/ngx-ui-scroll/#/adapter#is-loading-advanced). And you see issues in this scenario, I would really like to investigate it.

Going back to thinking about Buffer consistency and dealing with concurrent processes that affect it, the following thoughts come to my mind. The easiest approach might be just to implement an internal mechanism making concurrent operations safe by delaying them until current "workflow cycle" is done. Or until current "inner loop" is done which would be more useful and fast but might require more efforts to implement.

Also, "inner loop" variant may be not what you might want, because in this case you'll get, say [0-9, X = 10, 11-20, 21-30] instead of [0-9, 10-19, 20-29, X = 30] for "workflow cycle" variant. In addition there could be an option allowing to proceed concurrent update (say, Append) after "inner loop" or after "workflow cycle". 

 What do you think?

**Comment by DaveLomber** [comment]
> 3 cycles you mentioned, are they done one by one automatically?

either after datasource initialization OR after reload call

>  After the uiScroll is initialized and started relaxing, we see that there are 4 inner loops done, while isLoading counter is 1.


Aha this is good to know. Actually I read already this demo notes, but did not got an idea, but now its' clear. So I should try 'isLoading$' here.

Actually I use now 'loopPending$' so maybe it's a case and we can resolve the issue by switching to  'isLoading$'; 
But, one thing I want to highlight - the reason I switched to 'loopPending$'  instead of 'isLoading$' is because we faced one issue where 'isLoading$' subscription just hanged and did not return any value either false to true. So we started to trying any diff things and switched to   'loopPending$'. If you have any thoughts re this - please share.

For now I'm going to switch back to 'isLoading$' and see how it works, do we still have this 'hangs' issue or not

**Comment by DaveLomber** [comment]
I can confirm I sometimes have issues with isLoading$ - it just stuck 

Here is my code 

```
private doAdapterAppend(items, eof = false) {
    console.log("[DataSource][doAdapterAppend]", this.datasource.adapter.isLoading);

    if (this.datasource.adapter.isLoading) {
      const sub = this.datasource.adapter.isLoading$.subscribe(isLoading => {
        console.log("[doAdapterAppend]1", isLoading);
        if (!isLoading) {
          sub.unsubscribe();
          this.doAdapterAppendInternal(items, eof);
        }
      });
    } else {
      console.log("[ChatWindowComponent][DataSource][doAdapterAppend]2");
      this.doAdapterAppendInternal(items, eof);
    }
  }

  private doAdapterAppendInternal(items, eof = false) {
    this.datasource.adapter.append(items, eof);
 }
```

And I do not get a  `console.log("[doAdapterAppend]1", isLoading);` log until I will do some reload e.g. scroll messages or switch chat 

Is there anything I could debug ?

**Comment by dhilt** [comment]
@DaveLomber The code seems correct. Could you please put it on [stackblitz](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0) for I can dive in it run-time? If it's not an option for you, you may instead attach dev-log to your next reply, it also may help, though it will take more time to investigate.

**Comment by DaveLomber** [comment]
just did some debugging

I would say  the 'isLoading' is locking to 'true' somewhere before my append
and then do not re-set its value to 'false' because of this check 

```
    if (state.scrollState.scrollTimer === null) {
         state.isLoading = false;
    }

```

**Comment by DaveLomber** [comment]
@dhilt I guess I can conclude
at least partially 

something happens probably after prepend or just after scroll

my prepend looks like this:

```
  private doAdapterPrepend(items) {
    console.log("[ChatWindowComponent][DataSource][doAdapterPrepend]", this.datasource.adapter.isLoading);

    if (this.datasource.adapter.isLoading) {
      const sub = this.datasource.adapter.isLoading$.subscribe(isLoading => {
        console.log("[ChatWindowComponent][DataSource][doAdapterPrepend]1", isLoading);
        if (!isLoading) {
          sub.unsubscribe();
          this.doAdapterPrependInternal(items);
        }
      });
    } else {
      console.log("[ChatWindowComponent][DataSource][doAdapterPrepend]2");
      this.doAdapterPrependInternal(items);
    }
  }

  private doAdapterPrependInternal(items) {
    const bof = true;
    const fixParams = { minIndex: -Infinity, maxIndex: +Infinity};
    console.log(`[ChatWindowComponent][DataSource][doAdapterPrepend] ${items.length}`, items, fixParams);
    this.datasource.adapter.fix(fixParams);
    this.datasource.adapter.prepend(items);
  }
```

and here are some logs: 

```
[DataSource] Init.run   state.isLoading = true;
chat-window.component.ts:358 [ChatWindowComponent][DataSource][getAdapterData] 0 -> 2 (-3 -> 1). Total: 20, Rendered: 0, bof/eof: false/true, scroll: 0 from 661
chat-window.component.ts:378 [ChatWindowComponent][DataSource][getAdapterData] data 3 (3) [{…}, {…}, {…}]
chat-window.component.ts:2214 [ChatWindowComponent][DataSource][onUserScroll]  bof: false, eof: false, scroll: 0 from 661
chat-window.component.ts:358 [ChatWindowComponent][DataSource][getAdapterData] 0 -> -1 (0 -> 20). Total: 20, Rendered: 3, bof/eof: false/false, scroll: 0 from 636
chat-window.component.ts:378 [ChatWindowComponent][DataSource][getAdapterData] data 0 []
chat-window.component.ts:358 [ChatWindowComponent][DataSource][getAdapterData] 3 -> 22 (-23 -> -3). Total: 20, Rendered: 3, bof/eof: false/true, scroll: 0 from 636
chat-window.component.ts:378 [ChatWindowComponent][DataSource][getAdapterData] data 17 (17) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
chat-window.component.ts:622 [ChatWindowComponent][DataSource][getMessagesDiffs] 20 -> 50 took 0 ms {toAppend: Array(0), toPrepend: Array(20), toUpdate: Array(0), toDelete: Array(0), toInsert: false}
chat-window.component.ts:525 [ChatWindowComponent][DataSource][doAdapterPrepend] true
chat-window.component.ts:1142 [ChatWindowComponent][DataSource] this.messages 50 [] undefined false
ngx-ui-scroll.js:5861 [DataSource] Workflow.prototype.done null
chat-window.component.ts:529 [ChatWindowComponent][DataSource][doAdapterPrepend]1 false
chat-window.component.ts:544 [ChatWindowComponent][DataSource][doAdapterPrepend] 20 (20) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] {minIndex: -Infinity, maxIndex: Infinity}
ngx-ui-scroll.js:3273 [DataSource] Init.run   state.isLoading = true;
chat-window.component.ts:2214 [ChatWindowComponent][DataSource][onUserScroll]  bof: false, eof: false, scroll: 509 from 1145
ngx-ui-scroll.js:5861 [DataSource] Workflow.prototype.done 1902
chat-window.component.ts:622 [ChatWindowComponent][DataSource][getMessagesDiffs] 50 -> 99 took 0 ms {toAppend: Array(0), toPrepend: Array(20), toUpdate: Array(0), toDelete: Array(0), toInsert: false}
chat-window.component.ts:1142 [ChatWindowComponent][DataSource] this.messages 99 [] undefined false
chat-window.component.ts:2214 [ChatWindowComponent][DataSource][onUserScroll]  bof: false, eof: false, scroll: 1629 from 2265
chat-window.component.ts:622 [ChatWindowComponent][DataSource][getMessagesDiffs] 99 -> 99 took 0 ms {toAppend: Array(0), toPrepend: Array(0), toUpdate: Array(0), toDelete: Array(0), toInsert: false}
chat-window.component.ts:1142 [ChatWindowComponent][DataSource] this.messages 99 [] undefined false
chat-window.component.ts:622 [ChatWindowComponent][DataSource][getMessagesDiffs] 99 -> 99 took 0 ms {toAppend: Array(0), toPrepend: Array(0), toUpdate: Array(0), toDelete: Array(0), toInsert: false}
chat-window.component.ts:1142 [ChatWindowComponent][DataSource] this.messages 99 [] undefined false
chat-window.component.ts:622 [ChatWindowComponent][DataSource][getMessagesDiffs] 99 -> 99 took 0 ms {toAppend: Array(0), toPrepend: Array(0), toUpdate: Array(0), toDelete: Array(0), toInsert: false}
chat-window.component.ts:1142 [ChatWindowComponent][DataSource] this.messages 99 [] undefined false
chat-window.component.ts:622 [ChatWindowComponent][DataSource][getMessagesDiffs] 99 -> 100 took 0 ms {toAppend: Array(1), toPrepend: Array(0), toUpdate: Array(0), toDelete: Array(0), toInsert: false}
chat-window.component.ts:473 [ChatWindowComponent][DataSource][doAdapterAppend] true
```

so by some reason, sometimes a lib do not re-set 'isLoading' value to 'false' because of this:

```
  if (state.scrollState.scrollTimer === null) {
         state.isLoading = false;
  }
```

**Comment by DaveLomber** [comment]
@dhilt maybe, if not resetting it here

```
   if (state.scrollState.scrollTimer === null) {
         state.isLoading = false;
  }
```

then we need to reset it inside this timer ? 

            state.scrollTimer = (/** @type {?} */ (setTimeout(function () {

                state.isLoading = false;

                state.scrollTimer = null;
                scroller.logger.log(function () { return "fire the timer (" + scroller.state.time + ")"; });
                workflowOptions.byTimer = true;
                Scroll.run(scroller);
            }, diff)));
```

**Comment by DaveLomber** [comment]
To be more precise it should be       `scroller.state.isLoading = false;` inside timer 

I just did it and it resolves my issue

@dhilt  need your feedback here

**Comment by dhilt** [comment]
@DaveLomber Any practical suggestion should be approved by current test specifications. Your particular change breaks 37 of 204 tests. I agree, there might something not fine with resetting `isLoading` and `scrollTimer` null check at the `Workflow.end` point, but this is the only place where this flag is being dropped, so we need to deal with it very carefully. I'm sure it is possible to discover the cause and provide clean fix, but it needs to be done in agreement with common workflow, and first I'd like to write some failing tests. And I need to catch broken scenario, currently it is unclear for me.

Dev-log I meant does relate to [devSettings.debug](https://github.com/dhilt/ngx-ui-scroll#development) option set to `true`. and it would be better if you attach it as a file for not to pollute the thread. But the best option still would be a stand-alone repro as it would be a prototype for new test spec.

Thanks for helping to make lib better!

**Comment by DaveLomber** [comment]
Let me try to prepare a  stackblitz demo

**Comment by DaveLomber** [comment]
Ok so far I prepared a stackblitz demo
https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0-i9ky7u

but was not able to repro...

what I can say about my use case is the following:
- a user switches a chat window
- we do adapter reload to show new chat messages 
- then we check how much messages we have in redux and if it's < 50 then we have a BOF and hence perform a load more which resulted in adapter prepend. 
- after adapter prepend  - we got 'isLoading=true' which does no return to false 

As a quick dirty workaround, I just did the following:

 ```
         setTimeout(() => {
            this.doAdapterPrepend(dataToPrepend);
          }, 500); 
```

seems it works

but anyway I feel  there is something wrong, maybe some timing issues, cause a stackblitz demo has very simple child components and all works fast  here

**Comment by dhilt** [comment]
@DaveLomber Thanks for providing details, but please add the scroller dev-log taken from your environment with processes logging enabled:

```
    devSettings: {
      debug: true,
      logProcessRun: true
    }
```

Do not turn off your internal app logs as they might be helpful too, especially around the point of `isLoading` hanging.

Also, let's not abandon the efforts to reproduce it via live demo...

**Comment by DaveLomber** [comment]
@dhilt I tried this fix
https://github.com/dhilt/ngx-ui-scroll/issues/130#issuecomment-579805410 

so far I got a success after ran tests

the only one thing I noticed - sometimes tests are not stable, even in master branch - getting randomly "Error: Timeout - Async callback was not invoked within 2000ms (custom timeout)"

**Comment by DaveLomber** [comment]
@dhilt  regarding this issue with 'isLoading' hanging in a 'true' state - I guess I have a potential reason of this. 
Randomly I faced this issue again with some case in my app and what I noticed is that I created a 'datasource' object before my scroll div is rendered in DOM, which then caused this  'isLoading' hanging in a 'true' state.

Here is what I have in my template:


        
        <ul *ngIf="!showSearchResults && !showFullEditor" id="message-list" #messageList
            vpScrollList
            (onUserScroll)="onUserScroll($event);"
            [ngStyle]="messageListStyle">

          <ng-container *ngIf="datasource">
            <div *uiScroll="let data of datasource;"
                  class="message-item"
                  id="message-{{ data.message.id }}">
           
              ....

So I'm going to check this theory for more and then will update here

**Comment by dhilt** [comment]
@DaveLomber Would be great to have a repro over the latest lib version. But what I want to say is that `isLoading` is the property of the Workflow, which is being initialised after the component passed through `ngOnInit` hook and being destroyed on `ngOnDestroy` hook. If you destroy-recreate DOM randomly, I guess, it may lead to the issue and the issue needs to be fixed possibly on the app side, possibly on the lib end.

**Comment by dhilt** [comment]
There is issue https://github.com/dhilt/ngx-ui-scroll/issues/178 and the next minor release (1.7) will have to include "await" syntax for Adapter methods. This should drastically simplify handling of the Adapter methods asynchronicity.
