### ISSUE TITLE
firstVisible/lastVisible getting stuck for certain dataset sizes

### ISSUE THREAD

**Issue by hungyiloo** [dhilt/ngx-ui-scroll#131]
I've reproduced the issue here: https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0-jzc5hb

The key to getting this to happen seems to be capping the total record count to anything less than `2*bufferSize` and then attempting to scrolling down until EOF. In the stackblitz above, I've set `bufferSize` to 30 and stopped generating items before hitting a total of 55 items. If I set the boundary to ~63, it seems to get stuck much less often, but still gets stuck occasionally.

I'm trying to use lastVisible and firstVisible to implement a custom scrollbar, so any help on this would be very much appreciated. This is still the best virtual scroller for angular that I've used so far. 

Thank you!

**Comment by dhilt** [comment]
@hungyiloo Thanks for the issue and demo! This is the lib's bug, I was able to reproduce it and catch the reason. In two words, first/lastVisible calculation occurs  in the end of each UiScroll Workflow cycle, the Workflow cycle is being run on user' scroll, but there is a check that blocks the Workflow continuing running if there are no more items to be fetched (when both BOF and EOF have been reached at the same time):

https://github.com/dhilt/ngx-ui-scroll/blob/ecede163d3616b54bb2a5138ca38fa279bab6334/src/component/processes/scroll.ts#L183-L189

I guess I can't just remove this check for performance reasons. Instead I will think how to run first/lastVisible calculation procedure in BOF+EOF case.

Putting it here for the fix purpose. Will take this issue as soon as possible.

**Comment by hungyiloo** [comment]
That makes sense, and thanks for the quick response. Really appreciate your help!

**Comment by dhilt** [comment]
@hungyiloo ngx-ui-scroll v1.3.3 is released, it contains the fix
