### ISSUE TITLE
TypeError: Cannot read property 'unsubscribe' of undefined in workflow.ts

### ISSUE THREAD

**Issue by 0xSeb** [dhilt/ngx-ui-scroll#132]
Hi there !

I found myself in case where 

```
this.workflowSubscription.unsubscribe();
this.itemsSubscription.unsubscribe();`
```
in _/src/component/workflow.ts_

Raised the exception :   `Cannot read property 'unsubscribe' of undefined.`

I looked at https://github.com/dhilt/ngx-ui-scroll/issues/118 but I'm not in a test case so I don't know if it's relevant to set the initDelay in the dev_settings ? 

Thanks for your work ! :+1:

**Comment by dhilt** [comment]
@OxSeb I need to have full scenario... Is it possible for you to create a repro? you may fork this [stackblitz sample](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0)

**Comment by 0xSeb** [comment]
I'm sorry it's an "in production" really big app and I won't be able to make a full repro scenario, even for me to reproduce the end user issue ..
Woudn't it be easier to add a test around `this.workflowSubscription.unsubscribe();` 
and `this.itemsSubscription.unsubscribe();` to make sure they're initialized before unsubscribing them? 

Thanks for your fast answer btw !

**Comment by dhilt** [comment]
@OxSeb Well, could you please [enable dev-log](https://github.com/dhilt/ngx-ui-scroll#development) and attach it to your next reply? It might help.

Also, it would be helpful if you describe how you use the lib in your app: how it looks in the code of the app component and the template.

**Comment by dhilt** [comment]
@0xSeb ngx-ui-scroll v1.4.0 is released and available via npm, it contains fix for this issue, thanks to @lmreicks! Release notes: https://github.com/dhilt/ngx-ui-scroll/releases/tag/v1.4.0
