### ISSUE TITLE
getting wrong (old) indexes in inverted 'getAdapterData' when scroll (iOS WebView) 

### ISSUE THREAD

**Issue by DaveLomber** [dhilt/ngx-ui-scroll#135]
Hi there, 

it seems we are facing one more issue on iOS WebView when scroll to older messages

Here is our code:

    DATA_SOURCE_ITEMS_MIN_INDEX = 0

    get: (index, count, success) => {
        const data = this.getAdapterData(index, count).reverse();
        success(data);
     }

    private getAdapterData(_index: number, count: number) {

      const index = -_index - count + DATA_SOURCE_ITEMS_MIN_INDEX;
      const data = [];
      const start = Math.max(DATA_SOURCE_ITEMS_MIN_INDEX, index);
      const end = index + count - 1;

      console.log(`[ChatWindowComponent][DataSource][getAdapterData] ${start} -> ${end} (${_index} -> ${_index + count}).`);

    ...
    }

And here is what we are getting:

```
[DataSource][getAdapterData] 1 -> 20 (-21 -> -1). 
[DataSource][getAdapterData] 22 -> 41 (-42 -> -22). 
[DataSource][getAdapterData] 42 -> 61 (-62 -> -42). 
[DataSource][getAdapterData] 62 -> 81 (-82 -> -62). 
[DataSource][getAdapterData] 30 -> 49 (-50 -> -30).   <----
[DataSource][getAdapterData] 80 -> 99 (-100 -> -80). 
[DataSource][getAdapterData] 101 -> 120 (-121 -> -101). 
```

This causes some UI jumps , as it's requesting wrong items data, which is obviously not in a. new port 

Could you please let us know re possible reasons

Thanks

**Comment by DaveLomber** [comment]
@dhilt  here is a demo video using your Inverted code sample and iOS Safari browser

as you see, it works well with normal order, but it's lagging with an inverted one 

https://easyupload.io/bw2rx0

This is definitely something wrong on iOS Safari browser / web view

**Comment by DaveLomber** [comment]
and Safari Desktop works perfect, so it's only mobile related

**Comment by dhilt** [comment]
@DaveLomber I think wrong data request is caused by wrong scroll behaviour and not vice versa. Datasource implementation seems cross-browser, isn't it? But the scrolling itself... it depends on device and browser. Your demo reminds me of scroll-top inertia issues. You may get some details [here](https://github.com/dhilt/ngx-ui-scroll/issues/87#issuecomment-475085865). These overjumps strongly correlate with the idea described in that comment. So I do believe, there might be browser specific issues, but such an issue should be reproducible for any datasource implementation.

By the way, is there a way to debug mobile Safari without iOS device? How do you deal with it?

**Comment by DaveLomber** [comment]
@dhilt What I can say is that the issue is not only on Safari iOS, but also Chrome iOS - so in general it's iOS browser and iOS WebView

Re debug mobile Safari - if you use macOS then you can install Xcode and run iOS Simulator there

**Comment by DaveLomber** [comment]
Just checked this https://github.com/dhilt/ngx-ui-scroll/issues/87
btw I use the latest lib version 

Please let me know if I can help somehow here

**Comment by DaveLomber** [comment]
@dhilt  I may have an alternative solution on how to implement an inverted data source.. by applying a transform property 


```
.viewport {
  width: 100px;
  height: 200px;
  overflow-anchor: none;
  overflow-y: scroll;
  transform: scale(1, -1);
}

.item {
  height: 20px;
  transform: scale(1, -1);
}
```


A link to https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0-sl8sek?file=src/app/app.component.css

which seems to work fine even on iOS 

A video demo https://easyupload.io/xqh6xg

do you have anything against this approach of implementing an inverted data source ?

**Comment by dhilt** [comment]
@DaveLomber css approach is damn good (except the scrolling itself is also reversed; could it be fixed?) -- would you like to extend the official demo as follows

<img width="783" alt="Screenshot 2020-02-05 at 18" src="https://user-images.githubusercontent.com/4365660/73855906-c697c580-4845-11ea-9c6d-0f37dfa692c2.png">

The sources are here:

./demo/app/samples/datasource/inverted-datasource.component.ts
./demo/app/samples/datasource/inverted-datasource.component.html

Just add the third window, css tab and some words about. I'll accept the PR quickly.

Meanwhile, I'm going to try iOS mobile debug as yo suggested.

**Comment by DaveLomber** [comment]
"except the scrolling itself is also reversed; could it be fixed" - I did more tests on it today 

It looks good for iOS and Firefox
but is inverted for Chrome, Safari and Android 

I did a deep investigation re this some time in past but did not find a way on how to fix it..

**Comment by DaveLomber** [comment]
And to say more - this 'css' like inverted thing works much much better than Inverted datasource, I really like it... 
the only damn issue is this  inverted scroll effect I can't figure out how to fix it ...
