### ISSUE TITLE
Wrong scroll position on start when an items height > viewport and inverse = true

### ISSUE THREAD

**Issue by DaveLomber** [dhilt/ngx-ui-scroll#141]
There seem to be an issue with wrong scroll position for 'startIndex' setting when an item heigh > viewport height. 

A demo 
https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0-tbjtc1?file=src%2Fapp%2Fapp.component.css 

If we use 

```
.item {
  height: 50px; 
}
```

then all is ok 

but if we set something bigger than a viewport, e.g.

```
.item {
  height: 350px; 
}
```

then there is an issue with proper scroll positioning. 

There can be a case in chat apps, where a message can contain lots of text and the mobile device screen is not so big, so the issue can occur 

Please let me know if anything else is needed too trace it

**Comment by dhilt** [comment]
@DaveLomber The use case makes sense, but I don't see the problem.

In your demo (thanks for the one!) the reversed viewport is used, so the first item (determined by startIndex: 9) is adjacent to the bottom line. I played with its height increasing it from 50 to 215:

![ezgif-1-053edcee384d](https://user-images.githubusercontent.com/4365660/74897629-c1d82300-53a8-11ea-8e9e-6bf0be2a166c.gif)

You see, it is being bigger and bigger while its bottom edge is alway adhered to the bottom of the viewport. When its height becomes greater than the height of the viewport, the text leaves the view. And this seems consistent. Perhaps you want to align the text to the bottom of the row...

**Comment by DaveLomber** [comment]
Hi @dhilt 
I think I was too tired yesterday evening when posting it and provided a bit wrong information to you... 

Let me please clarify it a bit with a new demo 

This is an inverted datasource 

https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0-tbjtc1?file=src%2Fapp%2Fapp.component.ts

Issue N1:
- with  `startIndex: -2` it works well, the top element is 2. When I set ` startIndex: -10, ` then it focus on 9... Actually any value after 4 produces this minus one shift

Issue N2:
- If I remove `startIndex` setting, then here is an original issue I reported - it behaves like if I set `startIndex: -1` - but what I want is to be a scroll on the max bottom position and do not focus on 1st element. 
The main issue here is that if the latest message in chat is quite long, then the `inverse: true` setting does not work as it's intended, instead we have this small scroll offset

**Comment by DaveLomber** [comment]
Ok, one interesting observation re Issue N1 - if `startIndex ` is within `bufferSize` then it's ok, if it's higher then we can see this minus one effect

**Comment by dhilt** [comment]
@DaveLomber Regarding 1 issue, I would not rely on `settings.maxIndex` in case of inverted datasource. Playing with indexes on the datasource level we deceive the scroller as it doesn't know anything about the data it is going to fetch via `datasource.get`. My purpose for the issue 1 is to move a restriction logic into the datasource implementation. 

Here is the working demo: https://stackblitz.com/edit/angular-ngx-ui-scroll-1-4-1-inverted-datasource

**Comment by DaveLomber** [comment]
@dhilt checked your example.
When I set `startIndex: -2` then it focuses on `1 item`, not `2 item`. So not it's minus one for all. Is it expected ?

**Comment by DaveLomber** [comment]
@dhilt  thanks
this is interesting, let me try 

anything extra you need for #2 - please let me know

**Comment by dhilt** [comment]
@DaveLomber You know, the `inverse` setting is pretty dumb. Per [inverse demo](https://dhilt.github.io/ngx-ui-scroll/#/experimental#inverse-setting) description:

> When inverse setting is set to true, the backward padding element will have a priority over the forward one, and it will be stretched if there are not enough items in the viewport.

In your case it just does not have an impact on the result due to the fact that the item is big enough and there is no need to stretch paddings. In other words, if  the visible part of the viewport is filled, the `inverse` setting will not affect the view.

Instead I would use a combination of `reverse` setting (when cumulative height of initial items is less than the height of the viewport) and autoscroll feature (when the item you want to be shown first is bigger that the viewport). For the second part I suggest following approach:

```js
const { isLoading$, firstVisible$ } = this.datasource.adapter;
zip(isLoading$, firstVisible$)
.pipe(
  filter(([isLoading]) => !isLoading),
  take(1)
)
.subscribe(
  (([isLoading, item]) => {
    const viewportElement = document.querySelector('.viewport');
    const diff = item.element.clientHeight - viewportElement.clientHeight;
    // adjust scroll position only if the start item is bigger than the viewport
    if (diff > 0) {
      console.log('aligned by', diff)
      viewportElement.scrollTop += diff;
    }
  })
);
```

The demo is here -- https://stackblitz.com/edit/angular-ngx-ui-scroll-1-4-1-scroll-to-bottom-of-item. Try to switch `COUNT` to 1...

**Comment by DaveLomber** [comment]
@dhilt Thanks, rx js indeed a great thing for all such things! :)

**Comment by DaveLomber** [comment]
@dhilt I might need to request your feedback on one more magic thing we face 

Please use my latest demo 
https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0-tbjtc1?file=src%2Fapp%2Fapp.component.ts

and set

- buffer size to `bufferSize: 20`
- messages length to 7 (less than buffersize) - `for (let i = 0; i < 7; ++i) {`

Result: ` inverse: true` does not really works as expected - there is a blank space one the bottom 

<img width="957" alt="Screen Shot 2020-02-24 at 6 51 06 PM" src="https://user-images.githubusercontent.com/39332586/75172926-bb460480-5736-11ea-8597-e633bdc0fe34.png">

**Comment by DaveLomber** [comment]
Actually seems it tries to stick to the  bottom, but then a jump occurs

**Comment by dhilt** [comment]
@DaveLomber Actually, I don't see the problem running [your last demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0-tbjtc1):

<img width="873" alt="Screenshot 2020-02-25 at 02 44 54" src="https://user-images.githubusercontent.com/4365660/75201180-d5a0d200-5778-11ea-8d49-660fd9231a5e.png">

Maybe wrong link? or what browser is it?

**Comment by DaveLomber** [comment]
@dhilt I have updated it
just need to replace

```
    const index = -_index - count + this.MIN;
    const start =  Math.max(this.MIN, index);
    const end = start + count - 1;
    // const start = -_index - count + this.MIN;
    // const end = start + count - 1;
```

**Comment by dhilt** [comment]
@DaveLomber The math seems bad. In your last piece the datasource returns 2 arrays in sequence: [0..6] and then [1..6]. This is initially, before scrolling, and this is not consistent as the arrays intersect. The previous try (which seemed worked) also was imperfect, it gave [0] and [1..6]. Though, as you can see, it was consistent. But I believe the best result would be to have [0..6] and [] on start. And the approach [I suggested above](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-4-1-scroll-to-bottom-of-item) can do this:

```js
  private MIN = 0;
  private START = 0;
  private COUNT = 7;
...
    settings: {
      startIndex: this.MIN - this.START - 1,   
      bufferSize: 20,
      inverse: true
    },
...  
    const start = -_index - count + this.MIN;
    const end = start + count - 1;
```

**Comment by DaveLomber** [comment]
@dhilt could you please check this demo https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0-rnsvxm?file=src/app/app.component.ts

with your math provided it's better, but I still randomly can face the issue in my app, 
and now I reproduced it in a demo 

One element should be bigger than the rest  - and then the issue occurs

**Comment by dhilt** [comment]
@DaveLomber  Now, that's more like it

<img width="515" alt="Screenshot 2020-02-27 at 05 41 36" src="https://user-images.githubusercontent.com/4365660/75407367-db86e680-5923-11ea-802c-0a4d23870257.png">

I see the issue and will work on this. Something is wrong when adjusting with "reverse"...

**Comment by DaveLomber** [comment]
@dhilt please let me know when you can do this
Thanks

**Comment by dhilt** [comment]
@DaveLomber ngx-ui-scroll v1.4.4 is released. I don't think the "inverse" case is done, but this particular issue should be fixed. Could you please check it and open new issue if any questions?

**Comment by DaveLomber** [comment]
@dhilt  thanks so much 
let me try  it and get back to you in a case of any issues
