### ISSUE TITLE
Scrolling event triggers by itself when using nz-spin

### ISSUE THREAD

**Issue by DarthVeyda** [dhilt/ngx-ui-scroll#149]
We are using ngx-ui-scroll with a (potentially) long list of expandable elements, and we've encountered a strange problem. When I add an <nz-spin> to indicate that the list is loading/finished loading, on opening the page the list start to expand as if we were scrolling the page - the list keeps expanding in bufferSize-sized portions until the whole array is loaded. That's probably not how it's supposed to work, and it absolutely murders the page if the list is long enough. 

(this.items$ is loaded from ngRx store)
``` 
datasource: IDatasource = ({
    get: (index, count) =>
      this.items$.pipe(
        map(items => {
          return index + count <= items.length
            ? items.slice(index, index + count)
            : items.slice(index, activities.length - index);
        })
      ),
    settings: {
      bufferSize: 10,
      startIndex: 0,
      minIndex: 0,
    },
    devSettings: {
      debug: true,
    }
  });
```

(loading$ is another store variable that indicates whether we have finished retrieving items$)
``` 
<nz-spin [nzSpinning]="loading$ | async">
    <div class="viewport">
      <div *uiScroll="let activity of datasource" class="list-body">
        <div class="item">
          <app-activity-detail-container class="list-item" [activity]="activity"></app-activity-detail-container>
        </div>
      </div>
    </div>
  </nz-spin>
```

If I try to place <nz-spin> inside the viewport element instead, I'm getting an "HTML element is not defined" error:
![image](https://user-images.githubusercontent.com/13716483/75503970-3e16da00-5a2b-11ea-8c25-725953b11148.png)

Is there any correct way to do what I'm trying to do? Is ngx-ui-scroll compatible with ng-zorro at all?

Thank you in advance!

**Comment by dhilt** [comment]
@DarthVeyda May I ask you to look at [angular-ngx-ui-scroll-1-4-2-ng-zorro demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-4-2-ng-zorro) I just drafted for this issue? It would be great if you could update it to provide the repro of the issue. Basically "HTML element is not defined" message is talking about DOM related problems and I guess it has something to do with that self-expanding process you described above. We need to reproduce it.

**Comment by DarthVeyda** [comment]
@dhilt Thanks for your reply! I need some time to try and reproduce the layout that has unprompted scrolling, (the "HTML element is not defined" is here, just in case: https://stackblitz.com/edit/angular-ngx-ui-scroll-1-4-2-ng-zorro-ujuy18).
