### ISSUE TITLE
trackBy support for *uiScroll

### ISSUE THREAD

**Issue by DarthVeyda** [dhilt/ngx-ui-scroll#150]
ngx-ui-scroll doesn't seem to support trackBy - it doesn't recognise either *ngFor syntax `trackBy: trackByFn` or ng-repeat syntax `track by`. Is there any way to make it work? If not, do you have any plans to add it?

Thank you in advance!

**Comment by dhilt** [comment]
@DarthVeyda You know, the uiScroll is kind a mock of ngFor... Its Datasource is not iterable, and `Datasource.get` is not iterable too. This is the Scroller responsibility to request the only items that needed for render, while the App responsibility is to provide the items by index-count params via `Datasource.get` API method. So you may treat `index` as a kind of `trackBy`, as it might be linked with any data you want to be trackable in terms of App -> Scroller dataflow. For example, in the "[Append / prepend sync](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend-sync)" you may see how `index` is linked with `item.id`.

I think, this might relate to your first issue, and let me continue there... but speaking of `trackBy`, I guess, the answer is no, the ngFor fashion is not going to be supported.

Anyway, thank you for your question, perhaps it's a good idea to add some words in the doc!
