### ISSUE TITLE
How to scroll to a specific item?

### ISSUE THREAD

**Issue by aramwram** [dhilt/ngx-ui-scroll#158]
Hello.

Thanks for the fantastic package.

Is it possible to programmatically scroll to a specific item identified by index, i.e. something like `adapter.scrollTo(10)`?

I was able to utilize `adapter.reload(10)` but then all indexes less than 10 disappear (which is expected I guess).

Another working option is to set `startIndex: 10` but it works only for the first time. If I could change and apply Datasource settings at runtime it would be useful for programmatic scrolling.

Can you please suggest a way of programmatic scrolling using ngx-ui-scroll?

**Comment by dhilt** [comment]
@aramwram Glad to hear the lib is useful! Right now we have no such functionality (though [there are some plans](https://github.com/dhilt/ngx-ui-scroll/issues/156) on the implementation in the near future), but you may try to achieve it via `Adapter.fix({ updater })` API which is experimental but is available since ngx-ui-scroll v1.3.1. Here is [the demo and explanations](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater) of this API, but in few lines it could be done as following:

```js
this.datasource.adapter.fix({
  updater: ({ $index, element }) => {
    if ($index === 10) {
      element.scrollIntoView();
    }
  }
});
```

or using `scrollTop`:

```js
// find element to scroll
let myElement;
this.datasource.adapter.fix({
  updater: ({ $index, element }) => {
    if ($index === 10) {
      myElement = element;
    }
  }
});
// perform scroll on the viewport element
const viewportElement = document.getElementById('my-viewport');
if (myElement && viewportElement) {
  const elementTop = myElement.getBoundingClientRect().top;
  const viewportTop = viewportElement.getBoundingClientRect().top;
  const diff = viewportTop - elementTop;
  const scrollPosition = viewportElement.scrollTop - diff;
  adapter.fix({ scrollPosition }); // OR viewportElement.scrollTop = scrollPosition;
}
```

Does it help?

**Comment by aramwram** [comment]
@dhilt,

For me the proposed solution works only for elements within the viewport while I need to get to any elements, even those which are not yet in DOM.

Recently, I've found a hacky way of programmatically scrolling anywhere:
1. Wrap uiScroll in *ngIf:
```
<div class="scroll-viewport" *ngIf="enabled">
    <div *uiScroll="let rec of datasource">
```
2. In component make `*ngIf="false"`, then re-create DataSouce with `startIndex: indexToScrollto`, wait for stable zone and then make `*ngIf="true"`. Hrere's an example code:
```
class MyComponent {
    datasource: Datasource = this.getScrollDataSouce(0);

    /**
     * Used for temporary removing uiScroll from DOM and then creating it again.
     */
    enabled: boolean = true;

    scrollTo(idx: number): void {
        this.refreshScrollDataSouce(idx);
    }

    private refreshScrollDataSouce(scrollTo: number = 0): void {
        this.enabled = false;
        this.cdRef.markForCheck();

        this.datasource = this.getScrollDataSouce(scrollTo);

        this.ngZone.onStable.pipe(take(1)).subscribe(() => {
            this.enabled = true;
            this.cdRef.markForCheck();
        });
    }

    private getScrollDataSouce(scrollTo: number): Datasource {
        return new Datasource({
            get: (index, count, success) => {
                success(this.levelTextLogData.slice(index, index + count));
            },
            settings: {
                infinite: true,
                minIndex: 0,
                startIndex: scrollTo
            }
        });
    }
}
```

It works well, so for now I'm going to use this solution. Hope it will be useful for others until we have a direct API for this.

Best regards.

**Comment by dhilt** [comment]
@aramwram You are right, my suggestion only works for items that are currently exist in the buffer. The second point is that I'm sure there should be no difference between initialization with `startIndex = 10` and reloading via `Adapter.reload(10)`. I created [demo on stackblitz](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-5-0-reload-and-reinit?file=src/app/app.component.ts), with the help of logs you may see it. 

After first init (startIndex = 1):

> pos: 108, size: 414, bwd_p: 0, fwd_p: 0, aver: 18, items: 23, range: [-5..17]

After reload via Adapter.reload(100):

> pos: 108, size: 414, bwd_p: 0, fwd_p: 0, aver: 18, items: 23, range: [94..116]

After reload via rebuilding the DOM and the Datasource with startIndex=100:

> pos: 108, size: 414, bwd_p: 0, fwd_p: 0, aver: 18, items: 23, range: [94..116]

I'm sure your use case should be covered by `Adapter.reload(index)` API. You may try to fork the demo and reproduce necessary infrastructure for I can take a look...

The last thing, re-initialization of the Datasource in the runtime is a part of the future releases plan, here is the issue: [Replace Datasource on the fly](https://github.com/dhilt/ngx-ui-scroll/issues/139).

**Comment by aramwram** [comment]
@dhilt ,

After some redesign I tried adapter.reload(10) again and it magically started to work as "scrollTo(10)". Now I cannot reproduce the issue where all items with indexes < 10 were dissipating.

I'm closing this issue then as long as I don't have a clear state of reproduction. Thank you very much for your help and for the lib itself.
