### ISSUE TITLE
Development Questions

### ISSUE THREAD

**Issue by lmreicks** [dhilt/ngx-ui-scroll#159]
I'm working on improving some of the documentation and improving how ui-scroll works with asynchronous data. I have a few questions about the implementation and I'm not sure where else to ask these.

1. Can I get a brief overview of what the Buffer class does? Specifically, can you explain the concept of a 'pack'? 
2. How/when should clip be used? What does 'doClip' mean?
3. (This one isn't very much of a question) In prefetch, we use the buffer to get items and figure items to show, and then in fetch we get the items. This seems to be backwards, unless I miss understand the buffer. I think this could be why asynchronous data doesn't work properly.
4. Can you explain what these properties are used for:
```typescript
export interface WorkflowOptions {
  empty: boolean;
  scroll: boolean;
  keepScroll: boolean;
  byTimer: boolean;

  reset: Function;
}
```

**Comment by dhilt** [comment]
@lmreicks Answering on last question, I want to show you the uiScroll Workflow diagram. It also will be useful for other questions. But let's consider the 4 one.

Current version of the uiScroll Workflow is 6.5, I have the diagram only for version 5.0. It is outdated, but it can shed light on the basic concept:

![workflow-5](https://user-images.githubusercontent.com/4365660/76582305-efffdd00-64e6-11ea-8381-54a8be9271fa.png)

This is a kind of state machine, latest releases have it in the separate file [src/component/workflow-transducer.ts](https://github.com/dhilt/ngx-ui-scroll/blob/v1.5.0/src/component/workflow-transducer.ts).

In WF 5+ version I was trying to implement scrolling as the [WF Process](https://github.com/dhilt/ngx-ui-scroll/blob/v1.5.0/src/component/processes/scroll.ts) (WF 5 and below had scrolling as completely separate entry point). The logic of the Scroll process is really not perfect, and `WorkflowOptions` helps to integrate Scroll process into WF. Specifically it helps to make End-Init loop via `WorkflowOptions.keepScroll`. 

I hope the details will be more clear when you will investigate `WorkflowOptions` props keeping in mind the WF state machine, connection it with the Scroll process and the idea of the `WorkflowOptions` object as a data container helping the Scroll process to be a part of the WF.

I will look at other questions tomorrow. Thanks for your interest!

**Comment by dhilt** [comment]
@lmreicks 

**1)** Buffer keeps the main thing across all the module: `$items`. This is the only data that propagates from the Workflow to the UiScrollComponent. All `Buffer` methods are dedicated to maintain `$items` and related data such as EOF/BOF.

Not sure, what's the `pack` you mentioned? Does this relate to `PreFetch.skipBufferedItems` method? That method is dedicated to flushing indexes that are currently exist in the `Buffer`. This flushing may split index list into 2 parts (packs). The biggest pack will be requested by the Fetch process. 

**2)** Clip process runs after Render as you can see from the WF 5.0 diagram. But looking at [StateMachine](https://github.com/dhilt/ngx-ui-scroll/blob/v1.5.0/src/component/workflow-transducer.ts) you may get the actual image: Clip runs after **`PreClip`** process (which runs after `Render` and after `PreFetch` in case it was run by the `UserClip` process) and after **`Start`** process (which runs after `Remove` forced by Adapter.remove). 

`doClip` is a flag setting by `PreClip` and `Remove` I just mentioned. These two processes decide whether to start the `Clip` process after or not. And this decision is recorded in `doClip`.

**3)** PreFetch makes a list of **indexes** to be requested in Fetch. Buffer knows what indexes are exist currently and what indexes are available (borders). Items requested by Fetch are sent to Buffer. 

**4)** WorkflowOptions is an object helping the `Scroll` process to be integrated in the Workflow: Scroll -> Init/Start -> PreFetch -> ... -> End -> Scroll -> Init/Start -> ...
