### ISSUE TITLE
CPU load 100% when viewport has 'display: none' style 

### ISSUE THREAD

**Issue by DaveLomber** [dhilt/ngx-ui-scroll#163]
There were couple cases where our app got freezes 

We started to investigate and found that if a viewport has a  'display: none' style then it produces a freeze with 100% CPU load

can be reproduced here (press on Enable button) https://stackblitz.com/edit/angular-ngx-ui-scroll-1-5-0-enable-on-demand-pxejsu?file=src%2Fapp%2Fapp.component.css

I know it's not correct logically to use a `display: none` style here, 
but 
in complex apps there are lots of logic to update UI and suddenly a developer can run in a same issue 
Would be great to have a better logic to cope with such situation, 
for example, to throw an exception or error, something like this

**Comment by dhilt** [comment]
@DaveLomber I was able to reproduce the issue. Scroller passes null-size items and this hangs following PreFetch process run. I need to think how to fix it, I see two options: do not fetch if the viewport can't have positive size OR break the Render process if fetched items have zero size. First option seems simpler but the second one is wider and can be applied not only to the case of invisible viewport ... Anyway, I put "Bug" label and will fix it shortly. Thanks you!

**Comment by dhilt** [comment]
v1.5.2 is published and ready for use

**Comment by DaveLomber** [comment]
@dhilt  Thanks! 
We will integrate
