### ISSUE TITLE
Rendering problem while updating from v1.5.1 to v1.5.2

### ISSUE THREAD

**Issue by StriderRanger** [dhilt/ngx-ui-scroll#167]
Hello!

While updating from v1.5.1 to v1.5.2 I faced a problem with the display of a list with an inverted datasource.

The problem was mainly noticed in the values of the `forward padding` and `backward padding`, where these values were correctly updated in `v1.5.1` but stayed at their initial values in `v1.5.2`.
I hope these logs give more insight of the problem:
- [Padding-issue-v1-5-2.log](https://github.com/dhilt/ngx-ui-scroll/files/4430074/Padding-issue-v1-5-2.log)
- [Padding-issue-v1-5-1.log](https://github.com/dhilt/ngx-ui-scroll/files/4430075/Padding-issue-v1-5-1.log)

As you may notice in these logs, in v1.5.1 the Adjust process was run after the Render process. In v1.5.2 instead of adjusting the size in the Render process, it has been looged: `viewport size has not been changed`

Please let me know if you need additional information.

Thanks :)

**Comment by dhilt** [comment]
@StriderRanger Thanks for logs! v1.5.2 log seems not realistic:

```
stat before new items render, pos: 0, size: 442, bwd_p: 0, fwd_p: 442, aver: no, items: 0, range: no
average size has been updated: 65
stat after new items render, pos: 0, size: 961.2000122070312, bwd_p: 0, fwd_p: 442, aver: 65, items: 8, range: [1..8]
viewport size has not been changed
```

Let me think a bit right here... "size" had obviously been changed from 442 to  961 during render. Looking at the code we may see that "before render" log

https://github.com/dhilt/ngx-ui-scroll/blob/441d5767cd455e924dc23fda5a9c94e8202d4f39/src/component/processes/render.ts#L9

and "before-size" measurement

https://github.com/dhilt/ngx-ui-scroll/blob/441d5767cd455e924dc23fda5a9c94e8202d4f39/src/component/processes/render.ts#L35

are split by 1 event loop

https://github.com/dhilt/ngx-ui-scroll/blob/441d5767cd455e924dc23fda5a9c94e8202d4f39/src/component/processes/render.ts#L11

which is responsible for rendering new items that forced to be invisible

https://github.com/dhilt/ngx-ui-scroll/blob/441d5767cd455e924dc23fda5a9c94e8202d4f39/src/ui-scroll.component.ts#L21-L22

After new items are rendered (but invisible), the viewport size is being measured as `sizeBefore`. Then invisibility is being removed synchronously, then the viewport "after-size" measurement happens, and then "after render" log takes place.

Is it possible that something goes unexpected during asynchronous `scroller.bindData()` call? Maybe your template has css-positioning with `!important`? This tiny asynchronicity is the only thing I'm inclined to suspect... could we debug it in your environment? just set up breakpoint before the line 

https://github.com/dhilt/ngx-ui-scroll/blob/441d5767cd455e924dc23fda5a9c94e8202d4f39/src/component/processes/render.ts#L35

and invoke additional logging:

```
scroller.logger.stat('after new items render (invisible)');
```

**Comment by StriderRanger** [comment]
Thank you for your explanation!
You went straight to the point by suspecting the `!important` property. In the css relative to the viewport of the list presenting the problem I had:
```
.viewport {
  //...
  ::ng-deep div[data-sid] {
    position: unset !important;
    left: unset !important;
  }
}
```
I don't remember why I forced the values of these properties to `unset` but by deleting this code my problem was solved. Maybe there was some change from v1.5.1 to v1.5.2 that showed the vulnerability of this code.

I also added the log that you requested and it clearly calls the Adjust process:
```
run Render
ngx-ui-scroll.js:1159 stat before new items render, pos: 0, size: 442, bwd_p: 0, fwd_p: 442, aver: no, items: 0, range: no
ngx-ui-scroll.js:1159 stat after new items render (invisible), pos: 0, size: 442, bwd_p: 0, fwd_p: 442, aver: no, items: 0, range: no
ngx-ui-scroll.js:1159 average size has been updated: 69
ngx-ui-scroll.js:1159 stat after new items render, pos: 0, size: 995.2000122070312, bwd_p: 0, fwd_p: 442, aver: 69, items: 8, range: [1..8]
ngx-ui-scroll.js:1159 fire render "next" {noClip: false}
ngx-ui-scroll.js:1159 run PreClip
ngx-ui-scroll.js:1159 skipping clip [initial cycle, no scroll]
ngx-ui-scroll.js:1159 fire preClip "next" {doClip: false}
ngx-ui-scroll.js:1159 run Adjust
ngx-ui-scroll.js:1159 stat after paddings adjustments, pos: 0, size: 24565.201171875, bwd_p: 24012, fwd_p: 0, aver: 69, items: 8, range: [1..8]
ngx-ui-scroll.js:1159 setting scroll position at 24012
ngx-ui-scroll.js:1159 stat after scroll position adjustment (average), pos: 24012, size: 24565.201171875, bwd_p: 24012, fwd_p: 0, aver: 69, items: 8, range: [1..8]
ngx-ui-scroll.js:1159 fire adjust "done"
ngx-ui-scroll.js:1159 run End adjust
```
I really appreciate your help and your support :)

**Comment by dhilt** [comment]
@StriderRanger  Well, I think we've found the cause. New log doesn't confirm it, maybe logger call is not in the right place, but it doesn't matter. Can you allow the rows positioning to be controlled by the Scroller? This should fix the problem for now.

Also, I'm thinking of how to improve rendering. The point is that I need to make all scroll adjustments in the same repaint frame as the end of the render.  Otherwise, the user will see the adjustment process with his own eyes (ok, he may see and may not, depends on the environment and common probability). And to avoid possible blinking I have to hide new rows during render. This might be improved, I'm not sure how. But current workflow assumes new rows to be hidden right after the render is done, which is achieved by hiding the rows on the template layer before render.

**Comment by StriderRanger** [comment]
For now the behavior of the scroller seems good, but enhancements are always welcome :) Already the `ui-scroll` is giving much flexibility and options that are really useful, thank you for the great work !
I run some tests and the behavior of the scrolling was normal, which means that I can let the Scroller manage the rows positioning. I'll let you know if ever I run into any problem related to this positioning properties, but all seems fine for now.

**Comment by dhilt** [comment]
Great! We'll reopen this issue or create another one if needed.
