### ISSUE TITLE
Scroll event not trigger while having multiple items per row

### ISSUE THREAD

**Issue by amirhosein993** [dhilt/ngx-ui-scroll#170]
Thanks to your great module. 
I am using 3 items per row and getting data from server. the problem is that the data source get method not called when scroll ends. what should I do?
thanks for your help. 
here is the code I'm using in my component.html:
`
            <div class="row" *uiScroll="let data of datasource">
                <div class="col-xs-12 col-md-4 mb-4" *ngFor="let item of data">
                </div>
            </div>
`

**Comment by dhilt** [comment]
@amirhosein993 Any chance to have a repro? Basically your case is pretty common and we have one demo on stackblitz with the same template as yours:

https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-4-grouping-datasource

Note, that `this.data` is the real data provider in this sample, and applying the approach to your case (where your data provider is remote), you need to make all get-data methods asynchronous. If you fork the stackblitz demo and create a repro based on it, I can help you at the level of the App code.

**Comment by amirhosein993** [comment]
> @amirhosein993 Any chance to have a repro? Basically your case is pretty common and we have one demo on stackblitz with the same template as yours:
> 
> https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-4-grouping-datasource
> 
> Note, that `this.data` is the real data provider in this sample, and applying the approach to your case (where your data provider is remote), you need to make all get-data methods asynchronous. If you fork the stackblitz demo and create a repro based on it, I can help you at the level of the App code.

tha

**Comment by amirhosein993** [comment]
> @amirhosein993 Any chance to have a repro? Basically your case is pretty common and we have one demo on stackblitz with the same template as yours:
> 
> https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-4-grouping-datasource
> 
> Note, that `this.data` is the real data provider in this sample, and applying the approach to your case (where your data provider is remote), you need to make all get-data methods asynchronous. If you fork the stackblitz demo and create a repro based on it, I can help you at the level of the App

**Comment by amirhosein993** [comment]
> @amirhosein993 Any chance to have a repro? Basically your case is pretty common and we have one demo on stackblitz with the same template as yours:
> 
> https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-4-grouping-datasource
> 
> Note, that `this.data` is the real data provider in this sample, and applying the approach to your case (where your data provider is remote), you need to make all get-data methods asynchronous. If you fork the stackblitz demo and create a repro based on it, I can help you at the level of the App code.

thanks for your help. have you an example code with http client module and observables?

**Comment by dhilt** [comment]
@amirhosein993 Yes, we have one on stackblitz:

[ngx-ui-scroll v1.6.2 Remote Observable demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-6-2-remote-observable)

Basically, you just need to invoke your API GET method with `index` / `count` signature which would return an Observable of list of items (`Observable<MyItem[]>`). You also don't need to subscribe:

```js
  datasource = new Datasource({
    get: (index, count) => this.remoteService.requestData(index, count)
  });
```

So you need to replace `remoteService.requestData` method call with `httpClient.get` method call with appropriate params. In my demo the remote call is emulated via `delay` rxjs operator:

```js
  requestData(index, count): Observable<Item[]> {
    const data = [];
    for (let i = index; i < index + count; i++) {
      data.push({ id: i, text: 'item #' + i });
    }
    return of(data).pipe(delay(DELAY_MS));
  }
```

__________________

Also, there is an official "Remote datasource" demo:

https://dhilt.github.io/ngx-ui-scroll/#/datasource#remote

The code does work, but you won't see the result until you run the demo App locally (Http Client sends its request to NodeJS server which is not running in github.io environment).

**Comment by amirhosein993** [comment]
thanks for your help :)
