### ISSUE TITLE
Get the first/last loaded element in the DOM

### ISSUE THREAD

**Issue by StriderRanger** [dhilt/ngx-ui-scroll#174]
The scalars Adapter.firstVisible and Adapter.lastVisible besides their observables version allow to determine the first and the last visible items that are visible in the page.

In some cases, it is also handy to retrieve the first/last visible elements that are loaded (and not necessarily visible) in the DOM. Is there a simple way to have this information or would it be necessary that a new implementation be added to the api?

Thanks!

**Comment by dhilt** [comment]
Do you mean first/last buffered items that are in DOM at a moment with no connection to the visible viewport? Say, 4 and 12 rows on the diagram

![virtual-scrolling-settings-object-value](https://user-images.githubusercontent.com/4365660/81573063-acbdcf80-93ac-11ea-84f6-0a79565c936b.png)

where the visible group is only from 6 to 10.

Basically this can be done with `Adapter.fix({ updater })` approach: 

```js
let first, last;
this.datasource.adapter.fix({
  updater: ({ data }) => {
    if (!first) {
      first = data;
    }
    last = data;
  }
});
```

Updater is a function that is applied (synchronously) to each element in current ui-scroll buffer list. This method is not documented, but there is a [demo on github.io](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater) describing it. Is it what you are asking for? I would agree, it is not super simple, but it should work until we have developed a better approach.

**Comment by StriderRanger** [comment]
Even if there is no straightforward properties to use, this is a clean approach and it suits my needs, thank you!
