### ISSUE TITLE
Tests, basic specs

### ISSUE THREAD

**Issue by dhilt** [dhilt/ngx-ui-scroll#18]
**initialization spec**
- [x] initializing (host component, datasource, viewport, buffer elements)
- [x] bad datasource
- [x] settings default (datasource with and without settings; settings overriding)
- [x] bad settings
________
**initial load spec**
- [x] initial load with no clip (3 cases)
- [x] initial load with clip (3-5 cases)
- [x] infinite mode (based on previous clip-tests but only 1 case)
________
**scrolling spec**
- [x] single one-direction scroll event (3 cases of 1 scroll event per each direction)
- [x] mass one-direction scroll events (3 cases of 3-5 scroll events per each direction)
- [x] mass bouncing scroll events (3 cases of 3-5 sequences of (fwd + bwd) events)
- [x] mass two-direction scroll events (2) (3 cases of  (3-5 fwd + 3-5 bwd) events)

**Comment by dhilt** [comment]
Here 'case' is a combination of bufferSize, padding and viewportHeight params. Later we'll add itemHeight and startIndex. For now `initial.spec.ts` has an infrastructure to manipulate `case` params inside a single spec. All expectations should be calculated dynamically based on `case` params as it is done for `initial.spec.ts`. The branch for committing: https://github.com/dhilt/ngx-ui-scroll/tree/tests.

**Comment by dhilt** [comment]
I've just pushed tests for datasource settings default/overriding. Thinking about convenient tests configure runner.

**Comment by dhilt** [comment]
@supromikali @khajjit A new configurable test runner is implemented. Now it should be pretty easy to create mass cases specifications, please look at `initial-load.spec.ts`. The only new thing that should be taken into the account is asynchronous `done` callback – it must be invoked explicitly at the logical end of custom runner-it implementation.

Also, `done` could be useful in scroll events tests: `misc.workflow.resolver.subscribe` would allow to listen to the workflow cycle's ending, and `done` could be invoked inside this listener to complete the test.

**Comment by supromikali** [comment]
@dhilt I have just added "infinite" scroll case to initial load spec. See https://github.com/dhilt/ngx-ui-scroll/commit/a1e6db0ae3d80d851c99a436ad62170ee3360687

**Comment by dhilt** [comment]
@khajjit @supromikali I struggled with async events triggering for last 2-3 days and I developed an approach that is convenient enough (maybe we will change it in the future). It is based on jasmine `spyOn` mechanism. I added two stub `finalize` methods on the WorkflowRunner and Workflow classes which do nothing but which are being invoked when a) the workflow is completed and stopped (WFRunner.finalize); b) one cycle of the workflow is done (WF.finalize). Investigate **scroll-basic.spec**!

**Comment by dhilt** [comment]
@supromikali I saw your work on bad datasource and made some updates in tests runner. You can continue from this point and cover other "bad" scenarios.

**Comment by olga-solovyeva** [comment]
@dhilt I have added "missing datasource" case to Bad datasource spec. Could you check my commit 233ae383fdb2bd09cea92cf1f33bdc5b7ffe7f8d please?

**Comment by supromikali** [comment]
@dhilt I have added "missing datasource" case to Bad datasource spec, could you check my commit, please? 233ae383fdb2bd09cea92cf1f33bdc5b7ffe7f8d

**Comment by dhilt** [comment]
We did it!
