### ISSUE TITLE
Errors with angular 8

### ISSUE THREAD

**Issue by floAtEbcont** [dhilt/ngx-ui-scroll#181]
Running/Building a default angular <= 8 project with ngx-ui-scroll >= 1.6.4 fails with the error `An accessor cannot be declared in an ambient context`.

The cause for this is being discussed here: https://github.com/microsoft/TypeScript/issues/33939

For my own libs, I fixed this by just downgrading to `typescript@3.6.x` before bundling the lib and pushing it to npm.
Or - if you decide to no longer support angular < 9 - you could update your lib's peer dependencies accordingly.

**Comment by dhilt** [comment]
Terrible story... Thanks a lot for the report and suggestions. I published ngx-ui-scroll v1.6.6 on npm with downgraded typescript. Could you confirm it works in your environment?

**Comment by floAtEbcont** [comment]
Yes! Version 1.6.6. works fine in angular 8. :partying_face:  Thank you!!
