### ISSUE TITLE
First and the last visible items objects not emitting data

### ISSUE THREAD

**Issue by Ar-Kan** [dhilt/ngx-ui-scroll#182]
Hello,

Once again I seek guidance, after update 1.5.1 it seems to me that `firstVisible$` and `lastVisible$` from `adapter` isn't emitting values.

Am I missing something or not implementing correctly?

StackBlitz:
* [1.5.0](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-5-0-enable-on-demand-4ey3ca)
* [1.5.1](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-5-1-enable-on-demand-msfnab)

**Comment by dhilt** [comment]
@Ar-Kan Looks like we have lost some of flexibility with 1.5.1... an additional asynchronicity interferes with Adapter early subscriptions. I will fix it, but it will take some time. As a workaround you may postpone early subscriptions by moving them from `constructor` to `ngAfterViewInit`. Zero-timeout also works, but `afterViewInit` hook is better. Thanks for the report!

**Comment by Ar-Kan** [comment]
Thank you for your response, I was able to implement on `afterViewInit`.

Thanks once again!

**Comment by dhilt** [comment]
@Ar-Kan ngx-ui-scroll v1.7.0 was released yesterday and, as I can see, it fixes constructor-subscriptions problem. I'm going to add few tests, but it would be great if you could check 1.7.0 and we may close the issue.

**Comment by Ar-Kan** [comment]
@dhilt I've updated here, and it's working beautifully, thank you for your awesome work

Thanks!
