### ISSUE TITLE
chat app scroll up

### ISSUE THREAD

**Issue by amirhosein993** [dhilt/ngx-ui-scroll#185]
In one of my projects I implement scroll up myself for a chat UI. when I add new items to the beginning of the messages array, the scroll not remains in the correct position and it moves to the first (scrollHeight = 0). 
How can I fix this?

**Comment by dhilt** [comment]
@amirhosein993 Thanks for the issue! Basically you need two things: a) wait for the scroller is relaxed, b) trigger scroll event.

```ts
await this.datasource.adapter.relax();
const viewport = document.getLementById('myViewport');
viewport.scrollTop = 0; // scroll top
viewport.scrollTop = viewport.scrollHeight; // scroll bottom
```

There is also [adapter-fix-position](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-position) experimental feature allowing to scroll without looking for DOM element:

```ts
await this.datasource.adapter.relax();
this.datasource.adapter.fix({ scrollPosition: 0 }); // scroll top
this.datasource.adapter.fix({ scrollPosition: Infinity }); // scroll bottom
```

Also, you might be interested in our [Chat App wiki](https://github.com/dhilt/ngx-ui-scroll/wiki/Chat-App). The work is just started, so the doc may change, but the approach has working implementation and demo, which may be helpful.
