### ISSUE TITLE
events when DOM is updated

### ISSUE THREAD

**Issue by rraz-np** [dhilt/ngx-ui-scroll#186]
Can  we get any event callback when DOM is updated. Basically, I am trying to track which list item was last selected by user. When user scrolls down or up, that item may no longer exist in DOM, but I want to track where user was last time.

Also, the demos show how to get first and last item on view. But, can we also get which are the first and last item in the DOM?

I tried to get the data-sid value with following after dataadapter.loading becomes false, but it has more items and then later the items are removed, I guess.
var listElements = document.querySelectorAll('[data-sid]')

**Comment by dhilt** [comment]
**On DOM changes.** 

If you want to catch the moment when new rows are rendered, you may run `isLoading$` subscription inside `Datasource.get` method body. `Datasource.get` is invoked automatically by the Scroller when it needs new data to render new rows. So at this point (if the result of `get` is not empty), we may state that DOM will change.

```js
let cb = () => {
  cb = () => null; // if we want cb logic to be run only once
  // ... cb logic
}

datasource = new Datasource({
  get: (index, count) => {
    // ... getting the result
    if (/* the result is not empty */) {
      datasource.adapter.relax(cb); // smart isLoading, since v1.7.0
    }
    return /* result */;
  }
})
```

What about clipping old rows? Basically clipping process can be triggered only as a part of so called inner loop, which must include at least 1 `Datasource.get` call. See [wiki](https://github.com/dhilt/ngx-ui-scroll/wiki/The-UIScroll-Workflow). So this approach should cover both adding and removing scenarios.

But I also think, that the case might be simpler and running the `isLoading$` subscription may be not linked with `Datasource.get` invocation. It depends on the issue...

```js
ds1 = new Datasource(...)
ds2 = new Datasource(...)

merge(
 ds1.adapter.isLoading$.pipe(filter(v => !v), map(() => 'ds1')),
 ds2.adapter.isLoading$.pipe(filter(v => !v), map(() => 'ds2'))
).subscribe(v => 
  console.log(`${v} is relaxed last`)
);
``` 

**On DOM changes (2).** 

You may try not to rely on the lib API. Just put scroll-event handlers on your viewports and track which viewport was active last time. If you need to track not only scroll events, you may try 
[MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) approach instead.

**On first/last rendered items.** 

Currently we have no good API for this and "data-sid" is not your friend, but there is  [fix-updater](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater) experimental feature which can help. Recently there was a similar request ([Get the first/last loaded element in the DOM](https://github.com/dhilt/ngx-ui-scroll/issues/174)) and it contains the solution based on fix-updater approach:

```ts
let first, last;
this.datasource.adapter.fix({
  updater: ({ data }) => {
    if (!first) {
      first = data;
    }
    last = data;
  }
});
```

If you need it to be reactive, you may wrap it with `isLoading$-false` subscription.
