### ISSUE TITLE
Feature Request: Update to Angular 10

### ISSUE THREAD

**Issue by xiaoxiangmoe** [dhilt/ngx-ui-scroll#190]

**Comment by dhilt** [comment]
@xiaoxiangmoe Do you have any specific issues with ngx-ui-scroll v1.7.0 and Angular v10? I guess it should work as is. You may see that peerDependencies section does not specify upper limits, so Angular v10 matches:

https://github.com/dhilt/ngx-ui-scroll/blob/92845ef057f0d99fbb9ee0a2d7246ed7f8262ba2/package-dist.json#L29-L33

Also, I created simplest demo: https://stackblitz.com/edit/ngx-ui-scroll-1-7-0-angular-10. Downloading, installing, running and building it locally are not accompanied by any problems. Maybe I'm missing something, so it would be helpful if you could specify the issue/repro.
