### ISSUE TITLE
Not working in IE11 

### ISSUE THREAD

**Issue by Mrpankaj666** [dhilt/ngx-ui-scroll#196]
Object doesn't support property or method 'entries'
i think this code is executing inside settings
any alternative,please suggest.

**Comment by dhilt** [comment]
@Mrpankaj666 I wonder if this might just be a polyfill problem... Please take a look to the issue https://github.com/dhilt/ngx-ui-scroll/issues/60 (2nd comment), try to set up "object" polyfill in your App. See also [official doc](https://angular.io/guide/browser-support) in its actual state.

**Comment by Mrpankaj666** [comment]
@dhilt Thanks, It was the same issue. i fixed to import  this `import 'core-js/es7/object';`
