### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by dhilt** [dhilt/ngx-ui-scroll#2]
Здесь можно обсуждать все идеи и моменты, касающиеся продукта до выхода первой версии. Что и как работает, улучшения, возможные направления развития.

**Comment by ndovnar** [comment]
@dhilt Мы можем первое время поработать по схеме "ты говоришь я делаю"? Мне бы так намного проще было влиться в проект). Есть одна идейка: было бы не плохо оставить возможность для прокидывания события 'scroll' для возможности кастомизации скрол бара.

**Comment by dhilt** [comment]
@babsley Да, это очень хорошая идея. Как прокидывание события поможет кастомизировать внешний вид? есть какие-то устоявшиеся техники на этот счет? Если у тебя нет вопросов по текущему коду, то можно начать двигаться в сторону тестов. Или подумать, как улучшить использование

```
<ui-scroll [datasource]="datasource" #item="myItem" #index="index" class="viewport">
    <span>{{index}}</span> : <b>{{myItem.text}}</b>
</ui-scroll>
```

я не знаю, что написал сейчас, это смутные фантазии [на тему](https://stackoverflow.com/questions/38582293/how-to-declare-a-variable-in-a-template-in-angular2). То же касается определения datasource (и datasource.get).

в общем использование (https://github.com/dhilt/ui-scroll/issues/4) и тесты (https://github.com/dhilt/ui-scroll/issues/3) первые на очереди.

**Comment by ndovnar** [comment]
@dhilt  https://github.com/jkuri/ngx-slimscroll, судь идеи что бы можно было стригирить событие не только через Element.scroll

**Comment by dhilt** [comment]
@babsley Да, будет очень хорошо, если мы сможем интегрироваться со сторонними компонентами, вроде ngx-slimscroll, именно в этом, как я вижу, заключено будущее компонентного подхода во front end. Я создал задачу: https://github.com/dhilt/ui-scroll/issues/5.

**Comment by dhilt** [comment]
Closed before pre-release.
