### ISSUE TITLE
Updating items fails if I changed the DOM before by marking the content via Mark.js

### ISSUE THREAD

**Issue by RuBAN-GT** [dhilt/ngx-ui-scroll#200]
Hello everyone! 

First of all, thank you for this library, it really saves my time. 
But in the one specific case where I interact with item DOM I found an expected behavior where it can't updated properly, please advice, how I can solve it. 

## Context

In my real project I have an items list where each item updated from subscription (websocket) and everything really works good but if I change sth in element dom using Mark.js library (I guess it doesn't matter how I changed elements), after update (I use `adapter.fix.updater` to change data and keep scrolling position) element data concatenated with previous (see below). If it will be the common angular loop, I would add `trackBy` to control this issue, but here I didn't find the way to do the same thing. 

## Steps to reproduce

I prepared the demo application with all required things: https://github.com/RuBAN-GT/ngx-ui-scroll-dom-issue-example

1. Install all dependencies and launch application: `npm i && npm start`
2. Enter any text phrase which should be contained in existing items. You can see that they were marked (I used Mark.js):

<img width="642" alt="image" src="https://user-images.githubusercontent.com/4778223/88911620-c3b2e600-d266-11ea-8bf0-61c1eaf4c161.png">

3. Now press "Make mutation" button which regenerates item name...but the dom for this item will be copied instead of replacing:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/4778223/88911702-e644ff00-d266-11ea-9daf-dc7f237cf75a.png">

---

So, I have two questions:

1) What the library expects when I should update the specific element keeping scroll position? I guess I should use `adapter.fix.updater`.
2) How I can indicate that Angular should rerender specific element without `trackFn`?

Thanks in advance!

**Comment by RuBAN-GT** [comment]
I investigated the `UiScrollComponent` class and we can provide `trackFn` and use for example some getter from item like that:

```html
    <div data-padding-backward></div>
    <div
      *ngFor="let item of items; trackBy: trackByFn"
....
```

```typescript
public trackByFn(index, item) {
  return item.data.trackId || index;
}
```

Probably it may help but I didn't check how it can affects to another functionality yet.

**Comment by dhilt** [comment]
@RuBAN-GT Nice issue, thank you for detailed description and repro. The problem obviously steams from the violation of what we call Separation of concerns principle. 

 1. `Adapter.fix({ updater })` deals with `data` which is a string in your case and which is being rendered in accordance with the template you defined in your App in `datatable.component.html`. Changing the `data` leads to changing the DOM, but `data` is not the DOM it's just an argument of the transformation.
2. Mark.js forces another process not connected with the Scroller, it changes DOM directly. It does not relate to `data` and does not touch Angular template interpolation.

Say, you have "My first string" as some row data and `{{item.text}}` as simplest template. You mark "first" and got following DOM: 

```html
  My <span marked>first</span> string
```

Looks like Mark.js shifts "first string" out of Angular control and Angular continue treat only "My" as `{{item.text}}`. When you update `text`, you update only remaining part which is my "My", and it turns into "My first string (updated)". Disconnected part follows after it, and you see

```html
  My first string (updated) <span marked>first</span> string
```

Let's consider the simplest (but certainly not the best solution) when you continue keep Mark.js processes separately from the Angular/Scroller processes. There are two steps you should done to resolve the issue in this case:

 - clean up marked rows during the update of the contents
 - re-mark them after the update

Not sure if this could be done in some safe/clear enough way. Instead, the correct approach would be to avoid disconnecting processes at all. Marking should be under the Angular control. Imagine we have `MyItem` component accepting item data and mark string:

```html
  <div class="viewport__item" *uiScroll="let item of datasource">
      <my-item [data]="item" [mark]="mark"></my-item>
  </div>
```

Applying to your case, `MyItem` might look like

```ts
@Component({
  selector: 'my-item',
  template: `<div class="viewport__content">
    [{{ data.id }}] -
    <span [innerHTML]="data.name | highlight: mark">{{ data.name }}</span>
  </div>`,
})
export class MyItemComponent {
  @Input() data: any;
  @Input() mark: string;
}
```

Where "highlight" is a custom pipe that could be taken form [here](https://stackoverflow.com/a/51711549/3211932):

```ts
@Pipe({
  name: 'highlight'
})
export class HighlightSearch implements PipeTransform {
  transform(value: string, args: string): any {
    if (args && value) {
      value = String(value); // make sure its a string
      const startIndex = value.toLowerCase().indexOf(args.toLowerCase());
      if (startIndex !== -1) {
        const matchingString = value.substr(startIndex, args.length);
        return value.replace(matchingString, "<mark>" + matchingString + "</mark>");
      }

    }
    return value;
  }
}
```

This way we control every step in terms of Angular with no broken bindings. DOM stays consistent.

**Comment by RuBAN-GT** [comment]
@dhilt, I didn't think in this direction, thank you so much for your detailed explanation!
