### ISSUE TITLE
API to get all available ItemAdapter from buffer using adapter

### ISSUE THREAD

**Issue by RuBAN-GT** [dhilt/ngx-ui-scroll#201]
Hello everyone,

The current `IAdapter` provides API to get last/first visible ItemAdapter from buffer, but what about the rest elements? Can I somehow to get these elements using public API? I dug it and found incapsulating of buffer for published adapter, but probably I missed something.

Additional question about virtual items - it will be nice to have api to get the first loaded item form all collection.

Thank you in advance!

**Comment by dhilt** [comment]
@RuBAN-GT There is an experimental API which provides some kind of access to current Buffer state: [adapter-fix-updater](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater). You may iterate through all buffered items and receive first/last buffered items as follows:

```js
let first = null, last = null;
this.datasource.adapter.fix({
  updater: ({ $index, element, data }) => {
    if (first === null) {
      first = data;
    }
    last = data;
  }
});
console.log(`first buffered item is ${first}`);
console.log(`last buffered item is ${last}`);
```

On absolute min/max loaded items. Say, we have `Adapter.min` and `Adapter.max` scalars.  Do they store only indexes? or cached items data too? Also, if the Datasource had been initialized with minIndex/maxIndex settings, but these items had never been loaded, what should `Adapter.max` show?

**Comment by RuBAN-GT** [comment]
@dhilt, got it. Thank you for answer!
