### ISSUE TITLE
Adapter.reset() doesn't apply new values passed into settings

### ISSUE THREAD

**Issue by StriderRanger** [dhilt/ngx-ui-scroll#203]
Hi!

I have a particular case where the ui-scroll list is not displayed unless the buffer is not empty.
When new items are added to the buffer, the list becomes visible and the configuration of the ui-scroll is updated via the `Adapter.reset()` method to reload the whole list.

The problem that I am facing is that the new configuration is not applied after calling the `Adapter.reset()` method. To be more specific, when the scroller is displayed, its `maxIndex` value is taken from the old settings and not from the new ones that are passed to the `Adapter.reset()` method.

To make things more clear [this is a stackblitz example](https://stackblitz.com/edit/angular-ngx-ui-scroll-append-first-item?file=src/app/app.component.ts) where the list is empty by default, and when clicking _once_ on the 'Add first items' button, the list is displayed but remains empty because the scroller is based on the old `maxIndex` value (as shown in the logs)

Any idea how to overcome this problem?

Thanks!

**Comment by dhilt** [comment]
@StriderRanger Well, here's [the fixed fork](https://stackblitz.com/edit/angular-ngx-ui-scroll-append-first-item-fix). The thing is the Scroller is not initialized at the moment of first items adding. This is how your template works. Initialization process interfered with `reset`. Delaying of the `reset` via `relax` could help, but my suggestion is more clear and fast: I do not `reset` if the Scroller is not initialized, I just update `Datasource.settings` before `Datasource` passes to the Scroller in that case.

**Comment by StriderRanger** [comment]
@dhilt Resetting the `Datasource.settings` before the first load has exactly the desired effect. Thanks for the fix :)
