### ISSUE TITLE
IE 11 entire window scroll ERROR Error: HTML element is not defined issue

### ISSUE THREAD

**Issue by dugls** [dhilt/ngx-ui-scroll#205]
Hello @dhilt first of all thanks for such great library it works great in Chrome, Firefox, Safari, Edge.
But I faced with ERROR Error: HTML element is not defined, when I set 'windowViewport: true' in datasource settings. The error appears in IE 11 console and my items don't show up in the UI. Also I noticed this issue in your demo sample so it seems like issue of ngx-ui-scroll library.
Here is the screenshot of error in IE 1
https://gyazo.com/0682ee9a136e91ff21b1f7656f6a3e66

**Comment by dhilt** [comment]
@dugls IE and the entire window case, what a bad mix... After some investigation I would say that it also doesn't work in Edge (the list loads unlimitedly). This is clearly the bug of the lib, will fix it shortly. I hope. Thanks for the report!

**Comment by dhilt** [comment]
@dugls ngx-ui-scroll v1.7.1 is published, it should fix the issue

**Comment by dugls** [comment]
@dhilt Thank you very much!
