### ISSUE TITLE
Access to virtual scroll elements (by QueryList)

### ISSUE THREAD

**Issue by AnnaKozlova** [dhilt/ngx-ui-scroll#207]
Hello! Thank you for awesome project.
I have a problem with access to virtual scroll elements: when i scroll to top, my QueryList do not match elements which are displayed on the screen from a datasource.
This case can be viewed here: [stackblitz](https://stackblitz.com/edit/ngx-ui-scroll-1-7-0-query-list?file=src/app/app.component.ts) console.log shows current QueryList

I need QueryList because i'm using cdk for keyboard support implementation. [Doing A11y easily with Angular CDK. Keyboard-Navigable Lists](https://indepth.dev/doing-a11y-easily-with-angular-cdk-keyboard-navigable-lists/)

Please tell me how I can avoid discrepancies and get the current values in QueryList?

**Comment by dhilt** [comment]
@AnnaKozlova Thanks for the stackblitz demo! First, there are 3 types of items: 

 - visible for the user (1)
 - invisible for the user but living in DOM (2)
 - virtual, that are not in DOM (3)

As I can see, QueryList contains exactly the same number of rows (types 1 and 2) as the DOM has per each after-view-init cycle. The list is sorted improperly, the first and the last items are wrong, but it seems [known issue](https://stackoverflow.com/questions/54035719/does-the-ordering-of-the-querylist-from-viewchildren-always-match-with-the-orde) and you may try to handle it at the App component level.

Also, you may access all the items existing in the current Scroller buffer via experimental [Adapter-fix-updater](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater) API:

```ts
this.datasource.adapter.fix({
  updater: ({ $index, data, element }) => {
    console.log(`Hello, I'm DOM element #${$index}`, element);
  }
});
```

**Comment by AnnaKozlova** [comment]
Thank you very much for your answer!
