### ISSUE TITLE
The problem of inserting new values.

### ISSUE THREAD

**Issue by AnnaKozlova** [dhilt/ngx-ui-scroll#208]
Hello. I have a problem inserting new values by index. For now, I insert at the end of the list (index of last element), but in the future it will be any index.

1. This code snippet works correctly, but if you look in the DOM, the extra elements are not deleted (although the buffer size is set - bufferSize: 16)
```
    await this.uiDatasource.adapter.insert({
      items,
      after: (item) => item.$index === uiIndex,
    });
```

2. If I call clip () after insertion, it will display the elements correctly in the DOM. The problem here is that if I am at the top of the list and do an insertion and then go to the end and repeat the insertion of values, nothing happens. There are no new values.
```
    await this.uiDatasource.adapter.insert({
      items,
      after: (item) => item.$index === uiIndex,
    });
    await this.uiDatasource.adapter.relax();
    await this.uiDatasource.adapter.clip({forwardOnly: true});
```

Do you have any suggestions on how to fix this? Thank.

**Comment by dhilt** [comment]
@AnnaKozlova Thanks for the video, though a runnable demo would be greater. First, I want to clarify when the clipping process happens. In current implementation it happens in a direction that is opposite to the scroll movement. So, if you append new items and then scroll down and want the topmost items to be clipped, you are obliged to do it manually. 

Second, the bufferSize setting is about minimum size of a batch of items that are being fetched via Datasource.get. Nothing to do with clipping. The [padding](https://dhilt.github.io/ngx-ui-scroll/#/settings#padding) setting does. This way the first sample seems correct for me.

What I see from the second sample is that the first insert works as expected by adding 1 item after the last visible index. Then you clip some last items out and my guess is that `uiIndex` becomes irrelevant, which causes empty insert. [Logging](https://github.com/dhilt/ngx-ui-scroll#development) might help, but anyway I would advise to look at the insert-after predicate and check the `uiIndex` consistency.

**Comment by AnnaKozlova** [comment]
Thank you!
