### ISSUE TITLE
Scroll thumb jumps away from mouse cursor when scrolling up, Win 10

### ISSUE THREAD

**Issue by ripebananas** [dhilt/ngx-ui-scroll#210]
Hello. First of all, thanks for the great library.

I am using the library only for virtual scrolling with fixed number of items. There seems to be an issue when scrolling up.

**Scenario**: Display a fixed number of items, e.g. 100. Slowly scroll down to the end of the list, then slowly start scrolling up the list.
Browser: Chrome Version 85.0.4183.102 (Official Build) (64-bit). But also happens with other Chrome versions and browsers.
**Actual result**: At some point the scroll thumb will go much faster than the mouse cursor and will not be beneath the mouse cursor.
**Expected result**: The scroll thumb and the mouse cursor keep the relative position to each other (i.e. the scroll thumb stays under the mouse cursor).

Please see this stackblitz demo that illustrates the issue - [https://stackblitz.com/edit/angular-ivy-uw4emc](https://stackblitz.com/edit/angular-ivy-uw4emc)

Thank you.

**Comment by dhilt** [comment]
@ripebananas Are you experiencing this on Windows?

**Comment by ripebananas** [comment]
Yes, it's on Windows 10.
I tested as well with Firefox and on Ubuntu.

Ubuntu/Windows 10 + Firefox - seems to be ok.
Ubuntu/Windows 10 + Chrome - experiencing the issue.

**Comment by dhilt** [comment]
Great, let's see what can be done... thanks for the issue!

**Comment by dhilt** [comment]
@ripebananas Please try ngx-ui-scroll v1.8.2 as it has the fix.
