### ISSUE TITLE
ng-container with uiScroll question?

### ISSUE THREAD

**Issue by whittssg** [dhilt/ngx-ui-scroll#212]
Hello,
I have a certain scenario where i have to use an ng-container with the uiScroll and it looks like this:

```
<div class="my scroll class">
<nz-timeline>
 <ng-container *uiScroll="let item of mySuperData">
 </ng-container>
</nz-timeline>
</div>
```

I have to use the container so that the ui component displays correctly but when i do this with uiScroll it only loads the first 5 items, the scrollbar on the first div doesnt trigger ui-scroll to load more items.

This is the simple data source:

```
mySuperData= new Datasource({
    get: (index, count, cb) => cb(this.mySuperArray.slice(index, index + count)),
    settings: {
      startIndex: 0
    }
  });
```
Amy i missing something really obvious?

Thanks

**Comment by dhilt** [comment]
@whittssg Thanks for the issue! I'm suspecting that the viewport defining procedure might work improperly in this case. Try to use new [viewportElement](https://dhilt.github.io/ngx-ui-scroll/#/experimental#viewportElement-setting) setting to explicitly set up your wrapping div as a viewport. If it will not help, I would ask you to fork/create [stackblitz demo](https://stackblitz.com/edit/ngx-ui-scroll-1-8-2-angular-10) reproducing the issue and I will take a look.

**Comment by whittssg** [comment]
Thank you for the info. I will give this ago
