### ISSUE TITLE
Inconsistent behavior with variable height items

### ISSUE THREAD

**Issue by juanreynolds** [dhilt/ngx-ui-scroll#228]
Thank you for a brilliant module.

I need to render non-fixed height items (chat). It renders the initial load sequence correctly about 80% of the time:

```
skipping fetch backward direction [initial loop]
forcing fetch forward direction [no item size]
fetch interval: [49..49]
fetch direction is "forward"
going to fetch 1 items started from index 49
resolved 1 items (index = 49, count = 1)
stat before new items render, pos: 0, size: 480.0000305175781, bwd_p: 0, fwd_p: 480, aver: no, items: 0, range: no
average size has been updated: 49
pos: 0, size: 529, bwd_p: 0, fwd_p: 480, aver: 49, items: 1, range: [49..49]
skipping clip [initial cycle]
stat after paddings adjustments, pos: 0, size: 2450, bwd_p: 2401, fwd_p: 0, aver: 49, items: 1, range: [49..49]
setting scroll position at 2122 (2409)
stat after scroll adjustment, pos: 2122, size: 2594, bwd_p: 2401, fwd_p: 0, aver: 49, items: 1, range: [49..49]
 loop 5-1-1 done, loop 5-1-2 start
start delta is 2409  (+8 offset)
fetch interval: [38..49]
```

20% of the time it renders incorrectly (it loads only 1 item and then halts) and the sequence diverges at the line: **average size has been updated: 0**

```
skipping fetch backward direction [initial loop]
forcing fetch forward direction [no item size]
fetch interval: [49..49]
fetch direction is "forward"
going to fetch 1 items started from index 49
resolved 1 items (index = 49, count = 1)
stat before new items render, pos: 0, size: 480, bwd_p: 0, fwd_p: 480, aver: no, items: 0, range: no
average size has been updated: 0
stat after new items render, pos: 0, size: 480, bwd_p: 0, fwd_p: 480, aver: no, items: 1, range: [49..49]
viewport size has not been changed
```

My settings are as follows:
```
bufferSize: Math.ceil(this._el.nativeElement.clientHeight / item_element.rowHeight),
minIndex: 0,
startIndex: 49,
maxIndex: 49,
padding: 1,
```
In the provided example of variable height elements have an inlilne style height whereas in my case there is no CSS height that is set.
I assume there is some kind of measuring error that occurs. In light of the fact that I am providing maxIndex it would be nice if there is some form of retry setting. Is that a possibility?

**Comment by dhilt** [comment]
@juanreynolds Thanks for the issue! I'm very worried about such unstable repro, you are right speaking of the problem in determining the item size, which is 0 right after render, but what is causing it? One example is coming to my mind: a row consisting of an asynchronously loaded image which is mostly (80%) taken from cache. In such or similar cases you may force the size checking via [Adapter.check](https://dhilt.github.io/ngx-ui-scroll/#/adapter#check-size) method. It will measure rows sizes and run the uiScroll Workflow if any changes are detected. But you need to know when it should be called. In case of async loaded images you may use ResizeObserver to watch for the DOM element size changing  or any other appropriate technique ([here is the example](https://stackblitz.com/edit/ngx-ui-scroll-change-viewport-size-in-real-time), it is for Viewport changes but it can be applied to rows).

Also, if you need to update `maxIndex` at runtime, we have [Adapter.fix](https://dhilt.github.io/ngx-ui-scroll/#/experimental) undocumented feature allowing to do it: `Adapter.fix({ maxIndex: 999 })`.

If this will not help, I'd ask you to build a minimal repro on stackblitz, let the chance to be 20%.

**Comment by juanreynolds** [comment]
@dhilt Thanks for the prompt response. adapter.check() solved the problem.

It did however introduce a new issue in the intitial scroll behavior. In the settings startIndex is set to the last item in the list. With set CSS height it moves to correct position. With no height set and adapter.check() the position was variable. I assume it was because the initial Workflow bailed early and when calling subsequent adapter.check() it is no longer required via the settings to perform the scroll behavior. I fixed it by subscribing to isLoading$ directly after dataSource instantiation wherein I wait for the adapter to relax followed by a manual fix scroll.

Great support. Thanks.

**Comment by ShoaibIqbal452** [comment]
@dhilt i am, having same kind of issue. It is very random but sometimes scroll works fine but in some cases upon prepending data i get following issue 
![image](https://user-images.githubusercontent.com/31730120/103780045-4fbb0c00-5056-11eb-9cb3-2b16fd8e4219.png)

This is how i am prepending data in my code.

```
  prependData(items: any | any[]): void {
    //prepend assumes data source is already initialized.
    if (!this.dataSource) return;

    items = Array.isArray(items) ? items : [items];
    items.reverse();
    //Source is exhausted and no more data that can be prepended. so do nothing and return.
    if (items.length === 0) {
      this.bofReached = true;
      this.pageNumber--;
      return;
    }

    this.updateVirtualIndex(items, -1, --this.minIndex);

    this.minIndex = this.minIndex - items.length + 1; 

    this.data = [...items, ...this.data];

    this.dataSource.adapter.prepend(items, true);
    this.doCheck();
    this.runAdapterDeferred(() => this.dataSource.adapter.clip());

  }
```
```

  private runAdapterDeferred(cb: Function): void {

    if (!this.dataSource) return;

    const { adapter } = this.dataSource;
    const clipLimit = this.bufferSize + 25;

     
    if (!adapter.isLoading && this.dataSource.adapter.itemsCount >= clipLimit) {
      cb();
      return;
    }
    const isLoadingSub = adapter.isLoading$.subscribe(isLoading => {
      if (!isLoading && this.dataSource.adapter.itemsCount >= clipLimit) {
        cb();
      }
      isLoadingSub.unsubscribe();
    });
  }

  private findElement(index: number): HTMLElement | null {
    const viewportElement = document.getElementsByClassName('new-active-partie__messages')[0];
    return viewportElement
      ? viewportElement.querySelector(`[data-sid="${index}"]`)
      : null;
  }

  private autoscroll(index: number) {
    const element = this.findElement(index);
    const viewportElement = document.getElementsByClassName('new-active-partie__messages')[0];
    if (!element || !viewportElement) {
      return;
    }
    const elementTop = element.getBoundingClientRect().top;
    const viewportTop = viewportElement.getBoundingClientRect().top;
    const toScroll = viewportTop - elementTop;
    const diff = viewportElement.scrollTop - toScroll;
    if (viewportElement.scrollTop === diff) {
      return;
    }
    console.log('diff : ', diff);
    this.dataSource.adapter.fix({ scrollPosition: diff });
  }

  async doCheck() {
    await this.dataSource.adapter.relax();
    let firstVisibleIndex: number | undefined;
    if (this.needAutoscroll) {
      firstVisibleIndex = this.dataSource.adapter.firstVisible.$index;
    }
    await this.dataSource.adapter.check();
    if (firstVisibleIndex !== undefined) {
      this.autoscroll(firstVisibleIndex);
    }
  }
```

The scroller stops responding after this HTML error. Any thoughts on this issue, plus is there anyway we can keep scroller responsive even after the HTML error?

**Comment by dhilt** [comment]
@ShoaibIqbal452 My guess is you have not 100% clear sequence, and there is a potential gap between prepend and clip, a race condition. I would rewrite it as follows:

```js
  async prependData(items) {
    await this.dataSource.adapter.relax();
    // ... other code
    // what is the most explicit sequence?  triple await
    await this.dataSource.adapter.prepend(items, true);
    await this.doCheck();
    await this.dataSource.adapter.clip();
  }

  async autoscroll(index) {
    // ... previous code
    this.dataSource.adapter.fix({ scrollPosition: diff });
    // "fix" don't deal with "relax" (currently), this might be the problem
    // you are trying to go through it with the "isLoading" approach, and it's ok, but
    // here we are sure the scroll will happen, so we can apply the following
    await new Promise(resolve => requestAnimationFrame(async () => {
      await this.datasource.adapter.relax();
      resolve(void 0);
    }));
  }

  async doCheck() {
    let firstVisibleIndex;
    if (this.needAutoscroll) {
      firstVisibleIndex = this.dataSource.adapter.firstVisible.$index;
    }
    await this.dataSource.adapter.check();
    if (firstVisibleIndex !== void 0) {
      await this.autoscroll(firstVisibleIndex);
    }
  }
```

If this doesn't help, send here another log (after updating the code) or create stackblitz demo, I will take a look.

**Comment by ShoaibIqbal452** [comment]
Hi @dhilt thank you for you reply, the above issue seems to be fixed. Now i am removing some data from adapter using adapter.remove method and its working fine, but upon every remove some data is being remove from the adapter. For instance if there are total of 80 messages upon removing an index there are 79 left, upon removing another index 77 are left upon removing another one 67 are left and it does not show 67-80 messages. Following is my remove data code

```
this.data = this.data.filter(item => item.messageId !== x.messageId);
        await this.dataSource.adapter.remove({
          predicate: ({ data }) =>
            data.messageId === x.messageId && data.messageType === 'DayFirstMessage',
        });
```
i am unable to figure out what's causing this problem. any help is appreciated. Thank You.
