### ISSUE TITLE
refresh data does not work

### ISSUE THREAD

**Issue by urielTwito** [dhilt/ngx-ui-scroll#230]
I have master salve layout

every time I select  a new master then the salve needs to be refreshed.

the slave is a big list so I need virtualization.

so I used this method ```datasource.adapter.reload()``` hoping it will refresh the list.

when I invoke this method I can see that the ```datasource.get``` was invoked and a new data was send to the ```success(data);```

but the UI was not updated.
Note, If I display the data outside the uiScroll it is displayed correctly (```{{data[0]}}```)

any idea why the screen is not refresh?

Another NOTE: My component is using the default changeDetection strategy

**Comment by urielTwito** [comment]
to workaround the problem I did write this "ugly code"
```
     this.isDataSourceVisible = false;
        setTimeout(() => {
            this.isDataSourceVisible = true;
        })
```
this destroys the uiScroll and create it again (just to refresh the data)

**Comment by dhilt** [comment]
@urielTwito Hello! It would be great to have a minimal repro of your case, because it seems odd to me that the component's view doesn't respond to reload. Also, looking at your workaround, I'd suggest you to try [Adapter.reset](https://dhilt.github.io/ngx-ui-scroll/#/adapter#reset) method:

> It differs from Adapter.reload because it re-instantiates all internal entities, which is equivalent to destroying the scroller and re-creating it again via ngIf.

**Comment by urielTwito** [comment]
I also tried Adapter.reset and it did not work,
I will try to create a test component to show this problem

**Comment by urielTwito** [comment]
while trying to recreate it does not happen, it is hard for me to see the differences,  so for now I guess we can close this issue, until I will find the root cause

**Comment by dhilt** [comment]
@dhilt Sure! if you're lucky we'll reopen it
