### ISSUE TITLE
HTML error randomly while appending data

### ISSUE THREAD

**Issue by ShoaibIqbal452** [dhilt/ngx-ui-scroll#239]
I am using UIScroll in my chat app. Everything seems to work fine but in some cases such as in a group chat of 5 or more people, one person is just viewing the chat while others are continuously sending messages in chat at a fast speed, let's say 5 or messages per second, the person who is viewing the chat get's this HTML error and scroller stops working until page is reloaded and scroller starts working fine. Following is the HTML error.
![image](https://user-images.githubusercontent.com/31730120/104600918-718e4180-569b-11eb-917e-832c9090098b.png)
Now the real problem here is that application crashes and user can no longer view new messages in chat. I want to know is there any way to catch this error so that application keeps running and user do not have to reload the page?

**Comment by dhilt** [comment]
@ShoaibIqbal452 I think the problem might be caused by uncontrolled concurrency of Adapter calls, and this is the case the [1.9.0 release](https://github.com/dhilt/ngx-ui-scroll/pull/221) was dedicated to. Do you protect your insertion procedure with `Adapter.relax()`?

```
async receiveMessage(...) {
  await this.datasource.adapter.relax();
  await this.datasource.adapter.append(...);
  ...
}
```
