### ISSUE TITLE
get observable completion causes TypeError: Cannot read property 'unsubscribe' of undefined

### ISSUE THREAD

**Issue by vbraun** [dhilt/ngx-ui-scroll#243]
When using the datasource get observable API a JS error is logged when the observable completes. 

Note: The observable is apparently not automatically unsubscribed from inside ngx-ui-scroll, so api users must complete it.   

Fails with 2.0.0-rc.3, works (i.e. no error logged) with 1.11.1

Stackblitz: https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0-i1ogfp?file=src/app/app.component.ts
~~~
preview-fef3604….js:1 ERROR TypeError: Cannot read property 'unsubscribe' of undefined
    at SafeSubscriber.eval [as _complete] (fetch.ts:99)
    at SafeSubscriber.wrappedComplete (Subscriber.ts:248)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:265)
    at SafeSubscriber.complete (Subscriber.ts:251)
    at Subscriber._complete (Subscriber.ts:148)
    at Subscriber.complete (Subscriber.ts:126)
    at Observable.eval [as _subscribe] (subscribeToArray.ts:11)
    at Observable._trySubscribe (Observable.ts:238)
    at Observable.subscribe (Observable.ts:219)
    at Function.Fetch.get (fetch.ts:99)
~~~

**Comment by dhilt** [comment]
@vbraun It is done in [v2 PR](https://github.com/dhilt/ngx-ui-scroll/pull/238) and released  as **[ngx-ui-scroll v2.0.0-rc.4](https://www.npmjs.com/package/ngx-ui-scroll/v/2.0.0-rc.4)**. The thing is that in v1 Observable signature was the main, in v2 the main signature has been turned to Promise, because v2 got rxjs-free core published as [vscroll](https://www.npmjs.com/package/vscroll) (and the end fix [is there](https://github.com/dhilt/vscroll/commit/369236e12bf55edda6fcdd34c520a21fae846d75)). Thanks a lot!

**Comment by gaoyajiang** [comment]
ERROR TypeError: Cannot redefine property: id
    at Function.defineProperty (<anonymous>)
    at vscroll.esm5.js:4200
    at Array.forEach (<anonymous>)
    at new Adapter (vscroll.esm5.js:4188)
    at Scroller.push../node_modules/vscroll/dist/bundles/vscroll.esm5.js.Scroller.initDatasource (vscroll.esm5.js:4499)
    at new Scroller (vscroll.esm5.js:4475)
    at new Workflow (vscroll.esm5.js:4739)
    at UiScrollComponent.ngOnInit (ngx-ui-scroll.js:43)
    at callHook (core.js:3038)
    at callHooks `(core.js:3008)```

**Comment by dhilt** [comment]
@gaoyajiang "id" redefining... Could you add repro? Or at least code sample + log report? Also, I suppose this issue is not connected with datasource, so probably it would be to make a new issue.

**Comment by gaoyajiang** [comment]
> @gaoyajiang "id" redefining... Could you add repro? Or at least code sample + log report? Also, I suppose this issue is not connected with datasource, so probably it would be to make a new issue.

My scenario is like this: I have many lists, each with a lot of data. ngx-uiui-scroll is introduced when viewing list data.When I view the data of a certain list for the first time, it is successful. When I exit, I will report the error of last time when I view the data of other lists.

**Comment by gaoyajiang** [comment]
> @gaoyajiang "id" redefining... Could you add repro? Or at least code sample + log report? Also, I suppose this issue is not connected with datasource, so probably it would be to make a new issue.
Another problem is that if the buffer size is set to a large value, there will be a problem when sliding: when sliding to the 20th, slide again. When it replaces the buffer data, the data will jump directly to the 25th, not the 21st. If buffersize is set smaller, the screen will be white when swiping quickly.. The height of each item in my project is dynamic, different, and there is a big gap.

**Comment by vbraun** [comment]
I can confirm that the original `TypeError: Cannot read property 'unsubscribe' of undefined` bug is fixed in rc4, thank you!
