### ISSUE TITLE
Using multiple lists. TypeError: Cannot redefine property: id

### ISSUE THREAD

**Issue by dhilt** [dhilt/ngx-ui-scroll#244]
This issue is based on https://github.com/dhilt/ngx-ui-scroll/issues/243 comments and it needs to get more details.

**Comment by gaoyajiang** [comment]
Error report caused by datasource replacement

**Comment by dhilt** [comment]
@gaoyajiang My guess is your problem follows from the way you instantiate the Datasource/Datasources in your application. To help you I need two things:

 - code sample of how you call `new Datasource` with all related infrastructure
 - full [dev log](https://github.com/dhilt/ngx-ui-scroll#development) (`devSettings: { debug: true }`) attached as a separate file

**Comment by gaoyajiang** [comment]
public datasource = new Datasource({
    get: (index, count, success) => {
      if (this.item.length === 0) {
        setTimeout(() => {
          index -= 1
          success(this.item.slice(index, index + count))
        }, 2000)
      } else {
        index -= 1
        success(this.item.slice(index, index + count))
      }
    },
    devSettings: { debug: true }
  })``

**Comment by gaoyajiang** [comment]
`resolved 5 items (index = 1, count = 5)
vscroll.esm5.js:2899 stat before new items render, pos: 0, size: 634, bwd_p: 0, fwd_p: 634, aver: no, items: 0, range: no
vscroll.esm5.js:2899 average size has been updated: 77
vscroll.esm5.js:2899 stat after new items render, pos: 0, size: 1077.2000732421875, bwd_p: 0, fwd_p: 634, aver: 77, items: 5, range: [1..5]
vscroll.esm5.js:2899 skipping clip [initial cycle]
vscroll.esm5.js:2899 forward padding will be increased by 191.199951171875 to fill the viewport
vscroll.esm5.js:2899 stat after paddings adjustments, pos: 0, size: 634.2000122070312, bwd_p: 0, fwd_p: 191, aver: 77, items: 5, range: [1..5]
vscroll.esm5.js:2899 ---=== loop 1-1-1 done, loop 1-1-2 start
vscroll.esm5.js:2899 start delta is 0
vscroll.esm5.js:2899 fetch interval: [-1..10]
vscroll.esm5.js:2899 fetch interval after Buffer flushing: [6..10]
vscroll.esm5.js:2899 fetch direction is "forward"
vscroll.esm5.js:2899 going to fetch 5 items started from index 6
vscroll.esm5.js:2899 resolved 5 items (index = 6, count = 5)
vscroll.esm5.js:2899 stat before new items render, pos: 0, size: 634.2000122070312, bwd_p: 0, fwd_p: 191, aver: 77, items: 5, range: [1..5]
vscroll.esm5.js:2899 average size has been updated: 90
vscroll.esm5.js:2899 stat after new items render, pos: 0, size: 1187.800048828125, bwd_p: 0, fwd_p: 191, aver: 90, items: 10, range: [1..10]
vscroll.esm5.js:2899 skipping clip [initial cycle]
vscroll.esm5.js:2899 stat after paddings adjustments, pos: 0, size: 996.7999877929688, bwd_p: 0, fwd_p: 0, aver: 90, items: 10, range: [1..10]
vscroll.esm5.js:2899 ---=== loop 1-1-2 done, loop 1-1-3 start
vscroll.esm5.js:2899 start delta is 0
vscroll.esm5.js:2899 fetch interval: [-1..9]
vscroll.esm5.js:2899 fetch interval after Buffer flushing: [-1..0]
vscroll.esm5.js:2899 fetch interval after bufferSize adjustment: [-4..0]
vscroll.esm5.js:2899 going to fetch 5 items started from index -4
vscroll.esm5.js:2899 resolved 0 items (index = -4, count = 5)
vscroll.esm5.js:2899 ---=== loop 1-1-3 done
vscroll.esm5.js:2899    ~~~ WF Cycle 1-1 FINALIZED ~~~  
`

**Comment by gaoyajiang** [comment]
```js
public datasource = new Datasource({
  get: (index, count, success) => {
    if (this.item.length === 0) {
      setTimeout(() => {
        index -= 1
        success(this.item.slice(index, index + count))
      }, 2000)
    } else {
      index -= 1
      success(this.item.slice(index, index + count))
    }
  },
  devSettings: { debug: true }
})
```

**Comment by dhilt** [comment]
@gaoyajiang I don't see error in the log, it needs to be full, starting with "uiScroll Workflow has been started", ending with the error "Cannot redefine property: id".

Then, Datasource instantiation is fine, but how do you switch between lists? Do you copy DS or re-instantiate it? I need to see corresponded code. 

Well, the best option would be to create a stackblitz demo (forked from **[this one](https://stackblitz.com/edit/ngx-ui-scroll-1-11-0-angular-11?file=package.json)** for example); this way I would catch the problem in 5 minutes.

**Comment by gaoyajiang** [comment]
> @gaoyajiang I don't see error in the log, it needs to be full, starting with "uiScroll Workflow has been started", ending with the error "Cannot redefine property: id".
> 
> Then, Datasource instantiation is fine, but how do you switch between lists? Do you copy DS or re-instantiate it? I need to see corresponded code.
> 
> Well, the best option would be to create a stackblitz demo (forked from **[this one](https://stackblitz.com/edit/ngx-ui-scroll-1-11-0-angular-11?file=package.json)** for example); this way I would catch the problem in 5 minutes.

Demo is a bit complicated, but I solved it. Reset the datasourcewhen the component is destroyed

**Comment by dhilt** [comment]
@gaoyajiang Glad to hear! `Adapter.reset` might be a good backdoor when we need to deal with different views under a single datasource host.

**Comment by dhilt** [comment]
@gaoyajiang Regarding your question

> When I use this.datasource.adapter.reload(20) to slide to the 20th item，then slide up again, the first to 19th items are not loaded....I created demo: https://stackblitz.com/edit/angular-ivy-mgctqr?file=src%2Fapp%2Fapp.component.html
>

You need to set startIndex = 0 (its default value is 1) and don't decrease `index` on Datasource.get:

```js
datasource = new Datasource({
  get: (index, count, success) =>
    success(this.items.slice(index, index + count)),
  settings: {
    startIndex: 0
  }
});
```

**Comment by gaoyajiang** [comment]
> and don't decrease `index` on Datasource.get:

I set startIndex = 0， but when slide up ，the previous data is still not loaded

**Comment by dhilt** [comment]
@gaoyajiang `index -= 1` must be removed too, this breaks DS consistency and Scroller falls into begin-of-file situation.

**Comment by gaoyajiang** [comment]
> @gaoyajiang `index -= 1` must be removed too, this breaks DS consistency and Scroller falls into begin-of-file situation.

emmm,That's not the reason. I want to jump to the corresponding item, according to the index，then i use  this.datasource.adapter .reload(20)，But when the data I want to jump is in the buffer, the content in front of the data disappears.

**Comment by gaoyajiang** [comment]
> > @gaoyajiang `index -= 1` must be removed too, this breaks DS consistency and Scroller falls into begin-of-file situation.
> 
> emmm,That's not the reason. I want to jump to the corresponding item, according to the index，then i use this.datasource.adapter .reload(20)，But when the data I want to jump is in the buffer, the content in front of the data disappears.

This problem has been solved，set minIndex = 0 .... But another problem is that my items are get from the network, and there will be delays.However, in the new datasource, my items data had not been geted, but now get has been executed, so I couldn't get the reader data at the beginning.

**Comment by dhilt** [comment]
@gaoyajiang Good to know you are done with the previous issue! If you want me to look at the next one, please share new demo and the step-by-step details of how to reproduce it.

**Comment by gaoyajiang** [comment]
> @gaoyajiang Good to know you are done with the previous issue! If you want me to look at the next one, please share new demo and the step-by-step details of how to reproduce it.

https://stackblitz.com/edit/angular-ivy-mgctqr?file=src%2Fapp%2Fapp.component.ts   This is my demo.Thank you.

**Comment by dhilt** [comment]
@gaoyajiang It is hard to get from your description what the issue you are trying to solve... But what I see from the demo is that you have problem with connection between datasource and real data. Basically the Datasource is responsible for getting the data from the remote storage, and the Datasource.get should deal with network latency and provide caching of the data that was already received. 

But if you really want to initialize the entire dataset on the App start, you need to explicitly split the algorithm into 2 phases: remote data initialization and Scroller initialization. In this case (when the Datasource.get implementation is synchronous) Scroller must not be initialized before you have all the data the Datasource will deal with. Speaking of your demo, the easiest way to provide such consistency is to protect the uiScroll render by ngIf:

```html
<div class="viewport" *ngIf="items.length">
  <app-card *uiScroll="let item of datasource" ... />
</div>
```

**Comment by gaoyajiang** [comment]
> @gaoyajiang It is hard to get from your description what the issue you are trying to solve... But what I see from the demo is that you have problem with connection between datasource and real data. Basically the Datasource is responsible for getting the data from the remote storage, and the Datasource.get should deal with network latency and provide caching of the data that was already received.
> 
> But if you really want to initialize the entire dataset on the App start, you need to explicitly split the algorithm into 2 phases: remote data initialization and Scroller initialization. In this case (when the Datasource.get implementation is synchronous) Scroller must not be initialized before you have all the data the Datasource will deal with. Speaking of your demo, the easiest way to provide such consistency is to protect the uiScroll render by ngIf:
> 
> ```
> <div class="viewport" *ngIf="items.length">
>   <app-card *uiScroll="let item of datasource" ... />
> </div>
> ```

Thank you very much. The problem is solved

**Comment by gaoyajiang** [comment]
There is a new problem. I want to jump to the specified item according to the index and use the adapter.reload (index), but the DOM will render again. Is there any way for DOM not to render again？

**Comment by gaoyajiang** [comment]
https://stackblitz.com/edit/ngx-ui-scroll-1-11-0-angular-11-cqtqap?file=src%2Fapp%2Fapp.component.html
I have a problem, such as demo. When I have little data, I also want the H1 tag below to be next to the data above
