### ISSUE TITLE
Page scrolls to component when using windowViewport

### ISSUE THREAD

**Issue by tonybruess** [dhilt/ngx-ui-scroll#250]
When using `windowViewport: true`, `Viewport#setOffset` scrolls the page to the position of the Angular component.

I don't quite understand this behavior and am wondering if it would be possible to change or disable this initial jump. 

Please let me know if I can provide any more clarification.

**Comment by dhilt** [comment]
@tonybruess I created simple demo on stackblitz -- [Entire window demo](https://stackblitz.com/edit/ngx-ui-scroll-2-angular-11-entire-window) -- it would be great if you could modify it and provide more detailed repro linked with it.

**Comment by tonybruess** [comment]
@dhilt looks like it happens when `minIndex` is not set https://stackblitz.com/edit/ngx-ui-scroll-2-angular-11-entire-window-wmttkp

**Comment by dhilt** [comment]
@tonybruess Great! When `minIndex` is not defined or less than `startIndex`, the Scroller will request backward items until the viewport with its outlets (controlled by `padding` setting) is filled out. The `windowViewport` setting means the entire window is the viewport, and in this case any "header" above the Scroller element will mess and cause flickering. Also, stackblitz iframe body has 8px margin that results in additional shifting.

Here's new version of the Entire window demo for unlimited datasource: https://stackblitz.com/edit/ngx-ui-scroll-2-angular-11-entire-window-unlimited. I cleaned up all extra elements and styles. It looks fine for me, but perhaps this is not what you want?

**Comment by tonybruess** [comment]
Ah, now that behavior makes more sense. Thanks for the explanation and assistance! Setting `minIndex` in my app fixed the issue :)
