### ISSUE TITLE
Deleting an item does not update the index in the datasource

### ISSUE THREAD

**Issue by gaoyajiang** [dhilt/ngx-ui-scroll#251]
https://stackblitz.com/edit/ngx-ui-scroll-1-11-0-angular-11-r3yxdm?file=src%2Fapp%2Fapp.component.ts

hello，，this is demo. When you click add, (add more items), and then delete the newly added item, the ID of the item after the deleted item has not been updated.please help me, thank you.

**Comment by gaoyajiang** [comment]
> https://stackblitz.com/edit/ngx-ui-scroll-1-11-0-angular-11-r3yxdm?file=src%2Fapp%2Fapp.component.ts
> 
> hello，，this is demo. When you click add, (add more items), and then delete the newly added item, the ID of the item after the deleted item has not been updated.please help me, thank you.

Although this.datasource.adapter.reset() can solve the problem， but it causes DOM to render again.

**Comment by gaoyajiang** [comment]
> > https://stackblitz.com/edit/ngx-ui-scroll-1-11-0-angular-11-r3yxdm?file=src%2Fapp%2Fapp.component.ts
> > hello，，this is demo. When you click add, (add more items), and then delete the newly added item, the ID of the item after the deleted item has not been updated.please help me, thank you.
> 
> Although this.datasource.adapter.reset() can solve the problem， but it causes DOM to render again.

I think DOM rendering

**Comment by dhilt** [comment]
@gaoyajiang You have few issues with id-index conversion in your demo. This causes inconsistency between the Datasource and the Scroller's buffer when you do Adapter.remove. I created a new demo that solves all the requirements I can see in your sample. The main point is that I excluded "id" from the algorithm and provided pure "index" flow:

https://stackblitz.com/edit/ngx-ui-scroll-append-and-remove-by-index

**Comment by gaoyajiang** [comment]
> @gaoyajiang You have few issues with id-index conversion in your demo. This causes inconsistency between the Datasource and the Scroller's buffer when you do Adapter.remove. I created a new demo that solves all the requirements I can see in your sample. The main point is that I excluded "id" from the algorithm and provided pure "index" flow:
> 
> https://stackblitz.com/edit/ngx-ui-scroll-append-and-remove-by-index

https://stackblitz.com/edit/ngx-ui-scroll-1-11-0-angular-11-r3yxdm?file=src%2Fapp%2Fapp.component.ts
I know what you mean, but my demo is the same as yours. I also remove the item from datasource. You can add items, then delete them and view datasource on the console. My datasource is different from the rendered data.
![企业微信截图_16140662181830](https://user-images.githubusercontent.com/53201532/108815929-3bc06f00-75f0-11eb-8b95-43d178cb939e.png)

On demand. The index displayed must be the ID in the data

**Comment by dhilt** [comment]
@gaoyajiang Having 2 destructive operations (append and remove) I would recommend you to switch from id-index to a pure index approach. Sequences like 

```
    const index = this.items.slice(-1)[0].id;
    this.items.push({ id: index + 1, text: "item #" });
    ...
    this.items.splice(id - 1, 1);
    this.items.forEach((v, index) =>v.id = index + 1);
```

troubles the data flow consistency. Follow [this sample](https://stackblitz.com/edit/ngx-ui-scroll-append-and-remove-by-index). Note that you have 2 different layers of indexing:

- natural indexes of the initial data array started from 0;
- integer indexes of the Scroller's datasource that appear in Datasource.get as its index-count arguments.

**Comment by gaoyajiang** [comment]
> @gaoyajiang Having 2 destructive operations (append and remove) I would recommend you to switch from id-index to a pure index approach. Sequences like
> 
> ```
>     const index = this.items.slice(-1)[0].id;
>     this.items.push({ id: index + 1, text: "item #" });
>     ...
>     this.items.splice(id - 1, 1);
>     this.items.forEach((v, index) =>v.id = index + 1);
> ```
> 
> troubles the data flow consistency. Follow [this sample](https://stackblitz.com/edit/ngx-ui-scroll-append-and-remove-by-index). Note that you have 2 different layers of indexing:
> 
> * natural indexes of the initial data array started from 0;
> * integer indexes of the Scroller's datasource that appear in Datasource.get as its index-count arguments.

I know what you mean, but my list is converted from a two-dimensional array, so there will be two indexes。
1.item1
1.item1-item1
2.item1-item2
3.item1-item3
2.item2
1.item2-item1
2.item2-item2
3.item2-item3
