### ISSUE TITLE
When the content contains large images, the scroll bar positioning is abnormal

### ISSUE THREAD

**Issue by coloz** [dhilt/ngx-ui-scroll#253]
Is there a way to recalculate the content height when scrolling?

**Comment by dhilt** [comment]
@coloz [Adapter.check](https://dhilt.github.io/ngx-ui-scroll/#/adapter#check-size) method should help. From Readme:

> **check** Checks if any of the current items have changed their size and runs a procedure to provide internal consistency and new items fetching if needed.

Also [this comment](https://github.com/dhilt/ngx-ui-scroll/issues/228#issuecomment-730500202) might be useful.

**Comment by coloz** [comment]
@dhilt it's useful,thanks
