### ISSUE TITLE
vscroll dependency doesn't update when ngx-ui-scroll is updated

### ISSUE THREAD

**Issue by dpraul** [dhilt/ngx-ui-scroll#255]
Hiya! I recently installed `ngx-ui-scroll@2.0.0-rc.6`, and then a few days later I saw you published `2.0.0-rc.7` to NPM.

When I updated, it did not update `vscroll` to `1.0.0-rc.7`, so the package did not work correctly.

I believe this is because the required version range for `vscroll` is too broad on the published `ngx-ui-scroll` (`>=1.0.0-rc.4 <2.0.0`). Since `vscroll` was already resolved to `1.0.0-rc.6` in my lockfile, it did not update it when I updated `ngx-ui-scroll`.

**Comment by dhilt** [comment]
@dpraul Thank you!  It [is fixed](https://github.com/dhilt/ngx-ui-scroll/pull/252/commits/d5216e996cdf48c0204cfa5570f8860f25aff2a6) and ngx-ui-scroll v2.0.0-rc.8 is published, please check! 
PS Do not hesitate to suggest PR next time 😁

**Comment by dpraul** [comment]
Fantastic, thanks for the quick fix!

Next time I'll try to do the PR myself :)
