### ISSUE TITLE
Find item in datasource so that I can modify its attributes

### ISSUE THREAD

**Issue by tubergen** [dhilt/ngx-ui-scroll#256]
Hi, I have a nested tree structure of posts, e.g.

- post_1
  - comment_1
    - subcomment_1
    - subcomment_2
  - comment_2
- post_2
- post_3

etc etc

Each post/comment is an object like `{id: 123, comments: [comment_1, comment_2]} `

Based on what the user does in the UI, I need to do things like
- append a new comment to some parent post's `comments`
- update the comment counts of various posts in the tree (e.g. when there's a new comment, i need to update the parent post's comment count, and the grandparent's comment count, etc, all the way up to the root)

Is there any way I can iterate over the items in the datastore, find the post/comment I need, and modify the attributes (e.g. append a new comment to the comment's array) ? 

If there were a `find` method or iterator on the datastore, I could just use that to find the element I need and then use `replace`, but I didn't see that. Alternatively, if there's some way I can access the datastore's underlying array, that would work

Apolz if I missing something obvious

**Comment by dhilt** [comment]
@tubergen There are two methods providing access to items that are rendered in the viewport at the moment. The first is [Adapter.fix({ updater })](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater) method, which is a part of experimental API. If you iterate over posts only (*uiScroll="let item of postsDatasource"), this method might help, as it allows to update items in-place, I mean you can update items contents/attributes, you can't remove/add items.

The second method is **Adapter.update**, which is a part of ngx-ui-scroll v2 release (it is in rc for now, but available) and currently has no documentation. This method is a good friend if you need to have access to buffered items and at the same time to perform delete/insert operations over buffer. So it is helpful if you iterate over flat list where each entry might be post OR comment (*uiScroll="let item of flatDatasource"). For example, you need to insert new comment to post #X:

```ts
interface Entry {
  id: string;
  type: 'post' | 'comment';
  postId: string | null;
  text: string;
}

this.injectComment({ id: 'Y', postId: 'X', type: 'comment', text: '...' });

async injectComment(comment: Entry) {
  const { adapter } = this.myDatasource;
  await adapter.relax();
  let post: Entry, lastComment: Entry;
  adapter.update({ 
    predicate: ({ $index, data, element }) => {

      // find post X
      if (data.type === 'post' && data.id === comment.postId) {
        post = data;
        return true; // do not modify Buffer at this item
      }

      // find the last comment of the post X
      if (post && data.type === 'comment' && data.postId === comment.postId) {
        lastComment = data;
        return true; // do not modify Buffer at this item
      }

      // this branch is for the first entry after the last comment of the post X is found
      if (lastComment) {
        return [commentToAppend, data]; // prepend new item before the current one
      }

      return true; // don't touch other items
    }
  });
}
```

If you need to remove item, return `false`. If you need to replace: return [itemToReplace]. Append: [data, itemToAppend]. Here is the [spec for Adapter.update API](https://github.com/dhilt/ngx-ui-scroll/blob/v2.0.0-rc.9/tests/adapter.update.spec.ts), perhaps it may help, while there is no doc. Adapter.update should become a flagman method of the Adapter API in the nearest future. Moreover, Adapter.insert and Adapter.replace already use Adapter.update under hood in v2-rc.9.

**Comment by tubergen** [comment]
Thanks for the awesome response. I'm using the `update` method and it's helpful. Follow-up question: Is there a simple way to iterate over everything in the datasource in typescript?

Something like

```
for (let item of datasource) {
  // do stuff
}
```

**Comment by dhilt** [comment]
@tubergen If you speak about Scroller's Datasource, there is no explicit way to iterate over the data items with the Scroller's API. Datasource is a sort of data service which is used by Scroller to actualize the viewport, it does not control the data, the host component does. Scroller incapsulates data items retrieved via Datasource.get in its internal [Buffer](https://github.com/dhilt/vscroll/blob/v1.0.0-rc.8/src/classes/buffer.ts) and [Cache](https://github.com/dhilt/vscroll/blob/v1.0.0-rc.8/src/classes/cache.ts) storages that are invisible from the outside. At this point of view, I would say, if you can implement Datasource.get, you should be able to have access to all the data the Scroller might deal with.

From the other hand, update-API allows to iterate over the items that are in the current Scroller's Buffer:

```js
const items = [];
this.ds.adapter.fix({ updater: ({ data }) => items.push(data) });
console.log(items); // synchronous!
```

```js
const items = [];
await this.ds.adapter.update({ predicate: ({ data }) => !!items.push(data) });
console.log(items);
```

**Comment by tubergen** [comment]
Sounds good, thank you!
