### ISSUE TITLE
how to change maxIndex

### ISSUE THREAD

**Issue by coloz** [dhilt/ngx-ui-scroll#259]
I'm writing a comment function, post a comment and jump to the latest comment.
I do it by the following way:
```
        this.total = this.total + 1;
        await this.datasource.adapter.reset({
          settings: {
            windowViewport: true,
            minIndex: 1,
            maxIndex: this.total,
            startIndex: 1,
            bufferSize: 15,
          }
        });
        await this.datasource.adapter.relax();
        await this.datasource.adapter.reload(this.threadInfo.total);
        await this.datasource.adapter.relax();
        await this.datasource.adapter.fix({ scrollPosition: +Infinity });
```

but,when reset() is called, data will use index = 1 to reload.Is there a way to reset the maxindex without calling reset?

------------------------
ps，I tried to use reload (index) directly, but the positioning position of the scroll bar was deviated, so I used fix ({scrollposition: + infinity}) to scroll to the bottom

**Comment by dhilt** [comment]
@coloz [Adapter.fix experimental API](https://github.com/dhilt/vscroll/blob/v1.0.0-rc.8/src/interfaces/adapter.ts#L112-L119) allows to maintain min/max indexes manually: 

```js
this.ds.adapter.fix({ maxIndex: this.ds.adapter.bufferInfo.absMaxIndex + 1 });
```

But basically, inserting new rows to the datasource is accomplished via Adapter append, prepend, insert or update (new, v2) methods. These methods don't force reload and provide min/max indexes and other internal params consistency. Here is the demo of simple chat app where Adapter.append is used to process new messages: https://stackblitz.com/edit/ngx-ui-scroll-chat-app-2

```ts
  async processNewItems(items: Item[]) {
    const { adapter } = this.datasource;
    await adapter.relax();
    await adapter.append({ items, eof: true });
    if (this.scrollToBottom) {
      adapter.fix({ scrollPosition: Infinity });
    }
    adapter.clip();
  }
```

Complex (post-comment) hierarchy might be fulfilled via Adapter.insert or Adapter.update methods. There are no good examples at this moment, but you may check [this thread](https://github.com/dhilt/ngx-ui-scroll/issues/256#issuecomment-798785649).

**Comment by coloz** [comment]
@dhilt  Thanks a lot for your program and reply
