### ISSUE TITLE
Compatibility of ngx-ui-scroll version 2.0.0 with Angular 7

### ISSUE THREAD

**Issue by anasrbh** [dhilt/ngx-ui-scroll#262]
Hello and thank you for the enormous work you have done.

I wanted to know if version 2.0.0 of the library can be compatible with Angular 7 ?

Thank you.

**Comment by dhilt** [comment]
@anasrbh Yes, it should work, I placed "ngx-ui-scroll v2 / Angular 7" demo on stackblitz, please take a look: https://stackblitz.com/edit/ngx-ui-scroll-2-with-angular-7

**Comment by anasrbh** [comment]
@dhilt Thank you for your response. I'm glad it works for angular 7. But in my case, I get error messages during compilation when I upgrade from version 1.11.1 of ngx-ui-scroll to 2.0.2. Maybe I missed something.

Here are the error messages:


![Capture d’écran (18)](https://user-images.githubusercontent.com/82844585/115388320-05f8ca80-a1dc-11eb-8c58-ae67db3db3ef.png)


Here is how I instantiated the datasource :


![Capture d’écran (21)](https://user-images.githubusercontent.com/82844585/115389336-4147c900-a1dd-11eb-8400-0a21186be720.png)

**Comment by dhilt** [comment]
@anasrbh Thanks for details! It seems to be a Typescript compatibility issue. The point is that vscroll is built with Typescript 4 and uses Omit helper type which was introduced in [Typescript 3.5.1](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/#the-omit-helper-type). The nearest Angular version supporting TS 3.5 is [Angular 8.2](https://github.com/angular/angular/issues/31059). I would certainly not insist on updating the Angular, but it might be a good solution while I'm looking at the problem on the lib's end.

**Comment by anasrbh** [comment]
@dhilt Ok, I'll try to update Angular and see if the problem is fixed. 
Do you think there is a chance that the latest version of ngx-ui-scroll might work on Angular 7 ?

**Comment by dhilt** [comment]
@anasrbh Omit is not the only problem, I'm afraid. I can get rid of TS Omit, but "ambient context" is much more painful thing, there was a breaking change introduced in TS 3.7 -- https://github.com/microsoft/TypeScript/issues/33939 -- it made 3.7+ compiled code incompatible with the code compiling by the previous (3.7-) TS versions. And Angular 8 will not help, only Angular 9 will. I need to think... fixing this on the lib's end might be quite expensive. But let's not rush to conclusions.

Meanwhile there is a simplest workaround, you may turn the external libs checking off by adding the following to your tsconfig.json:

```
"skipLibCheck": true,
```

This will degrade type checking, but will allow to compile incompatible TS pieces.

**Comment by anasrbh** [comment]
@dhilt I added the "skipLibCheck" option to tsconfig. This certainly made the "TS Omit" and "ambient context" errors disappear.
But there is always a compilation error following the instantiation of the datasource.


![Capture d’écran (25)](https://user-images.githubusercontent.com/82844585/115428480-ba0d4c00-a202-11eb-8281-5013e6e0cebb.png)


This may be due to the new type of the adatper variable in the datasource constructor :



![Capture d’écran (26)](https://user-images.githubusercontent.com/82844585/115429075-56cfe980-a203-11eb-8d7e-129342df297b.png)




Maybe i need to update angular to at least version 8.2 to get rid of this error message.

I was also wondering is there a real change between version 1.11.1 and 2.0.2 ?

Thank you.

**Comment by dhilt** [comment]
@anasrbh The main purpose of v2 release is extracting the core into a separate framework-independent npm package [vscroll](https://github.com/dhilt/vscroll), which is going to be used outside the Angular universe. It was accompanied with multiple infrastructure updates, and in particular vscroll uses TS4. 

I just pushed a new tiny Angular7 project with ngx-ui-scroll v2 and skipLibCheck setting into Github, for me it works as expected, both "start" and "build" scripts: https://github.com/dhilt/angular-7-ngx-ui-scroll-2. Please try it? There might be an important difference in the lib usage between your home.component.ts and the demo's app.component.ts.

**Comment by anasrbh** [comment]
@dhilt Thank you for taking the time to create the project on Github. You are right, it works well. And when I returned back to my project, I uninstalled and reinstalled ngx-ui-scroll and I no longer see the error related to instantiating the datasource.

However, I see errors when I try to use the adapter functions (relax, reload, check ...) : 



![Capture d’écran (28)](https://user-images.githubusercontent.com/82844585/115444223-96eb9800-a214-11eb-95a9-a8683dc3397e.png)



I think this is normal as the adapter is of type IAngularAdapter which extends Omit <IAdapter <Data>, keyof IReactiveOverride<Data>>. As Omit is not recognized by typescript versions lower than 3.5.1. This must have generated the error : 


![Capture d’écran (26)](https://user-images.githubusercontent.com/82844585/115444579-0792b480-a215-11eb-8d9b-e271a91ec930.png)


What do you think ?

**Comment by dhilt** [comment]
@anasrbh Well, I cleaned up the code from all incompatible TS expressions except "ambient context", which should be covered by skipLibCheck option. Please try ngx-ui-scroll v2.0.3 with skipLibCheck.

**Comment by anasrbh** [comment]
@dhilt Thank you so much ! I installed the new version and added skipLibCheck and it works fine.
I know it's just a temporary pseudo solution but it seems to be enough to make the virtual scroll work well in my case.

I close the ticket wishing you good luck for further improvements in this library.

Have a good day !
