### ISSUE TITLE
buffer page alignment

### ISSUE THREAD

**Issue by nanamicat** [dhilt/ngx-ui-scroll#266]
my server side api can only response messages by page
for example request page=1 then server will return 1..10

when ngx-ui-scroll requests 17..26, I have to 2 requests server for 11..20 and 21..30 then filter back to return.
could ngx-ui-scroll support to always request `minIndex + bufferSize * integer` ?

**Comment by dhilt** [comment]
@nanamicat Scroller requests as many items as needed to fill the [Viewport](https://github.com/dhilt/vscroll/wiki/Viewport) with outlets. What behaviour you'd expect if the Scroller needs exactly 17..26 items? If your API provides `((N-1)*10+1)..(N*10)` items per request (where N is a natural number), then there will two requests anyway (for N = 2 and 3). Am I missing something?

The recommended way to do it is shown in [this demo](https://dhilt.github.io/ngx-ui-scroll/#/datasource#pages) (Comp. async tab). The approach can be powered with [cache](https://github.com/dhilt/ngx-ui-scroll/wiki/Cache).

**Comment by nanamicat** [comment]
> Scroller requests as many items as needed to fill the [Viewport](https://github.com/dhilt/vscroll/wiki/Viewport) with outlets. 

What is `BufferSize` ? I see it always request that size of items, even if not all of them in viewport. this pre-loading part could be alignment.

**Comment by nanamicat** [comment]
or maybe I should set BufferSize to 1 ?

**Comment by dhilt** [comment]
@nanamicat `bufferSize` is a minimal number of items the Scroller requests per single `Datasource.get` call. For example, if the Scroller needs 9 items to complete the view and `bufferSize` = 15, then it will request 15 items. The rest 6 items will be rendered to expand one of the [outlets](https://github.com/dhilt/vscroll/wiki/Viewport). Please also refer to [bufferSize-demo](https://dhilt.github.io/ngx-ui-scroll/#/settings#buffer-size). I'd agree, naming is not perfect, this is historical matter...

**Comment by nanamicat** [comment]
> if the Scroller needs 9 items to complete the view and `bufferSize` = 15, then it will request 15 items. The rest 6 items will be rendered to expand one of the [outlets](https://github.com/dhilt/vscroll/wiki/Viewport). 

here is the page alignment point.

when scroller need 17..19, if request 17..26, it need to process a more page. 
if request 11..20, only exact need (to view and to fill buffer) wiil be requested. no waste.

**Comment by dhilt** [comment]
👍 Have we answered all the questions?

**Comment by nanamicat** [comment]
well the main problem is page alignment.
currently scroller will request some extra data not in viewport to fill buffer.
and server also return extra data for page.

if these there two extra data be alignment, could improve performance.

**Comment by dhilt** [comment]
@nanamicat That's how it works. In order to reduce extra data you may also play with [padding setting](https://dhilt.github.io/ngx-ui-scroll/#/settings#padding). By reducing the "padding" value, you tell the Scroller that you want the Viewport outlets to be smaller. This will lead to less data requests at a static moment, but may lead to more requests during scrolling. And the lib user needs to decide which combination of settings will be the most appropriate in this or that case.
