### ISSUE TITLE
Expose Settings interface as part of the public api

### ISSUE THREAD

**Issue by MadsBuchmann** [dhilt/ngx-ui-scroll#271]
Hi! 👋

I would like for the `Settings` interface used for the `IDataSource.settings` to be exposed as part of the public api. 

**Use case )**

In [Kirby design-system](https://github.com/kirbydesign/designsystem) we've extended our list component `kirby-list` with an opt-in option for virtual scrolling  by wrapping ngx-ui-scroll. 

The consumers of this component are able to pass settings for virtual via a `virtualScrollSettings` input property, like so: 

```javascript
<kirby-list [useVirtualScroll]='true' [virtualScrollSettings]={...}>
</kirby-list>
```

We want `virtualScrollSettings` to be strongly typed such that consumers of Kirby get type checking for this input property. 

**Current solution )**
Our current solution is to directly import the interface from `vscroll` and re-export this. We do not think is a very 'pretty' solution as it feels a bit _hacky_...

```javascript
import { Settings as VirtualScrollerSettings } from 'vscroll/dist/typings/interfaces/settings';

export { VirtualScrollerSettings };
```

**Comment by dhilt** [comment]
@MadsBuchmann Ok, let me look at this... 

I would suggest the following appoarch instead of importing Settings from vsroll/dist:

```ts
import { IDatasource, Workflow } from 'vscroll';

type DatasourceSettings = IDatasource['settings'];
type ScrollerSettings = Workflow['scroller']['settings'];
```

Not sure if you might need `ScrollerSettings` as it gives [all settings](https://github.com/dhilt/vscroll/blob/v1.0.0/src/classes/settings.ts#L6) (user, dev, internal) of the end Datasource entity using by the Scroller. `DatasourceSettings` type should be enough, I guess, it should be the same as your `VirtualScrollerSettings `.

**Comment by MadsBuchmann** [comment]
@dhilt Thank you for taking the time to look at it! 😄

Will try out with `IDatasource['settings']` - as it makes us dependent on the public api of `vscroll` instead of importing directly from the `dist` folder.

I will make sure to report back how it goes and close this issue if it works out!

**Comment by dhilt** [comment]
@MadsBuchmann By the way, it is possible to use ngx-ui-scroll `IDatasource` as well:

```ts
import { IDatasource } from 'ngx-ui-scroll';

type DatasourceSettings = IDatasource['settings'];
```

ngx-ui-scroll  and vscroll `IDatasource` entities have different 'adapter' properties (vscroll doesn't deal with RxJs), while 'settings' props are identical.

**Comment by MadsBuchmann** [comment]
We opted for using `IDatasource['settings']` as you proposed. 

Thanks you for the help - it's much appreciated!
