### ISSUE TITLE
HTML element is not defined

### ISSUE THREAD

**Issue by gaoyajiang** [dhilt/ngx-ui-scroll#275]
When I use the interface adapter.insert  to insert elements 。 Remind me：Error: HTML element is not defined。

**Comment by dhilt** [comment]
@gaoyajiang It is hard to get what happened, the best option for me to help you would be to provide a runnable demo on stackblitz (by forking [this demo](https://stackblitz.com/edit/ngx-ui-scroll-append-async) for example). If you could spend some time and push the repro on stackblitz, I will take a look and suggest a fix shortly.
