### ISSUE TITLE
Memory leak when using Datasource class instance 

### ISSUE THREAD

**Issue by markushall** [dhilt/ngx-ui-scroll#276]
First of all, thanks for all the hard work you are putting into this project. There are not many virtual scrolling solutions out there that supports variable size items, so this is highly appreciated.

I think I have stumbled upon a bit of a problem though. When I use a `Datasource` class instance as the datasource of a list and then remove the list using `*ngIf`, the library seems to be retaining both memory and DOM nodes. If I use an `IDatasource` object literal as the datasource instead, this leak does not happen.

Here is a Stackblitz to illustrate what I mean: https://stackblitz.com/edit/angular-ngx-ui-scroll-memory-leak?file=src/app/sample-table/sample-table.component.ts

Try toggling the lists on and off a few times using the buttons, while keeping an eye on the performance monitor (if you are using chrome). The left one does not leak, the right hand one does.

**Comment by dhilt** [comment]
Hi @markushall! This is an important area, but looks like I can't see the issue and would like to ask you to help me with it. 

My steps are as follows:

 - collect garbage
 - run profiler (and take snapshot 1)
 - show / hide the right viewport for 5 times
 - collect garbage
 - stop profiler (and take snapshot 2)

**First**, the performance tab (profiler):

<img width="667" alt="Screenshot 2021-06-29 at 22 28 14" src="https://user-images.githubusercontent.com/4365660/123856065-52256100-d929-11eb-8aca-40f423b086c2.png">

GC releases almost 100% of resources (except some memory, but this is unrelated, see below).

**Second**, the memory heap difference (snapshots):

<img width="688" alt="Screenshot 2021-06-29 at 22 30 19" src="https://user-images.githubusercontent.com/4365660/123856353-a9c3cc80-d929-11eb-9bfc-2cacccee0ccc.png">

"Delta" is zero for all html-related stuff. There are few non-zero "deltas", but drastically small and may relate to stackblitz rather than to ngx-ui-scroll (though I would not state this; anyway it is negligible). Where am I going wrong? If I'm missing something...

**Comment by markushall** [comment]
Hi,

Thanks for the quick response!

I have now tried this on four different machines and I still get the same result. The machines have the following setup:

Windows 10 Enterprise
18363.1621
Chrome: 91.0.4472.114

Windows Server 2019
Chrome: 91.0.4472.124

MacOS Catalina 10.15.7
Chrome: Version 91.0.4472.114 (Official Build) (x86_64)

MacOS Big Sur 11.2
Chrome: Version 91.0.4472.114 (Official Build) (x86_64)

Perhaps you already did this, but in case not, try running this in incognito mode with third party cookies allowed. Using this direct link also gets rid of most Stackblitz noise (same as clicking "Open in New Window" from within Stackblitz editor): https://angular-ngx-ui-scroll-memory-leak.stackblitz.io/

Following your steps I get this result on the Performance tab:
![image](https://user-images.githubusercontent.com/970037/123939808-d5ca6680-d998-11eb-821e-6cb010a34fc1.png)

Edit: Looking more at the performance tab figures I think I confused low/high with start/end. However, if we go with 100 iterations instead of 5 the memory increase is visible (see post below).

Heap ~~at start~~ low: 44.1 MB
Heap ~~at end~~ high: 46.1MB

DOM nodes ~~at start~~ low: 51
DOM nodes ~~at end~~ high: 621

For me the memory snapshot comparison shows an increase of these guys (which may have to do with me showing/hiding the right list five times):
![image](https://user-images.githubusercontent.com/970037/123940550-951f1d00-d999-11eb-80c0-54f327840f09.png)

Continued:
![image](https://user-images.githubusercontent.com/970037/123940820-d6173180-d999-11eb-8ee1-dca7bf8860c8.png)

Thanks for looking into this. Let me know if I can help out in any other way.

**Comment by markushall** [comment]
Following the same procedure as before, but with 100 show/hide iterations, the numbers become more visible.

![image](https://user-images.githubusercontent.com/970037/123960692-e33f1b00-d9af-11eb-9c8d-7960d35210af.png)

Memory snapshots:
![image](https://user-images.githubusercontent.com/970037/123960780-01a51680-d9b0-11eb-87be-a468d22c7be6.png)
Continued:
![image](https://user-images.githubusercontent.com/970037/123960863-15e91380-d9b0-11eb-8dd3-e564fb739539.png)

**Comment by dhilt** [comment]
@markushall Yes, now I clearly see it. It's interesting, why the same repro did not work for me yesterday... Anyway, I'm starting a research, great thanks!

**Comment by dhilt** [comment]
I'm close to fixing this.

**Comment by dhilt** [comment]
@markushall ngx-ui-scroll v2.2.0-beta is on npm, it contains fix for memory leak. I'm going to spend some time for clean up and refactoring, but v2.2.0-beta should work properly, could you try it?

**Comment by markushall** [comment]
Great news! I have tried it out at the updated https://stackblitz.com/edit/angular-ngx-ui-scroll-memory-leak-v220-beta?file=src/app/sample-table/sample-table.component.ts and I can confirm that both memory and DOM nodes are now returned properly when the scroller is `*ngIf`ed away.

One problem though, is that now in the `IDatasource` variant to the left, we get the following error on the console when clicking the toggle button twice (to hide it):

UiScrollComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: this.datasource.reset is not a function
    at UiScrollComponent.ngOnDestroy (ui-scroll.component.ts:66)
    at callProviderLifecycles (provider.ts:576)
    at callElementProvidersLifecycles (provider.ts:542)
    at callLifecycleHooksChildrenFirst (provider.ts:530)
    at destroyView (view.ts:524)
    at callViewAction (view.ts:646)
    at execEmbeddedViewsAction (view.ts:593)
    at destroyView (view.ts:522)
    at callWithDebugContext (services.ts:641)
    at Object.debugDestroyView [as destroyView] (services.ts:359)

This is not present in the first Stackblitz so I suspect it may be related to the fix.

**Comment by dhilt** [comment]
@markushall I'm happy that you looked into this! I added appropriate spec, pushed a fix and released a new interim version of ngx-ui-scroll (v2.2.0-beta.1)

**Comment by dhilt** [comment]
ngx-ui-scroll v2.2.0 is released

**Comment by markushall** [comment]
After running the same Stackblitz with ngx-ui-scroll updated to v2.2.0 I can confirm that neither the memory leak nor the console error message mentioned above is present anymore. Thanks for fixing this! :tada:

**Comment by dhilt** [comment]
It was great, thanks!
