### ISSUE TITLE
Fast scrolling white screen， override scroll bar

### ISSUE THREAD

**Issue by gaoyajiang** [dhilt/ngx-ui-scroll#278]
I have two questions now：
1. When I quickly drag the scroll bar, there will be a temporary white screen.emmm.Is there any way to display an empty DOM, as long as the screen is not white
2. For example, I have 2000 items，but the initial length of the scroll bar is not 2000 items, as roll, it will shorten. Is there any way to rewrite the scroll bar to match the number of items
thank you

**Comment by gaoyajiang** [comment]
https://stackblitz.com/edit/ngx-ui-scroll-1-7-0-angular-10-r3pnkq?file=src%2Fapp%2Fapp.component.ts  This is demo，you can quickly drag the scroll bar.

**Comment by gaoyajiang** [comment]
https://user-images.githubusercontent.com/53201532/125590701-28335fdb-6c19-4de2-9f17-9f530b2f6829.MP4

**Comment by dhilt** [comment]
@gaoyajiang I believe you are talking about [maxIndex setting](https://dhilt.github.io/ngx-ui-scroll/#/settings#min-max-indexes). If the height of the item is fixed, it should 100% satisfy your request. If there are items of different heights, then the result scrollbar params will be approximate, and in this case I would also advise to take a look at the [sizeStrategy setting](https://dhilt.github.io/ngx-ui-scroll/#/settings#different-item-heights).
