### ISSUE TITLE
Explicitely state the EOF for the UiScroll?

### ISSUE THREAD

**Issue by taujoey** [dhilt/ngx-ui-scroll#281]
Hi,
In short, I have a use-case, where i would like to Explicitely tell the UiScroll, when to stop querying for more data

It is all related to this sentence from the main user guide:
"Empty result (or result which length is less than count) is being treated as the edge of the dataset (eof/bof), and no further requests for preceding/tailing items will be issued."

In details, here are 2 examples, 1 where i wanna send out another query after EOF, and 1 where i dont want to send out another query before EOF:

1. use case example:
My app makes a query towards the backend, which, let's say, triggers a 'trivial' search (string operator= in c++) in the backend in a huuuuge text file. Let's say i set "count" to 60 items, and my search in the backend resulted in 55 items only. BUT :) This is only the 'first' search, the second search starts after this, but it is based on, let's say regex, which takes much longer to perform. So i send back the first 55 result (which the user wants to see quickly), the frontend shows these 'trivial' search results, and now the UiScroll got less than 'count' items, so it treats this result as EOF. But after resolving those 55 for the UiScroll, I would like that it performs another 'get' call, so it can get the additional search results too later on (in the backend the logic for matching this second 'get' is handled). The tricky part is the index, i know.. I think it should query from the 56. item, and not the 60. obviously, but i dont know how much chaos it would mean inside the UiScroll

2. use case example:
I have a card layout based on this issue: https://github.com/dhilt/ngx-ui-scroll/issues/267
i have groups of 10 items (so 'count' is 6 in the 'get' method, and i multiply it up by 10 to query 60 items from the backend, and when that arrives, i use the double ngfor-s to present them in 6 lines/groups), and the backend sends back 55 items --> which is 6 groups. Let's say now that in the backend there are no more items, search results, anything to send back, this is the end. BUT the UiScroll gets back 'count' groups, so it will send out another 'get' query unnecessarily, because it does not treat this as EOF currently.

So somehow during every 'resolve' i wanna tell the UiScroll that i want it to continue (or not) to query the backend for more data.

Personal note: I'm a c++ programmer, not frontend :) If this is a totally stupid approach, please tell me, and suggest a better one please :). I saw an issue, where the business logic could append stuff manually after the currently shown items (basically write logic to handle the case, when (result < expected), but i feel like that solution is somehow out of the natural flow of the 'calling 'get' method until necessary' functionality. And also in the 1. use-case, the regex could potentially have hundreds of results, so it would need many more get calls to get all the items from the backend.

Thanks in advance :)

**Comment by dhilt** [comment]
@taujoey The first case, I believe, can be handled by the Adapter.append API ([demo1](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend), [demo2](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend-sync)). This is how I see it:

 1. Client App has a sort of server data Cache, which is empty on start.
 2. Inside `Datasource.get` method you check if the requested (by index and count) items are available via Cache. If yes, resolve them via `success` callback immediately. If no, perform the Request to Server, save the result in Cache and then resolve. Partial availability should be handled too as an async merge of already cached data and data that is received by Request.
 3. The App should know if the Request has "double" nature (60 items are split into 55 and 5), and it should be possible to run some logic when the second part comes. There, at the appropriate time, the `Adapter.append` method should run along with caching. `Adapter.append` adds items even when EOF is reached, it shifts the max index. But you should save it in Cache carefully, for these new items should be available via `Datasource.get` on regular scroll (p.2).

So the idea is to decouple the regular client data flow from the irregular server one. When the Client gets a new portion of data in some irregular way, it appends this data to the regular Cache and a) renders it if EOF is reached, or b) virtualize it if a user scrolled up and there is no EOF. Use `Adapter.append({ items, eof: true })` for this. 

The implementation of the `Datasource.get` method could be very complicated, this "hook" allows to do low-level things and control the Scroller. For example, speaking of you second case, you may conditionally force the EOF situation by calling `Adapter.fix({ maxIndex: myIndex })` if you know that `myIndex` is the last index (as it was done in [this demo](https://stackblitz.com/edit/ngx-ui-scroll-end-of-results-demo-forked)).

**Comment by taujoey** [comment]
Thanks, I'll try out your suggestions!

**Comment by taujoey** [comment]
Hi, 
I tried your suggestions, here's what i found for my 1st use case (2nd use case seems trivial with the adapter.fix methodcall):

(NOTE: I have the grouping layer over the items because of the card layout, but it does not effect the 'eof' state i guess)

Eof not reached: The very first query gets back the needed 'count' of items from the backend, and i resolve them (so no eof is reached), and after that i append more items, the scroller does not render them, but after i scroll down, they appear --> exactly what you suggested, the scroller fetches them from my own cache very well.

Eof reached: Now i limit my first query's result (imitate the 'not enough result found' case) to let's just say 9 items (count is 10, so eof is reached), I resolve it, so the scroller renders the 9 items. After this I still can append to the list, but what i append now renders immediatelly, so when i scroll down, the items are already there, and the scroller will never call the 'get' method ever again, no matter what i do (the cache is consistent with the state, but the 'get 'method never gets called, so the cache is never even touched again..)

Why does this happen? What am I missing here?

**Comment by dhilt** [comment]
@taujoey When you do append and EOF is true, then EOF will remain true. The maxIndex value ([Buffer.absMaxIndex](https://github.com/dhilt/vscroll/blob/v1.2.0/src/classes/buffer.ts#L105)) shifts in accordance with the appended set length, but EOF value is not changed. The Scroller treats this maxIndex value as a datasource boundary in this case, and if it is less than Infinity, further requests are prevented. Moreover, if the datasource is small enough and EOF/BOF are both true at the same moment, then the Datasource.get method will not be called at all. This is by design.

If you know that there is some additional data and it is limited, you may request it and append it in the same manner: expand the datasource at the App Component level and push the data to Scroller via `Adapter.append`.

If you know that there is some more data and it is not limited, then I'd recommend to reconsider the approach itself. You should not fall into EOF situation if there are some data that could be requested by user action. Maybe it would be a good idea to reset EOF via `Adapter.fix({ maxIndex: Infinity })`... From the other hand, you may request for data reactively: if EOF becomes true, do a request and append the result:

```ts
this.datasource.adapter.eof$.subscribe(eof => {
  if (eof) {
    this.requestAndAppend();
  }
})
```

There are too many ways, many of them look like workarounds, while there is a chance that we missed something in the very beginning and it might be better to fix the initial architecture plan. Maybe you can create demo to do more solid and substantive research ([this stackblitz sample](https://stackblitz.com/edit/ngx-ui-scroll-append-async) seems a good start point)?
