### ISSUE TITLE
TypeError: Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by IgorVNC** [dhilt/ngx-ui-scroll#291]
After upgraded to 2.1.0 (and then to 2.2.2) we started facing sometimes the following error 

"TypeError: Cannot read property 'log' of undefined"

It's not clear what exactly leads to it,
we have a chat app, and it happens when switching chats.

We are doing adapter.reset() when switching chats.

![Screenshot 2021-09-22 at 15 00 18](https://user-images.githubusercontent.com/57942649/134343135-c06ffeac-e547-4efa-be16-94d5368f7f61.png)

and this is where it happens (seems it's inside relaxUnchained)

![Screenshot 2021-09-22 at 15 00 42](https://user-images.githubusercontent.com/57942649/134343170-32a896f4-a21a-42d8-a266-150503c7bcab.png)

**Comment by dhilt** [comment]
@IgorVNC 

1. Which version did you use before 2.1.0?
2. Can you attach also [dev log](https://github.com/dhilt/vscroll/wiki/Dev-Log) (with `logProcessRun` set to true)? Even 2 logs: one for good run with the old version, and one for bad run with new.
3. The best option would be to provide runnable demo (the latest stackblitz stub could be taken [from here](https://stackblitz.com/edit/ngx-ui-scroll-2-angular-12)). If you can do it, logs are not necessary.

I started investigation, but have no results for now. It looks like a race condition multiplied by a lost context problem: some outdated processes continue after reset and fall into conflict. I understand, it may be quite difficult to get minimal repro, but the end goal is to create a test specification.

Btw, `relaxUnchained`, the method where the error raises, was developed during the work on the issue #220, and you are certainly familiar with it. So the story goes on and I hope we resolve it as well as before.
