### ISSUE TITLE
scrollbar appears and disappears when scrolling

### ISSUE THREAD

**Issue by elira** [dhilt/ngx-ui-scroll#293]
Hi,

Very nice project. I'm finding it extremely useful.
There is a small issue I'm not sure how to resolve, that of a scroll bar appearing and then disappearing at certain points of scrolling (  not the viewport scroll bar ).
Am I doing something wrong?

Thanks.

**Comment by dhilt** [comment]
@elira Hello! Any chance to make a repro? Maybe stackblitz (fork [this demo](https://stackblitz.com/edit/ngx-ui-scroll-2-angular-12-issue-288) or at least gif record?

**Comment by elira** [comment]
Thanks for the reply @dhilt .I was not able to recreate the issue in stackblitz. Here is a recording 
![test - Google Chrome 2021-09-30 15-17-22](https://user-images.githubusercontent.com/405275/135454120-68a3e6c9-8366-405b-9352-e85af89db166.gif)
Notice the flashing scrollbar on the right.

**Comment by elira** [comment]
I found the issue.
When used inside `ngx-smart-modal` the modal has an background element when open.  It  has a fixed position with `top: 0, bottom: 0, ... `
For some reason it adds a scrollbar as the `uiscroller` is being recalculated. Adding a `overflow:  hidden` to this element fixed the issue.

**Comment by elira** [comment]
Maybe this can be useful for someone trying to use `ngx-smart-modal` together with `ngx-ui-scroller`

**Comment by dhilt** [comment]
Great!
