### ISSUE TITLE
Fix updater not working

### ISSUE THREAD

**Issue by i7d3v3l0p3r** [dhilt/ngx-ui-scroll#295]
Fix-updater method not working when try to use. Example from [docs](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater) not works too (partially)
![image](https://user-images.githubusercontent.com/56602205/139438888-71b39423-3f64-43a0-b52a-3e935c5db9e4.png)

**Comment by i7d3v3l0p3r** [comment]
In my case error corresponds with using rest parameter in `updater` method

![image](https://user-images.githubusercontent.com/56602205/139441828-e19a1e46-defa-433e-a0ec-63b7fd2a7bae.png)

**Comment by dhilt** [comment]
@i7d3v3l0p3r  `Adapter.fix({ updater })` wants a function with 1 or 2 arguments. It uses [Function.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) under the hood. Looks like the rest syntax don't work with it. The demo has more obvious issue:

https://github.com/dhilt/ngx-ui-scroll/blob/977bb071de25e163a10786399994eed07dade1d0/demo/app/samples/experimental/adapter-fix-updater.component.ts#L111-L113

The empty object argument disappeared with the [eslint refactoring](https://github.com/dhilt/ngx-ui-scroll/commit/d91c527980b3be698993241847b7028dd14b32a6#diff-65f087d9a3da39bc5888b9176d392ebac86049f794d011bdc829943ef83ac8e5L110). I fixed it by adding _ argument.

Perhaps it is not a bad idea to remove this requirement, especially taking into account the API is experimental...

**Comment by i7d3v3l0p3r** [comment]
Rest syntax under the hood is use `arguments` (after babel transformation), maybe it can [help](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAawKbIBQDocCdUDOUAlIgN4BQiiECBcANqlg3AOYb5HEUC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.15.8&externalPlugins=&assumptions=%7B%7D)

**Comment by dhilt** [comment]
Even if it is possible to go around the "rest" problem in es5-compiled distributive, there is also esm6 distributive keeping "rest" as is. No, the Function.length approach is not good there... Thanks for the report anyway! The demo is fixed, the recommendation is to use explicit arguments, and I'll consider another validation for function inputs, less strict.
