### ISSUE TITLE
Why is the get() method called twice at startup?

### ISSUE THREAD

**Issue by sawa-ko** [dhilt/ngx-ui-scroll#296]
I have noticed that the get() method is called twice at startup, I am using the demo code with infinite scroll and that happens.

This is a problem for me because it calls the api twice at startup when it should be only 1. I don't know if I am doing something wrong.

I am making an infinite scroll for a chat room component.

```ts
  ngOnInit(): void {
    this.datasource = new Datasource({
      get: (_, __, success) => {
        this._apiService
          .GetMessages(this.channelId!)
          .pipe(
            filter((r) => r.data.GetMessages !== undefined),
            first(),
          )
          .subscribe({
            next: (r) => {
              success(r.data.GetMessages);
            },
          });
      },
      settings: {
        bufferSize: 50,
        maxIndex: 50,
        startIndex: 50,
        infinite: true,
      },
    });
  }
```

**Comment by dhilt** [comment]
@kaname-png You may add dev logging to get detailed picture of what's going on, please refer to this doc: https://github.com/dhilt/vscroll/wiki/Dev-Log. Basically, the initial run is accompanied by 2 `Datasource.get` calls: one for fetching the items in forward direction and one for fetching the items in backward direction (if this is not prohibited by settings). Then the Scroller checks if the viewport is filled, and if not, it makes another `Datasource.get` call. Then checks again... Dev-log can clearly show the flow. If you will still at a loss, attach your log to the next comment, I'll see and explain.

Btw, your Datasource implementation looks quite unusual. First, you may, I believe, omit the subscribe-success hookup, like
```js
      get: (index, count) => 
        this._apiService
          .GetMessages(this.channelId)
          .pipe(
            filter(r => !!r.data.GetMessages),
            first(),
            map(r => r.data.GetMessages)
          )
      },
```
And second, where are the logic related to index-count? How does the api service know which items to return?

**Comment by sawa-ko** [comment]
@dhilt Thanks for the quick reply.
My api gets the messages according to the last message id obtained, for example, if the last message has the ID 123, then the api will get the messages before that ID. The messages are sorted in descending order by creation date.

And my problem is that, for example, I get 50 items, but the get() method is called again and pushes another 50 items, and then the list now has 100 items and stays in the middle even though I select it to start at index 50, which is the maximum.

**Comment by dhilt** [comment]
Well. Attach dev-logs here, or (which is better) fork [this demo](https://stackblitz.com/edit/ngx-ui-scroll-2-angular-12) and update it with a repro of your issue.

**Comment by sawa-ko** [comment]
Log: https://pastebin.com/mY7mTE4j


https://user-images.githubusercontent.com/56084970/140595732-51d3ab72-438d-4edb-b598-f710c64666d4.mp4

**Comment by dhilt** [comment]
Log says, we have inconsistent index flow. For example

> vscroll.esm5.js:3075 going to fetch 1 items started from index 50  // time: 165
> vscroll.esm5.js:3075 fire preFetch "next" {process: 'init'}  // time: 166
> vscroll.esm5.js:3075 run fetch  // time: 166
> vscroll.esm5.js:3075 resolved 50 items (index = 50, count = 1)  // time: 502

Wanted 1, got 50. That's because the `Datasource.get` ignores the index-count params. The README doc is strict:

> Datasource.get method must provide an array of count data-items started from index position. If there are no items within given range [index; index + count - 1], an empty array has to be passed. 

So you need to replace your DS implementation with something like

```js
  new Datasource({
      get: (index, count) => 
        this.apiService.getMessagesByIndex(this.channelId, index, count)
      }
  })
```
and oblige the API service to respond with exact portion of data-items, mapped as the UI needs. Scroller perfectly maintains the indexes under the hood and knows how many items are required at a given moment, you just need to give him what he wants when he calls the `get` method. And he wants "count" items started from "index" position.

**Comment by kaname-png** [comment]
I understand, one more doubt. When obtaining the new data, must it be new data in addition to the data already obtained?
For example, if I received 1,2,3 when obtaining more data should be 4,5,6 and not 1,2,3,4,5,6?

**Comment by sawa-ko** [comment]
Thanks

**Comment by dhilt** [comment]
Glad to help! All calculations, concatenations, clipping, etc. take place inside Scroller. Just provide him with an index-count subset of external data when he asks for it, and let him do his work 😁
