### ISSUE TITLE
Test infrastructure

### ISSUE THREAD

**Issue by dhilt** [dhilt/ngx-ui-scroll#3]
Need to develop test infrastructure and provide first tests.

**Comment by dhilt** [comment]
@babsley  Первый тест должен просто рендерить компоненту в заданном viewport и проверять, что было, скажем, 2 вызова datasource.get вниз и 1 вызов datasource.get наверх. Можно проверить итоговый html, что у нас нужное количество строк и их содержание соответствует ожидаемому.

**Comment by ndovnar** [comment]
@dhilt Решил сразу приступить к написанию тестов, но так как я их никогда не писал, нужно изучить материал и т.д. Решил держать тебя вкурсе, о том чем я занимаюсь и надеюсь обучение в процессе не будет сильно тормозить работу.

**Comment by dhilt** [comment]
@babsley Окей! я со времен первого ангуляра не занимался тестированием front end (недавно только начал получать опыт с Реактом) и я не могу подсказать "правильное" направление, но кроме прочего, нам обязательно надо иметь возможность отлаживать тест в реальном браузере, видеть DOM, шариться по callstack...

**Comment by dhilt** [comment]
Done by PR https://github.com/dhilt/ngx-ui-scroll/pull/14.
