### ISSUE TITLE
Issue during integration Module not found

### ISSUE THREAD

**Issue by rakeshdausa** [dhilt/ngx-ui-scroll#30]
Hey,
I am using this for my feed screen list as suggested by @dhilt,  But after integrating I got this error. `ERROR in ./node_modules/ngx-ui-scroll/esm5/ngx-ui-scroll.js
Module not found: Error: Can't resolve 'lodash.throttle' in 'D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\esm5'
resolve 'lodash.throttle' in 'D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\esm5'
  Parsed request is a module
  using description file: D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\package.json (relative path: ./esm5)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\package.json (relative path: ./esm5)
    resolve as module
      D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\esm5\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\src\main\pwa\node_modules\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\src\main\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\src\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      looking for modules in D:\PlownsWeb\src\main\pwa\node_modules
        using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules)
          using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules/lodash.throttle)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.js doesn't exist
            as directory
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle doesn't exist
      looking for modules in D:\PlownsWeb\src\main\pwa\node_modules
        using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules)
          using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules/lodash.throttle)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.js doesn't exist
            as directory
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle doesn't exist
      looking for modules in D:\PlownsWeb\src\main\pwa\src
        using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src)
          using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src/lodash.throttle)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle.js doesn't exist
            as directory
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle doesn't exist
      looking for modules in D:\PlownsWeb\src\main\pwa\src
        using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src)
          using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src/lodash.throttle)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle.js doesn't exist
            as directory
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle doesn't exist
[D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\esm5\node_modules]
[D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\node_modules]
[D:\PlownsWeb\src\main\pwa\node_modules\node_modules]
[D:\PlownsWeb\src\main\node_modules]
[D:\PlownsWeb\src\node_modules]
[D:\PlownsWeb\node_modules]
[D:\node_modules]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.ts]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.js]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.ts]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.js]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle.ts]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle.js]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle.ts]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle.js]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle]
 @ ./node_modules/ngx-ui-scroll/esm5/ngx-ui-scroll.js 784:15-41
 @ ./src/app/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in D:/PlownsWeb/src/main/pwa/node_modules/ngx-ui-scroll/src/component/interfaces/direction.d.ts (2,15): In ambient enum decl
arations member initializer must be constant expression.
ERROR in D:/PlownsWeb/src/main/pwa/node_modules/ngx-ui-scroll/src/component/interfaces/direction.d.ts (3,16): In ambient enum decl
arations member initializer must be constant expression.
ERROR in Error: Metadata version mismatch for module D:/PlownsWeb/src/main/pwa/node_modules/ngx-ui-scroll/ngx-ui-scroll.d.ts, foun
d version 4, expected 3, resolving symbol SharedModule in D:/PlownsWeb/src/main/pwa/src/app/shared.module.ts, resolving symbol Sha
redModule in D:/PlownsWeb/src/main/pwa/src/app/shared.module.ts
    at syntaxError (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26
)
    at D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10
)
    at Object.listLazyRoutesOfModule (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_
api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (D:\PlownsWeb\src\main\pwa\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\PlownsWeb\src\main\pwa\node_modules\@ngtools\webpack\src\plugin.j
s:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

webpack: Failed to compile.
^CTerminate batch job (Y/N)? y

D:\PlownsWeb\src\main\pwa>ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-03-27T04:54:46.836Z
Hash: 070901e42f20166c02d1
Time: 28169ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.67 MB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 1.3 MB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 295 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 18 MB [initial] [rendered]

ERROR in ./node_modules/ngx-ui-scroll/esm5/ngx-ui-scroll.js
Module not found: Error: Can't resolve 'lodash.throttle' in 'D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\esm5'
resolve 'lodash.throttle' in 'D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\esm5'
  Parsed request is a module
  using description file: D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\package.json (relative path: ./esm5)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\package.json (relative path: ./esm5)
    resolve as module
      D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\esm5\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\src\main\pwa\node_modules\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\src\main\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\src\node_modules doesn't exist or is not a directory
      D:\PlownsWeb\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      looking for modules in D:\PlownsWeb\src\main\pwa\node_modules
        using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules)
          using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules/lodash.throttle)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.js doesn't exist
            as directory
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle doesn't exist
      looking for modules in D:\PlownsWeb\src\main\pwa\node_modules
        using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules)
          using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./node_modules/lodash.throttle)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.js doesn't exist
            as directory
              D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle doesn't exist
      looking for modules in D:\PlownsWeb\src\main\pwa\src
        using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src)
          using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src/lodash.throttle)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle.js doesn't exist
            as directory
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle doesn't exist
      looking for modules in D:\PlownsWeb\src\main\pwa\src
        using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src)
          using description file: D:\PlownsWeb\src\main\pwa\package.json (relative path: ./src/lodash.throttle)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle.js doesn't exist
            as directory
              D:\PlownsWeb\src\main\pwa\src\lodash.throttle doesn't exist
[D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\esm5\node_modules]
[D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\node_modules]
[D:\PlownsWeb\src\main\pwa\node_modules\node_modules]
[D:\PlownsWeb\src\main\node_modules]
[D:\PlownsWeb\src\node_modules]
[D:\PlownsWeb\node_modules]
[D:\node_modules]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.ts]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.js]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.ts]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle.js]
[D:\PlownsWeb\src\main\pwa\node_modules\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle.ts]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle.js]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle.ts]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle.js]
[D:\PlownsWeb\src\main\pwa\src\lodash.throttle]
 @ ./node_modules/ngx-ui-scroll/esm5/ngx-ui-scroll.js 784:15-41
 @ ./src/app/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in D:/PlownsWeb/src/main/pwa/node_modules/ngx-ui-scroll/src/component/interfaces/direction.d.ts (2,15): In ambient enum decl
arations member initializer must be constant expression.
ERROR in D:/PlownsWeb/src/main/pwa/node_modules/ngx-ui-scroll/src/component/interfaces/direction.d.ts (3,16): In ambient enum decl
arations member initializer must be constant expression.
ERROR in Error: Metadata version mismatch for module D:/PlownsWeb/src/main/pwa/node_modules/ngx-ui-scroll/ngx-ui-scroll.d.ts, foun
d version 4, expected 3, resolving symbol SharedModule in D:/PlownsWeb/src/main/pwa/src/app/shared.module.ts, resolving symbol Sha
redModule in D:/PlownsWeb/src/main/pwa/src/app/shared.module.ts
    at syntaxError (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26
)
    at D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10
)
    at Object.listLazyRoutesOfModule (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\PlownsWeb\src\main\pwa\node_modules\@angular\compiler-cli\src\ngtools_
api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (D:\PlownsWeb\src\main\pwa\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\PlownsWeb\src\main\pwa\node_modules\@ngtools\webpack\src\plugin.j
s:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

webpack: Failed to compile.`

**Comment by rakeshdausa** [comment]
After upgrading angular to 5.2.8 I am getting this error

ERROR in ./node_modules/ngx-ui-scroll/esm5/ngx-ui-scroll.js
Module not found: Error: Can't resolve 'lodash.throttle' in 'D:\PlownsWeb\src\main\pwa\node_modules\ngx-ui-scroll\esm5'

**Comment by dhilt** [comment]
@rakeshdausa Thanks for the issue! The problem has been fixed and the updated 0.0.2 version is available via npm.
