### ISSUE TITLE
How to update startIndex after reseting data source.

### ISSUE THREAD

**Issue by CRDEV00** [dhilt/ngx-ui-scroll#309]
### A couple of things to keep in mind.

- My component is getting data throughout Input()
- I got a property in my component that is storing the instance of  dataSource
`public dataSource: IDatasource;`
- In the constructor I'm initializing the dataSource, using 0 as `startIndex`.
```
  constructor(private route: ActivatedRoute) {
    this.dataSource = this.generateDataSource(0);
  }
```
- NgOnChanges hook is helping me to watch and restart the DataSource when data changes. I'm using `this.dataSource.adapter.reset();` with a new instance of DataSource with a new startIndex.
- So when data changes I call a function that returns a new instance of DataSource with a new startIndex

```
generateDataSource(startIndex: number): IDatasource {
    return new Datasource<IProviderItemHeight>({
      get: (index, count, success) => {
        const innerData: IProviderItemHeight[] = [];
        if (this.resultsWithHeight.length > 0) {
          const max = (index + count - 1) > this.resultsWithHeight.length ? this.resultsWithHeight.length : (index + count - 1);
          if (index >= 0 && index < this.resultsWithHeight.length) {
            for (let i = index; i <= max; i++) {
              innerData.push(this.resultsWithHeight[i]);
            }
            success(innerData);
          }
        }
        success(innerData);
      },
      settings: {
        startIndex,
        sizeStrategy: SizeStrategy.Average,
        bufferSize: 1
      }
    });
  }
```
I expect to see this item as the first one, instead it starts at the number I set in the constructor previously.

**Comment by dhilt** [comment]
@CRDEV00 In which way you call the Adapter.reset method? Basically, if the startIndex is the only thing that should change, I would expect it to be

```js
this.dataSource.adapter.reset({ settings: { startIndex } });
```

I mean, you don't need to re-instantiate the Datasource, the Scroller will do it for us. Though you can re-instantiate it manually, but you should pass the new settings object in this or that way via `reset`. I'm not sure, but looks like your App continue using the previous version of settings object after reset, which is possible in case you didn't pass the new version through the Adapter.reset argumets.

If this doesn't help, you may fork [this stackblitz demo](https://stackblitz.com/edit/ngx-ui-scroll-2-angular-12) and reproduce the problem with minimal necessary infrastructure from your project. I will take a look and suggest a fix.

**Comment by CRDEV00** [comment]
In the hook I got something like this... 

```Javascript
  async ngOnChanges(changes: SimpleChanges) {
    if (changes.results) {
        await this.dataSource.adapter.reset(this.generateDataSource());
    }
  }
```
 every time when I got a new array in my component though the input() I create a new dataSource... I'm note sure about this  approach to be honest, but it was the only way the remove all the data and create new...

**Comment by dhilt** [comment]
@CRDEV00 I don't see the startIndex argument in your `this.dataSource.adapter.reset(this.generateDataSource())` call. This way the `generateDataSource(startIndex: number)` method produces `undefined` when doing `{ settings: { startIndex } }`, which leads to fallback the value of startIndex to the default, which is 1. Also, I still believe that replicating the issue on the [stackblitz](https://stackblitz.com/edit/ngx-ui-scroll-2-angular-12) would be a better option for debugging.

**Comment by CRDEV00** [comment]
Thanks in advance, I've created this [demo](https://stackblitz.com/edit/ngx-ui-scroll-2-angular-12-jy7o5z?file=src%2Flist%2Flist.component.ts)..

**Comment by dhilt** [comment]
Great, thanks, will take a look soon!

**Comment by dhilt** [comment]
@CRDEV00 I'm ready to suggest a fix. During my investigation I found that the Scroller can't fix the position of the **host element**, which is the parent of the "ui-scroll"-attributed element (let's call it the **scroller element**). In your demo you have the app and the list components, and the host element is defined in the app component while the scroller element is defined in the list component. Basically, the host element should be the parent of the scroller element. That was not true in your demo: you assigned the "viewport" class not to the &lt;list&gt; element, but to its parent. And whait is not 100% clear for me is that if we assign the "viewport" class to the &lt;list&gt; element in the app component, then it will not work. I think it might relate to Angular components injection mechanism, I didn't investigate this branch. From this point I have 2 working solutions. 

1. Move the host element into the list component, and provide "viewport"-classed element inside the list template as the nearest parent of the scroller element:

https://stackblitz.com/edit/ngx-ui-scroll-2-angular-12-issue-309

2. Assign the over-parented host element explicitly via [viewportElement](https://dhilt.github.io/ngx-ui-scroll/#/experimental#viewportElement-setting) setting:

https://stackblitz.com/edit/ngx-ui-scroll-2-angular-12-issue-309-v2

**Comment by CRDEV00** [comment]
Cool ! Many thanks !  I'll definitely  implement it this way !
