### ISSUE TITLE
What is the best practice to update an item within the list without flashing?

### ISSUE THREAD

**Issue by CAIsoul** [dhilt/ngx-ui-scroll#311]
Currently, if I use update  method to do this, the list would 'flash'. I think it is doing a quick deletion and insertion which caused this flashing. Is there a better way to do this otherwise I might need to manually update the DOM.
Thanks!

**Comment by dhilt** [comment]
@CAIsoul Basically, the [Adapter.update](https://dhilt.github.io/ngx-ui-scroll/#/adapter#update) method is your friend when updating the virtual list elements manually. As well as Adapter.insert/remove/append/prepend/replace methods if they update buffered items (for they all use Adapter.update under hood, see [diagram](https://github.com/dhilt/vscroll/wiki/VScroll-Workflow)). The ngx-ui-scroll library does not re-use DOM elements and there is an async render process that runs 0-timeout in its [default implementation](https://github.com/dhilt/vscroll/blob/v1.5.0/src/classes/domRoutines.ts#L188); the rest is given to Angular. Perhaps this is the point of possible optimization...

There is also [Adapter.fix({ updater })](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater) API which is experimental and which provides low-level access to the data-items from the current Scroller's buffer. Calling the Adapter.fix method does not trigger the Scroller's inner loop and thus doesn't lead to render. It is synchronous and may give better performance and UX in particular cases. If you can afford to forget immutability, you may try it.

**Comment by CAIsoul** [comment]
@dhilt Got it, I will try this out, thanks.
