### ISSUE TITLE
Mouse wheel scrolling gets stuck on loading after updating Chrome (v102)

### ISSUE THREAD

**Issue by Kikimora124** [dhilt/ngx-ui-scroll#317]
Hi,
since one of the latest Chrome updates, i´ve noticed, that the mouse wheel scrolling, especially if you do it fast, gets stuck on loading new items. Only if you move the cursor a bit, it starts working again. This can be observed on your demo page. On other browsers this doesn't seem to occur. Might be a Chrome bug, just wanted to let you know. 

Thx

**Comment by dhilt** [comment]
Oh God... touch pad died as well
Thank you! Will try to investigate and raise the issue on the Chromium's end.

**Comment by dhilt** [comment]
Here we are: https://bugs.chromium.org/p/chromium/issues/detail?id=1330045&q=component%3ABlink%3EScroll.
They confirmed that this is a Chromium bug and fixed it in the next 104 release.
I downloaded Chrome Canary (105) and made sure that the issue if fixed.
So the suggestion is not to use Chrome 102 and switch to 104+.
