### ISSUE TITLE
Scroll position jumps/changes when new items are loaded in viewport

### ISSUE THREAD

**Issue by asifnkhan** [dhilt/ngx-ui-scroll#319]
Stackblitz: [https://stackblitz.com/edit/angular-ivy-ygqf4f](https://stackblitz.com/edit/angular-ivy-ygqf4f)
Please check in mobile view. Thanks.

Hi there. I am using your library for a PWA built using Ionic Framework. Thanks for your work.

Right now I am facing an annoying issue related to the scrolling of content. When a user is scrolling through the list, the scroll position jumps around because of loading/unloading of items in the viewport. The height of items in the list is not fixed and that is causing the viewport size to change.

Is there any way I can make sure the scroll position does not change? Thanks for your help.

**Comment by dhilt** [comment]
@asifnkhan First, thanks for the repro as it really saves time! 

After some shallow look I'm obliged to state that your problem does not relate to random heights: https://stackblitz.com/edit/angular-ivy-p5wmfm?file=src/app/hello.component.html. I would look more precisely but my current brief assumption is that we have margin collapse or another CSS issue. If you remove "my-6" class from what I left in my stackblitz fork, you'll see the jumping stopped.

DOM-related calculations are part of [Routines module](https://github.com/dhilt/vscroll#5-routines) and its default implementation is quite simple and may not cover some specific cases, like margin collapse. Need to investigate deeper.

**Comment by asifnkhan** [comment]
@dhilt Thanks for the help. Removing the margin CSS has worked and I am now using padding instead.

I would have never guessed that margin could be an issue. So, thanks a lot.
