### ISSUE TITLE
Different items heights

### ISSUE THREAD

**Issue by dhilt** [dhilt/ngx-ui-scroll#32]
Need to provide different items heights functionality (per https://github.com/dhilt/ngx-ui-scroll/issues/31#issuecomment-376780261).

Here is the demo that does not work properly in some cases: https://stackblitz.com/edit/angular-tfmcme?file=index.html.

**Comment by dhilt** [comment]
@rakeshdausa Could you please tell me what OS and what Browser version are you using? For me the stackblitz demo works fine on Win 10 Chrome v65.0.3325.181.

**Comment by rakeshdausa** [comment]
I am also using Google Chrome Version 65.0.3325.181 (Official Build) (64-bit) Windows 10.

**Comment by rakeshdausa** [comment]
It happens during scroll up and down multiple times.

**Comment by dhilt** [comment]
@rakeshdausa Oh, I was able to reproduce the problem, your video was very helpful. Currently I don't understand the mechanics of the bug and I need some time to minimize it. Thank you!

**Comment by dhilt** [comment]
@rakeshdausa Hi! I've just published v0.0.3-beta, it is available via npm. I think I fixed the issue though not all the tests are done (that's why it is beta). May I ask you to try v0.0.3-beta in your environment?

**Comment by dhilt** [comment]
Closed per ngx-ui-scroll v0.0.3 has been released.

**Comment by rakeshdausa** [comment]
Yes Its working fine. Thanks
