### ISSUE TITLE
Data loading is abnormal when scrolling up

### ISSUE THREAD

**Issue by coloz** [dhilt/ngx-ui-scroll#320]
I scroll halfway and then scrolling up, and the data cannot be loaded immediately.

this is demo:
http://s.diandeng.tech/t/1066

**Comment by dhilt** [comment]
@coloz Perhaps an indexes issue at the datasource.get level. I need a debuggable demo (with source code available) to sort this out. Could you please push it to stackblitz? here's the sample you may fork: https://stackblitz.com/edit/ngx-ui-scroll-3-angular-14?file=src%2Fapp%2Fapp.component.ts. 

Another option is to add [sourcemaps](https://webpack.js.org/configuration/devtool/) to your demo and turn on [scroller's debug mode](https://github.com/dhilt/vscroll/wiki/Dev-Log).

**Comment by coloz** [comment]
I try to reproduce this problem on stackblitz, but it didn't show up.
i add
```
devSettings: {
            debug: true,
            immediateLog: true,
 }
```
when scrolling up,log show:  
```
error: Can't set buffer items (loop 1-66-68)
```
http://s.diandeng.tech/t/1066  Updated

i guess this is the reason.  
how to solve this error？  
thanks for your help

**Comment by dhilt** [comment]
@coloz Yes, that clearly shows a mess with indexes. Now we need to debug the App code. I suppose the `Datasource.get` implementation is not well, but not sure. I'd like to see how it works live, and to make it possible you need to add sourcemaps to your demo or replicate the issue on stackblitz. An alternative would be to post your `Datasource.get` code here, but it might be not enough.

**Comment by coloz** [comment]
@dhilt  https://stackblitz.com/edit/ngx-ui-scroll-3-angular-14-da2jmc
thanks

**Comment by dhilt** [comment]
@coloz The first issue I found is that your `Datasource.get` call results in 1 extra item each time it is called. Perhaps you'll need to fix it in a way like

```js
.range(index, index + count - 1)
```

This is not the end, because I see jumping that should not be there...

**Comment by coloz** [comment]
@dhilt 
it‘s’ solved, thanks a lot
