### ISSUE TITLE
Nested cdkVirtualFor in cdk-virtual-scroll-viewport

### ISSUE THREAD

**Issue by kevalgw** [dhilt/ngx-ui-scroll#322]
Hi,

I want to use nested cdkVirtualFor in cdk-virtual-scroll-viewport 
I am getting the following error:

![image](https://user-images.githubusercontent.com/101707048/200794579-fb9ea28c-db58-4d1f-811d-9b22f7705d21.png)

Here is my code:

![image](https://user-images.githubusercontent.com/101707048/200794796-69e4a72b-a6fd-4d50-b516-4f75937d7424.png)

**Comment by dhilt** [comment]
Hello! Your issue relates to Angular CDK, so you need to go to https://github.com/angular/components/issues and open issue there.
