### ISSUE TITLE
Sluggish on iOS

### ISSUE THREAD

**Issue by muchbetterug** [dhilt/ngx-ui-scroll#324]
Hey!
People told me, that the scrolling on my site (https://www.***.de/aktivitaeten - sorry for the adultcontent!) is sluggish especially with iOS. 
Has anyone experienced similar problems? I use android and can't replicate it.

Big thanks! <3

**Comment by muchbetterug** [comment]
Oh! It seems that the DOM in the scroll elements is just to heavy. I heard that this test site runs smooth: https://www.***.de/scroll1

**Comment by dhilt** [comment]
@muchbetterug Thanks for using the lib! I've looked at your demo on my Mac's Chrome and didn't see any issues. Though it were only 25 rows... Anyway, if you realized that the problem is not with lib, then we can close this issue.

**Comment by muchbetterug** [comment]
Yes, thank you for this great lib! The problem was the complex DOM inside my scrolling elements.
