### ISSUE TITLE
Observable dataSource change (emission) does not update uiScroll list

### ISSUE THREAD

**Issue by dil-pkollar** [dhilt/ngx-ui-scroll#332]
You can use this [stackblitz ](https://stackblitz.com/edit/base-angular-12-app-x1j1xe) to reproduce the issue.

```
    "@angular/core": "12.0.0",
    "ngx-ui-scroll": "3.0.1",
    "vscroll": "^1.5.3",
```

Steps:
1. Click on filter button (this will not update the list)
2. Click on show (*ngIf) twice (this will update the list with the expected filtering)

Expected behaviour: observable emissions would update uiScroll list.

![filter](https://user-images.githubusercontent.com/96052348/223105728-82ed434e-ec99-4640-a9c0-c56fb3cb5a9e.gif)

**Comment by dhilt** [comment]
@dil-pkollar Thanks for using the lib! The point is the consistency between the App and the Scroller. The datasource (App level) is used by the VScroll engine only to retrieve part of the data that is needed for rendering at the moment when rendering is required. Therefore, the engine does not know if/when an external change occurs. It can be seen a sort of one-way relation:

```
Datasource (App)   <--    VScroll engine
```

It means you need to provide every datasource update manually at the App level using the Adapter methods:

```
Datasource (App)   <--   
                         VScroll engine
Datasource.Adapter  -->  
```

In your demo you want to filter out all `i%2` items. Thus, this should be divided into two parts, like as follows

```js
  // 1) App datasource update
  this.filterSource.next(!this.filterSource.value);
  // 2) VScroll update
  const min = this.datasource.adapter.bufferInfo.minIndex;
  const max = this.datasource.adapter.bufferInfo.maxIndex;
  const indexesToRemove = Array
    .from({ length: max - min + 1 })
    .map((_, i) => i + min)
    .filter(i => (i % 2));
  this.datasource.adapter.remove({ indexes: indexesToRemove });
``` 

Updated demo: https://stackblitz.com/edit/base-angular-12-app-7zp2fb

**Comment by dil-pkollar** [comment]
Thank you very much for you quick and clear answer how it works!
