### ISSUE TITLE
Scrolling on item click when it's not fully visible in list

### ISSUE THREAD

**Issue by gaspgor** [dhilt/ngx-ui-scroll#334]
Hey there,

I am using ui scroll and I find out that when item in list is not fully visible (e.g when you scrolling down and the top item is visible in 30%) and by clicking on it it scrolling down and making item visible in 100%.

So the question is how we can fix that issue, or maybe there is an option to disable that behavior.

![Screenshot 2023-04-17 152347](https://user-images.githubusercontent.com/68889200/232473096-13282d93-6ee8-4e28-8249-3181892ea8cd.png)
![Screenshot 2023-04-17 152402](https://user-images.githubusercontent.com/68889200/232473100-efe75087-bb64-42a6-8b99-67c36f8fe2dd.png)

**Comment by dhilt** [comment]
@gaspgor I guess, it might be a css issue. I created this demo - https://stackblitz.com/edit/ngx-ui-scroll-3-angular-14-demo - please take a look, there is no autoscroll behavior. If you can fork it and update to reproduce the problem, I will check what can be done.


https://user-images.githubusercontent.com/4365660/232638008-e9fc1103-5359-4035-aa45-1a7b4df7ace1.mp4

**Comment by gaspgor** [comment]
@dhilt Thanks for response. I find out the reason of that behavior. That because of ion-item. As I researched it have some feature that affect item clicking. So when item is visible partly it scrolls down automatically when I press. 

all the best
