### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'log')

### ISSUE THREAD

**Issue by weilinzung** [dhilt/ngx-ui-scroll#335]
We are keep getting this error from `vscroll` lib.

```
Uncaught (in promise) Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'log')
TypeError: Cannot read properties of undefined (reading 'log')
    at vscroll.esm5.js:5168:20
```

https://github.com/dhilt/vscroll/blob/5ebbe79497bc90594885b792d04dd9868f641582/src/classes/adapter.ts#L515

Not too sure if because in this wrapper that doesn't export the logger?

![Screenshot 2023-04-26 at 12 31 36 PM](https://user-images.githubusercontent.com/7368063/234642166-3277a430-ba87-453c-8398-fe42735f2ed7.png)

**Comment by dhilt** [comment]
@weilinzung It looks like a serious issue. Loosing a context. Do you call the `Adapter.reset` method at some moment or destroy/re-create the component containing the Scroller? Could you please attach [dev-log](https://github.com/dhilt/vscroll/wiki/Dev-Log) of the failing run? I need to understand which processes have led to this point.

```js
  devSettings: {
    debug: true,
    logProcessRun: true
  }
```

Also, if it is possible, could you provide minimal runnable demo (like by forking [this stackblitz](https://stackblitz.com/edit/ngx-ui-scroll-3-angular-14-demo))? This would be the best option for me to investigate the issue.

**Comment by weilinzung** [comment]
@dhilt, we do call `reset` method in some usages. It is very complex for our usage, let me do the debugging first. Then I will get back to you. thank you for your quick response.

**Comment by weilinzung** [comment]
@dhilt It is the issue of calling  `Adapter.reset `. We basically listen to the data changes from the backend, then call the `reset`.

```
      const newDatasource = this.createDataSource(newIndex);
      await this.dataSource.adapter.reset(newDatasource);
```

**Comment by dhilt** [comment]
@weilinzung Ok, still waiting for dev logs 🙂

**Comment by dhilt** [comment]
ngx-ui-scroll v3.0.2 contains fix related to this issue, though I'm not sure if it covers the initial case, so, please open a new PR if the problem still occurs.
