### ISSUE TITLE
Angular 16 compatibility ?

### ISSUE THREAD

**Issue by ThibDums** [dhilt/ngx-ui-scroll#336]
Hi guys, 

We would like to know if this library is expected to be compatible with Angular 16 Ivy ?

**Comment by dhilt** [comment]
@ThibDums The ngx-ui-scroll library supports Ivy since v3. Here's the stackblitz demo for Angular 16: https://stackblitz.com/edit/ngx-ui-scroll-3-angular-16

**Comment by sheikalthaf** [comment]
@dhilt  when can we expect the anuglar 16 release?

```
./node_modules/ngx-ui-scroll/fesm2020/ngx-ui-scroll.mjs:5:0-80 - 
Error: Module not found: Error: Can't resolve 'vscroll' in '.../node_modules/ngx-ui-scroll/fesm2020'



✖ Failed to compile.
```

currently getting error if i try to use in angular 16 version.

Thanks in advance
