### ISSUE TITLE
Object reference after appending

### ISSUE THREAD

**Issue by muchbetterug** [dhilt/ngx-ui-scroll#345]
Hey!

I have an object `foo,` which i add dynamically to the scroller like this:

`await this.datasource?.adapter?.append({ items: [foo] });`

When i change `foo` afterwards, like setting a property e.g. `foo.content = 'hey'`, the change is not reflected/rendered - so i think the reference to the original `foo` object got lost.

Is there a way to keep this reference? I think in older ngx-ui-scroll versions, this was possible -

Thanks for this great library!

**Comment by dhilt** [comment]
@muchbetterug References should work, although this is generally considered a dangerous technique. My guess is that you have an issue with datasource synchronization. I mean, along with appending `foo` via adapter, you need to provide exactly the same (by reference) `foo` object to the datasource. Look at this demo, I made this especially for your case:

https://stackblitz.com/edit/ngx-ui-scroll-3-prepend-and-references

**Comment by muchbetterug** [comment]
Thank you, you're right, references work!
I had a component with OnPush ChangeDetection inside the scroller, so i needed to call the ChangeDetection.
