### ISSUE TITLE
Can't update Demo App to Angular 6

### ISSUE THREAD

**Issue by dhilt** [dhilt/ngx-ui-scroll#38]
Multiple errors during compilation:

> ERROR in ./node_modules/ngx-bootstrap/dropdown/bs-dropdown.directive.js
> Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in 'D:\dev\ngx-ui-scroll\node_modules\ngx-bootstrap\dropdown'
> 

Is blocked by https://github.com/valor-software/ngx-bootstrap/issues/4299.

**Comment by postpersonality** [comment]
Hello! Block is resolved.
