### ISSUE TITLE
Window scroll

### ISSUE THREAD

**Issue by fredericojesus** [dhilt/ngx-ui-scroll#42]
Hey @dhilt,

I can't seem to figure out how to make it work with window scroll.
I don't see anything on the documentation or on the examples but I know that on the AngularJS version it was supported so probably is it something that will be supported in the near future?

**Comment by dhilt** [comment]
@fredericojesus Thanks for the issue! We'll certainly do it. Not sure it will be in nearest releases, so let's this issue keep open.

**Comment by dhilt** [comment]
The entire window scroll feature is finalized in v0.0.5-rc.2 which has been just published.
