### ISSUE TITLE
after updating records in datasoruce , view(html) is not updated ? how to refresh datasource

### ISSUE THREAD

**Issue by riteshsingh2k** [dhilt/ngx-ui-scroll#44]

**Comment by dhilt** [comment]
@riteshsingh2k You may try to use `Adapter.reload` method, 
https://dhilt.github.io/ngx-ui-scroll/#/adapter#reload
Currently it is the only way to make changes in the View (say, reset the View) after the data from Datasource is retrieved and rendered.
