### ISSUE TITLE
Is it possible to use page and size while creating datasource

### ISSUE THREAD

**Issue by andiwonder** [dhilt/ngx-ui-scroll#46]
Hi, 

My api is build using the params page and size , so I can do something like page 1 and size 10 to get elements 11 to 20. I was wondering if I could create a datasource with those params or is it fixed to index and count ?

**Comment by dhilt** [comment]
Hey, thanks for the issue! The Datasource.get method has only index-count signatures. But you can implement pages logic as an intermediate layer between the Datasource (uiScroll) and the Remote (server data). Something like

```
get: (index, count, success) => {
  const start = Math.max(index, 0); // no negative indexes 
  const end = start + count;
  const startPage = Math.floor(start / count);
  const endPage = Math.ceil(end / count);
  // ... request data for pages from startPage to endPage
    // ... "result" should have joined array of requested items
    const data = result.slice(start - startPage * count, start - startPage * count + count);
    success(data);
}
```

With this approach we do some extra work and should throw away items that are out of real index-count scope (`result.slice`). Depending on your needs this could be improved. For example you may build a full cache layer here: all data is being stored in special array (Cache, see below) that could increase only, and then you slice that array to pass index-count piece into the uiScroll. If some items are not in the Cache, do a request for the page that should include missing items, then store the response items in the Cache and then slice the Cache to pass index-count piece into the uiScroll.

```

interface IDatasourceCacheItem {
  index: number; // should be relevant to the Datasource.get index
  item: any;
}
...
Cache: List<IDatasourceCacheItem>;
```

There are many ways and things that could be done: page size can differ from the Datasource.get count parameter (which is bufferSize setting), also, you may take into the account max page number value etc. Datasource.get method implementation could be very flexible and complicated, I hope I was able to reflect the idea of additional layer within the "get" method.

**Comment by MasterToney** [comment]
@dhilt have you considered adding a minIndex setting at one point?
Asking because I too limit the index to 0 and thought that it would be neat if you could set that just like the startIndex for example.
I suspect that this use case might be quite common ;)
Keep up the good work!

**Comment by dhilt** [comment]
@MasterToney Sure! I understand the need and AngularJS version had such a setting. It would be nice if you create a separate issue for minIndex setting, because this one will be closed (I hope).

**Comment by andiwonder** [comment]
Hey, thanks for the explanation. Was able to get it working (sort of) with your code and you can close the issue if you want. Thanks for the reply.
