### ISSUE TITLE
Feature request minIndex setting

### ISSUE THREAD

**Issue by MasterToney** [dhilt/ngx-ui-scroll#47]
As a common use case involves the limitation of the index in order to call an api I suggest implementing a setting which limits the index from which data gets loaded.

```
datasource: IDatasource = {
  get: (index, count, success) => {
    const data = [];
    for (let i = index; i <= index + count - 1; i++) {
      data.push({ id: i, text: 'item #' + i });
    }
    success(data);
  },
  settings: {
    minIndex: 0 // would be nice to have ;)
  }
}
```

In this example `get` would only be called with `index >= 0` which avoids checks like:

```
get: (index, count, success) => {
  const start = Math.max(index, 0); // no negative indexes 
  const data = [];
    for (let i = index; i <= index + count - 1; i++) {
      data.push({ id: i, text: 'item #' + i });
    }
  success(data);
}
```

**Comment by dhilt** [comment]
Closing this per minIndex setting implementation is done! See [demo](https://dhilt.github.io/ngx-ui-scroll/#/settings#min-max-indexes).
