### ISSUE TITLE
perfect scrollbar look

### ISSUE THREAD

**Issue by cristigav** [dhilt/ngx-ui-scroll#51]
I have a question: can ngx-ui-scroll be used toghether with a perfect scrollbal (like ngx-perfect-scrollbar), or the concepts are not compatible?

Actually I am more interested to replace the native scroll used in ngx-ui-scroll with a perfect scrollbar look.

I really do not know if I am asking you for a new feature, or I can do this on top of ngx-ui-scroll just with css.

**Comment by dhilt** [comment]
@cristigav Sure, it should be possible! We have a stackblitz sample that demonstrates such an integration (with ngx-scrollbar): https://stackblitz.com/edit/angular-aba8se
