### ISSUE TITLE
Question on using observables

### ISSUE THREAD

**Issue by ArcticFaded** [dhilt/ngx-ui-scroll#52]
Hello,
I have the following pattern for information but I am not getting how the scroll fetches new values. In my system I retrieve information as such:

- http GET request fetches all the data
- The data is then passed to a subject like so

```
private nodes: Node[] = []
private nodesSource = new Subject<any>();
nodes$ = this.nodesSource.asObservable()


constructor(private http: HttpClient ){
    this.http.get(APIroot + '/all').subscribe((data: QUESTIONS.Widget[]) => {
        var temp = []
        for(var entry of data){
            temp.push(new Node(1, data.id))
        }
        this.nodes = temp;
        this.nodesSource.next(data);
    })
}

search(string){
    var filter = []
    for(var node of this.nodes){
        if(StringMatch(node, string)){
            filter.push(node)
        }
    }
    this.nodesSource.next(filter);
}
```

In a component I pass the observable as follows:

```
  nodes: Node[] = [];

  public datasource: IDatasource = {
    get: (index, count) => this.service.nodes$ // from the space above imported to the component
    ,
    devSettings: {
      debug: true
    }
  }
```

However when I try using my search function, it will only update on the first update. After that it never updates again. I am not understanding why, I would also like to know how I could use index and count with my observable, I do not know how to index an observable.

**Comment by dhilt** [comment]
@ArcticFaded Basically if you already have `nodes: Node[]` that contains all the data you want to be accessible by the `uiScroll`, then the easiest way to implement `Datasource.get` method would be

```
datasource: IDatasource = {
  get: (index, count, cb) => cb(this.nodes.slice(index, index + count))
}
```

We also may want to take care of negative indexes:

```
datasource: IDatasource = {
  get: (index, count, cb) => {
    if (index < 0) {
      count += index;
      index = 0;
    }    
    cb(this.nodes.slice(index, index + count));
  }
}
```

If you want some external `nodes$: Observable<any>` to be a datasource for the `uiScroll`, there may be some difficulty. The point is that the `uiScroll` should trigger new data fetching when the scroll conditions are fulfilled. The data must flow from the App to the `uiScroll` per `uiScroll` index-count requests, so `Datasource.get` is responsible for such a flow. If you return `nodes$` from `Datasource.get`, the subscriber within the `uiScroll` won't be triggered until the source is changed. As I understand `nodes$` is being changed on initialization and during search. Not during scroll. To provide right data flow I can suggest following approach.

**1.** Subscribe to `nodes$` changes on component's constructor to have non-reactive data on the component and to refresh the viewport on each search.

```
  private data: Node[] = [];

  constructor(public myData: MyData) {
    this.myData.nodes$.subscribe((data: Node[]) => {
      this.data = data;
      this.datasource.adapter.reload();
    });
  }
```

**2.** Initialize Datasource via 'new'  for safe access to Datasource.adapter object and just slice component's data taking negative indexes into the account passing the result via plain old callback.

```
  datasource = new Datasource({
    get: (index, count, callback) => {
      if (index < this.myData.startIndex) { // this.myData.startIndex = 0
        count -= Math.abs(index - this.myData.startIndex);
        index = this.myData.startIndex;
      }
      callback(this.data.slice(index, index + count));
    },
    settings: {
      startIndex: this.myData.startIndex
    }
  });
```

____________

I created simple demo for this case on stackblitz: https://stackblitz.com/edit/angular-qygtkf. There also should be another approaches, but this is what just came to my mind. Hope it helps!

**Comment by ArcticFaded** [comment]
Thank you so much! Yes this answers all my questions and thanks for that demo!
