### ISSUE TITLE
weird index when scrolling back

### ISSUE THREAD

**Issue by alexus85** [dhilt/ngx-ui-scroll#53]
The index is correctly incremented by the number defined in bufferSize when scrolling down.  However when I scroll up, I get weird indexes and I don't know how to calculate current position. 

Please see below the flow. I'm only using some very basic example from your demo pages, just populated with some real data and that's it.

index: 0 
Scroll down: 
index: 4 
Scroll down: 
index: 8
Scroll down: 
index: 12
Scroll up: 
Index: 0  **//// why 1???** 
Scroll down: 
index: 11 /// ????

Thanks in  advance,
Alex

**Comment by dhilt** [comment]
@alexus85 Could you please show your `Datasorce.get` method implementation?

**Comment by alexus85** [comment]
https://angular-jxmkxz.stackblitz.io

I'm trying to calculate the current page since we're not using [from, to] ranges when requesting table data.

**Comment by dhilt** [comment]
@alexus85 As I can see in your demo you are trying to apply page logic over index-count logic of the Datasource.get method. This certainly could be done and [here are some thoughts](https://github.com/dhilt/ngx-ui-scroll/issues/46#issuecomment-393336846) on this issue.
Does it cover your situation?

**Comment by alexus85** [comment]
Thanks, will definitely try this approach, although I don't understand that when the table is initially loading, it loads as much data as is required to fill out the predefined table height.  When it hits the height, it stops loading, at that point it's always trying to load page with index: 0 , count: 5.

https://stackblitz.com/edit/angular-jxmkxz

setting page : 0
loading page : 0

setting page : 1
loading page : 1

setting page : 0 /// ???
loading page : 0 /// ???

Why is that happening?

**Comment by alexus85** [comment]
I have updated my example on stackblitz (same link) , but I can't get even near to what I'd like to achieve. Whenever I'm communicating with my API, I only send current page index, not from - to page. 
So I need to calculate just the currentPage index as I scroll up or down. But that only works as I scroll down, when I scroll up the get method isn't being called at all for some reason.

**Comment by dhilt** [comment]
@alexus85 I forked your last demo and made it work. It took some time due to some inaccuracy in the initial approach description and your implementation.

https://stackblitz.com/edit/angular-hpg9ev

Now it is done and I think this sample should be included into official demo list.

**Comment by alexus85** [comment]
It's working like a charm!

I event did some performance testing , added two viewports with same datasource (as I. couldn't figure out a better way to add a sticky column to my lis)t, the scrollTop property of the second viewport is being updated as soon as the other is scrolled. Also removed all the console logs and it performed very well. 

https://stackblitz.com/edit/angular-ttoesn?file=src%2Fapp%2Fapp.component.ts

Thank you so much!
