### ISSUE TITLE
current index

### ISSUE THREAD

**Issue by cristigav** [dhilt/ngx-ui-scroll#54]
Is it possible to know the current index (first visible) ?
This would be useful to be able to do a reload at the same positions (for ex. after deleting an element)

**Comment by dhilt** [comment]
@cristigav I drafter a solution in [first-visible branch](https://github.com/dhilt/ngx-ui-scroll/tree/first-visible). Could you try it before next release? 

```
git clone https://github.com/dhilt/ngx-ui-scroll.git
cd ngx-ui-scroll
git checkout first-visible
npm install
npm start
http://localhost:4200/#/test
```

The Adapter got new property `firstVisible` that is an object of special type:

```
export interface ItemAdapter {
  $index?: number;
  data?: any;
  element?: HTMLElement;
}
```

So to have current top index you should do something like this:

```
{{datasource.adapter.firstVisible.$index}}
```

**Comment by cristigav** [comment]
Thanks, works ok 👍 
I will use it with the next release.

**Comment by brunohbelo** [comment]
Hi folks, I also need that new feature about the first visible. There is a date for the next release?

**Comment by dhilt** [comment]
Okay, I'm going to postpone major release and promise to publish v0.0.6 in 1-2 days

**Comment by dhilt** [comment]
Let's try v0.0.6! Documentation is not updated, so I want to put some notes here:

 - use `new Datasource(...)` in your component to instantiate the datasource with the Adapter
 - use `{{datasource.adapter.firstVisible.$index}}` in your template to output first visible item's index where `firstVisible` is dynamically updated item object
 - use `{{(datasource.adapter.firstVisible$ | async)?.$index}}` in your template to output first visible item's index where `firstVisible$` is BehaviourSubject of first visible item object
 - use `this.datasource.adapter.firstVisible$.subscribe((value) => console.log(value.$index));` in your component's code to catch the exact moment when first visible item is changed
 - the subscription is smart enough, so you may subscribe even on your component's constructor before the uiScroll is initialized itself

The first visible item object has following properties 
```
ItemAdapter {
  $index?: number;
  data?: any;
  element?: HTMLElement;
}
```
This type is not exported out of the UiScroll module for now.

**Comment by brunohbelo** [comment]
I have updated to version 0.0.6 and the current index works fine! thanks
