### ISSUE TITLE
isLoading api surface

### ISSUE THREAD

**Issue by bearinld004** [dhilt/ngx-ui-scroll#56]
Coming in from [another issue](https://github.com/dhilt/ngx-ui-scroll/issues/55). In my case I like call back style. But observables are fine too. basically need to trigger a function to scroll down once data is loaded. Come to think of this would also be nice and convenient to work with.

```
<div *uiScroll="let item of datasource" onLoad="onLoadFunc">
    <b>{{item.text}}</b>
</div>
```

**Comment by dhilt** [comment]
@bearinld004 v0.0.6 has been just released, it has updates related to this issue. See [this comment](https://github.com/dhilt/ngx-ui-scroll/issues/54#issuecomment-407648239), applying to `isLoading` the following should work in your component's code

```
this.datasource.adapter.isLoading$.subscribe((value) => console.log(value));
```
