### ISSUE TITLE
Preload

### ISSUE THREAD

**Issue by brunohbelo** [dhilt/ngx-ui-scroll#58]
Is there a possibility to antecipete the load of the itens. I mean, before the scroll reach the top or the bottom, the load is called. My problem is, when the load is called it takes 1-2 seconds to bring and rendenize my itens on html

**Comment by dhilt** [comment]
Hi @brunohbelo! You may try to use `Adapter.isLoading` in your project. This property is being set to `true` while the uiScroll Workflow does run (and the `Datasource.get` as a part of this process does work). It is set to `false` when the uiScroll does not work and necessary items are retrieved and rendered. We have [isLoading demo](https://dhilt.github.io/ngx-ui-scroll/#/adapter#is-loading). It is related to v0.0.5. In v0.0.6 we also have Observable interface: `Adapter.isLoading$`, it works in the same way as `Adapter.firstVisible$`. With this flag you may improve the UI with conditional pre-loader. Does it fit your needs?

**Comment by brunohbelo** [comment]
Thanks for the reply. I've changed my UI and I've implemented the Adapter.isLoading$, it helped a lot, but sometimes the scroll seems to hook, I ran some tests and the reason may be the act to keep scrolling. It's possible to set a limer to block unecessary handlers of the scroll?
Here is a performance test that I did

![teste](https://user-images.githubusercontent.com/13396351/43536017-e63dba6a-9591-11e8-9bb8-b2bf135e0850.png)

**Comment by dhilt** [comment]
@brunohbelo The uiScroll has only one scroll handler that is throttled by 40ms by default. This value can be changed via undocumented `Datasource.devSettings.throttle`, so you may try to play with it. Also, scroll handler does skip processing logic if the uiScroll works. I see that current scroll handling implementation is not the best one and there are some ways how to improve it. Anyway, it is very important to investigate the directive work from the performance view and if you have some thoughts/results, I guess, it would be better if you opened a separate issue!
