### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by chrsadk** [dhilt/ngx-ui-scroll#60]
Hello,

The library works great for my usecase in Chrome, Firefox, Edge and Opera (haven't tried Safari yet).

But it fails in IE11.

I tried opening your demo page in IE11, and it fails as well. Maybe I'm overlooking something?

Is the intention to support IE11?

Best regards
Christian

**Comment by dhilt** [comment]
@chrsadk Thanks for the issue! I never tried to run it with IE, so it took some time. And I saw the error 

> Exception thrown and not caught _for-of.js (14,1)

and I was able to fix it by modifying polyfills.ts of the demo App. I just uncommented "IE9, IE10 and IE11 requires all of the following polyfills" imports. You may play with this section of your polyfills.ts and precisely find out which imports are needed for your App to be runnable in IE11.

Maybe I missed something, so please report the results, and if it does not work I'll dig into it.

**Comment by chrsadk** [comment]
@dhilt Thanks for checking - turns out I already had the same polyfill imports uncommented in my app.

However, after some more investigation, it's the "entire window scrolling demo" (on route /window) that displays the same error as I'm getting in my app (even with polyfills uncommented in the demo app).

The error is shown in danish on my system, but roughly translated: "Attribute 'scrollTop' cannot be found for reference that is undefined or null". So maybe some issue with locating the proper parent, when it's the entire window (in IE)?

**Comment by dhilt** [comment]
@chrsadk I was able to reproduce the issue on the Entire window demo. The following assignment is the root of the problem:

```
this.scrollable = <HTMLElement>this.element.ownerDocument.scrollingElement;
```
Per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement) IE has no `scrollingElement` property on the document object. So this line (./src/component/classes/viewport.ts:43), I believe, should be replaced with

```
this.scrollable = <HTMLElement>this.element.ownerDocument.documentElement;
```

While I'm working on the [workflow-5](https://github.com/dhilt/ngx-ui-scroll/tree/workflow-5) branch, maybe I may ask you to try this fix locally and open the Pull Request to the 'master' if it's okay?
