### ISSUE TITLE
can we add checboxes 

### ISSUE THREAD

**Issue by mohammed534** [dhilt/ngx-ui-scroll#61]
because the DOM elements are replacing while we scroll...im loading the data from api on every scroll so is it possible to add checkboxes to the table and select multiple rows and show the selected rows??

**Comment by alexus85** [comment]
I suppose you may need to store the state of those check-boxes for each row on client side. And then,  identify the row via index (or some other key) while loading the data and check the box when the row's state meets requirements.

**Comment by dhilt** [comment]
@mohammed534 You may store the row state right on the item model. Add 'isSelected' field to each item when returning it from Datasource.get. If you are using Observable signature, it could look like

```
  import { map } from 'rxjs/operators';

  datasource: IDatasource = {
    get: (index, count) =>
      this.http.get(`${myApiUrl}?index=${index}&count=${count}`).pipe(
        // mark all even items as selected
        map(items => items.map((item, index) => item.isSelected = index % 2 !== 0))
     )
  };

  doToggleItem(item) {
    item.isSelected = !item.isSelected;
  }
```

Then you should be able to use 'isSelected' in the template, create checkboxes, bind selection classes etc:

```
  <div *uiScroll="let item of datasource">
    <span (click)="doToggleItem(item)">
      {{item.text}} {{item.isSelected ? ' (selected)' : ''}}
    </span>
  </div>
```

**Comment by mohammed534** [comment]
thank you...i'll try this
