### ISSUE TITLE
Virtual scrolling with infinite scrolling/pagination?

### ISSUE THREAD

**Issue by agscheidle** [dhilt/ngx-ui-scroll#62]
Is there a way to support paginated data sets with this directive so that I can virtually scroll through an infinite scrolling list by updating my datasource  (think async binding via observable) until the user has loaded all the data?

We do this with some data grids elsewhere by using the count/index to slice the data source being fed to the observable. It's handy because it reduces the datasource to approximately the buffer size yielding great performance. However, if one has to load a huge data set to do this, it becomes ineffective. If we could specific a total records setting that gave this directive a way to calculate scroller handle position and 'waypoints' where an event was dispatched every time the scroller reached x% of the current buffer, we could really leverage this nicely.

**Comment by dhilt** [comment]
@agscheidle Hi Andrew! I think you may be interested in following issues: https://github.com/dhilt/ngx-ui-scroll/issues/49, https://github.com/dhilt/ngx-ui-scroll/issues/46. The second one is about pagination approach for uiScroll directive and [here is](https://stackblitz.com/edit/angular-hpg9ev?file=src%2Fapp%2Fapp.component.ts) callback-based Datasource.get implementation example. This approach could be applied also to Observable-based .get. But if we are talking about remote source of data and http requests, I would suggest you to build a cache layer (described in issue 46).

**Comment by agscheidle** [comment]
Hi @dhilt, the outline in #46 is actually the approach we have, and it generally works. The issue seems to be that despite calling `adapter.reload()` when the data in the middle cache layer (ngrx entity reducer has all the paged buffer, and a selector returns a slice of that data set), the scroll bottom is reached and cannot continue further.

The fundamental issue that prevents this from working for us (I suspect) is the true scroller height compared to the 'virtual' height. A scroller that truly had 1k records in it would calculate a scrollbar and scroll handle position that was much different than one calculated on only the buffer size (in my case 15 items). To truly scroll through an infinite and virtual scroll, one needs to know the total records that will be scrolled through, which is a value usually returned in a paged data set.

I will keep plugging away to get this to a point where at least the scroll handle jumps back up a few pixels to allow for more pages, but at present I can't seem to see even that work.

**Comment by dhilt** [comment]
@agscheidle Is it correct that the problem is that the uiScroll prevents forward scrolling right after `Adapter.reload()` is called? Skipping infrastructure details, this behaviour is managed by `Buffer.eof` property (end-of-file), which is set to `true` when the size of downward fetched item list is less than `Settings.bufferSize` (15 in your case). Can you check how many items are being fetched via `Datasource.get()` right after reload? Maybe it would be helpful if you turn on the uiScroll internal logging via undocumented `Datasource.devSettings.debug` set to `true` (it logs, among other things, "get" method results).

**Comment by dhilt** [comment]
Since the first major release, pages-based datasource implementation had been included in the list of official demo samples ([link](https://dhilt.github.io/ngx-ui-scroll/#/datasource#pages)).
