### ISSUE TITLE
Scroll issue on mobile device (Chrome/Android)

### ISSUE THREAD

**Issue by chrsadk** [dhilt/ngx-ui-scroll#64]
Hello,

I have tested the "Entire window scrollable" demo on Chrome 68.0.3440.91 on mobile device Huawei Mate 10 Pro using Android 8.0.0.

https://dhilt.github.io/ngx-ui-scroll/#/window

It doesn't really allow you to scroll through the items. It stops at some points, and you have to go further up, and then swipe very quick to get a few more rows shown. Sometimes it rapidly jumps to the top.

I don't know if the component is supposed to support mobile devices, but i hope so :)

Thanks
Christian

**Comment by alexus85** [comment]
Tried on my iPhone SE (Safari), everything works as expected, but then I
tested it on my second phone Huawei P9 (Android 7.0)
 and was experiencing the same. It just stops at 46 and not letting me
scroll further down the list.

**Comment by dhilt** [comment]
I was able to see the problem on Android 7 too, thanks for the report!
It is true that the entire window scrolling mechanism is different from common scrolling mechanism, so I need to learn how to debug javascript issues on the mobile, and it may take some time.

**Comment by mostafa321** [comment]
Hello dhilt,
 any update about the problem in scroll in chrome and android devices (example android 7 and 8).
kindly update me.
thanks

**Comment by dhilt** [comment]
@mostafa321 Sure! I started the investigation and looks like late Android treats browser static header in some special way that has impact on scroll process. I have [branch](entire-window-rect-params) where I'm trying to deal with it (the results are deployed on [dhilt.github.io](https://dhilt.github.io/ngx-ui-scroll/#/window) and as I can see the behaviour is a bit better). I need some more time to figure this out.

**Comment by chrsadk** [comment]
Hi @dhilt. Any chance you had time to investigate further?

**Comment by dhilt** [comment]
@chrsadk Christian, yesterday we have released first major version of the lib and it should have an impact on mobile experience too. May I ask you to review https://dhilt.github.io/ngx-ui-scroll/#/window behaviour? If you have some specific scenario/app environment, let's discuss it and try to reproduce it separately. For me the issue looks acceptably with v1.0.0 but I may miss something.

**Comment by antidote2** [comment]
The Demo exposes a problem to me at least on android: scrolling stops at the end of fetched items. I the next second I must scroll again to see more. For me it is annoying. I think it would be solved with the other request if you would display dummy items during the load. That could be further improved by prefetching items from the datasource, so they are readily available for display when you start to scroll down and then fetch more depending on the scroll speed. When the data is loaded at once like an array with 1000 elements, you would not even see the dummy items.

**Comment by YoungCatChen** [comment]
Not sure if it's related, but I noticed that https://dhilt.github.io/ngx-ui-scroll/#/window has issue on **desktop** Chrome browser (ver. 79.0.3945.130) on my MacBook Pro. To reproduce, scroll down to around `Item #100` and then scroll up slowly. You will notice the items jumping up and down.

Let me know if you would like to see a screen recording or anything.

**Comment by dhilt** [comment]
This is done with the release of ngx-ui-scroll v1.6.3. All the logic related to the Entire Window Scrollable case had been reconsidered. Also, the requirement of the "overflow-anchor: none" rule set on the topmost DOM node (html/body) for this case is appeared. Here's the new issue for removing this requirement: https://github.com/dhilt/ngx-ui-scroll/issues/173.
