### ISSUE TITLE
Virtual scroll for grouped items with nested ngFor

### ISSUE THREAD

**Issue by bernard4uece** [dhilt/ngx-ui-scroll#68]
I am looking for any pointers on how to implement this virtual scroll for nested ngfor scenarios where I grouped data and iterating through group.items in inner ngFor. Please let me know

**Comment by dhilt** [comment]
@bernard4uece If you want to use ngFor for each row of virtualized dataset, it may look like

```
<div class="viewport">
  <div *uiScroll="let item of datasource">
    {{item.text}}
    (<small *ngFor="let subItem of item.data">
      {{subItem}}
    </small>)
  </div>
</div>
```

where datasource must provide an array of items `{ text: "...", data: [1, 2, 3, ...] }`

```
 datasource = new Datasource({
    get: (index, count, success) => {
      const data = [];
      const subItemListMaxLength = 10;
      for (let i = index; i <= index + count - 1; i++) {
        this.data.push({
          text: 'item #' + i,
          data: Array.from({length: Math.random() * (subItemListMaxLength - 1) + 1}, (x, j) => j + 1)
        });
      }
      success(data);
    }
  });
```

As a result you will get following:

```
...
tem #0 ( 1 2 )
item #1 ( 1 2 )
item #2 ( 1 2 3 4 5 6 7 8 )
item #3 ( 1 2 3 4 5 )
item #4 ( 1 2 3 4 5 6 7 8 9 )
item #5 ( 1 2 3 4 5 6 7 8 9 )
item #6 ( 1 2 3 4 5 )
item #7 ( 1 2 3 )
item #8 ( 1 2 3 )
...
```

Does this satisfy your needs?

**Comment by bernard4uece** [comment]
Thanks for the inputs. I am not sure if I followed you correct but I tried to use this solution and it didn't work for me. I think I am missing something and may be stackblitz with my reference code would help you understand better what issues I have and where I am doing wrong.  I will try to do it and keep you posted when I get time. Appreciate your response

**Comment by dhilt** [comment]
@bernard4uece Yep, stackblitz would be the best option. And also I would ask you to describe desired behaviour, desired output.

**Comment by bernard4uece** [comment]
@dhilt Please see the [stackblitz](https://stackblitz.com/edit/angular-grouped-data-table) I have something pretty similar table with at least 20-30 groups with each group having 50-100 records. When I scroll through table body, I am looking for the option to render only records that are visible in that table body height. Please let me know if you followed what I described. Appreciate any inputs. Since I am loading ~(800-1000) records and rendering everything into DOM, the page appears to perform really slow in Edge especially. And I do have some additional functionality like sorting and more columns as well.

**Comment by dhilt** [comment]
@bernard4uece The approach I described above is definitely applicable to your task. Here is the updated stackblitz: [angular-ngx-ui-scroll-grouped-data-table](https://stackblitz.com/edit/angular-ngx-ui-scroll-grouped-data-table). You are lucky, it works because the uiScroll can virtualise rows of uncertain height.

**Comment by bernard4uece** [comment]
@dhilt Thanks for quick response. Your stackblitz fork really helped me a lot and I am now able to implement this feature in my app. I truly appreciate your help and thanks for your contribution to this open source world. I think we can close this issue now.

**Comment by SaravanarajaGITHUB** [comment]
@dhilt  this link you mentioned is not working (https://stackblitz.com/edit/angular-ui-scroll-grouped-data-table)

**Comment by dhilt** [comment]
@SaravanarajaGITHUB Yes, I accidentally moved it to another url, here's the [updated link](https://stackblitz.com/edit/angular-ngx-ui-scroll-grouped-data-table).
