### ISSUE TITLE
this.datasource.adapter is undefined

### ISSUE THREAD

**Issue by sesellis** [dhilt/ngx-ui-scroll#71]
I am following the example for the reload index functionality shown here: https://dhilt.github.io/ngx-ui-scroll/#/adapter but I am getting Error Type Error "this.datasource.adapter is undefined". Is there an additional package required to install the adapter?

**Comment by dhilt** [comment]
@sesellis 
1. Datasource should be initialized via operator _new_:

```
import { Datasource } from 'ngx-ui-scroll';
...
datasource = new Datasource({
  get: ... ,
  settings: { ... }
});
```

2. And then the Adapter could be accessible via `this.datasource.adapter`.

3. The Adapter call should occur only after the Datasource had been instantiated. For example you can't call the Adapter on your component's constructor if you are instantiating the Datasource on your component's ngOnInit.

In case this doesn't help, I would ask you to show your Datasource implementation and how you try to access the Adapter. The entire component's code would be fine too. The best option is stackblitz demo.

**Comment by sesellis** [comment]
Perfect, thank you. I was trying to combine one of the examples that didn't use new.
