### ISSUE TITLE
Empty space buildup at the top when row item change height

### ISSUE THREAD

**Issue by gamefundas** [dhilt/ngx-ui-scroll#73]
Is there a way to refresh the scroll bars when the items change height as I noticed in my use of the component that when the row items change height after the view is rendering scrolling with the new items now causes empty space at the top of the list.

**Comment by dhilt** [comment]
@gamefundas Currently we have no mechanism for dynamic items heights adjustment after the view is rendered, but let's think about how it could be. What scenario you have for this issue? Do you know the exact moment when some given item's height is being changed? or a time interval when it can occur? 

If we know the time, we may try to implement height listener, and adjustment will happen silently. In other hand, we need to provide an API on manual height change triggering.

**Comment by dhilt** [comment]
Adapter.check method is available since v1.1.0 ([demo](https://dhilt.github.io/ngx-ui-scroll/#/adapter#check-size)).
