### ISSUE TITLE
Horizontal scroll not scrolling

### ISSUE THREAD

**Issue by sesellis** [dhilt/ngx-ui-scroll#74]
I am working on getting horizontal scroll implemented in a project. I have followed the demo page but I am unable to get the example working in my own project. It appears that the display: inline-block does not apply to the child divs inside each element so they simply stack on each other. To verify that CSS is not the issue, I have included the rendered code by copying the outer HTML from the browser inspector, and it creates a horizontal scroll as shown in the demo.

I have created a demo stackblitz demonstrating the above here: https://stackblitz.com/edit/angular-ge7otc

Any ideas are much appreciated.

Thanks!

**Comment by dhilt** [comment]
@sesellis Thanks for the issue and especially for stackblitz demo. With the help of your demo the problem could be investigated quite quickly. Let's look at the result html:

<img width="515" alt="screen shot 2018-11-06 at 06 09 25" src="https://user-images.githubusercontent.com/4365660/48040587-9f59d080-e18a-11e8-8f5e-918ddc80cdee.png">

Some divs have `_ngcontent-c36` attribute, some don't.  The styles you defined in app.component.css are being applied with this attribute mention:

```
.viewport.horizontal[_ngcontent-c36] div[_ngcontent-c36] {
    display: inline-block;
}
```

And all internal containers created by the `*uiScroll` directive (`<div ui-scroll>`, `<div data-padding-backward>`, `<div data-sid="X">` and `<div data-padding-forward>`) don't have such attribute, and `display: inline-block;` rule is not applied.

The `_ngcontent-cX` attributes are being added by the Angular itself in case the encapsulation strategy is set to `ViewEncapsulation.Emulated` value ([which is the default](https://angular.io/api/core/ViewEncapsulation#Emulated)). It means that all divs you defined in the app.component.htm will be marked with `_ngcontent-cX` attribute, where X is unique for this component. Divs I listed before (without this attribute) are parts of internal `*uiScroll` component creating run-time. So, we have a styles encapsulation conflict and I see two solutions. 

**First**, change encapsulation strategy of the host component:

```
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ],
  encapsulation: ViewEncapsulation.None // .Native or .ShadowDom values are fine too
})
```

**Second**, move the CSS rule that we are interested in to the global styles.css:

```
.viewport.horizontal div {
  display: inline-block;
}
```

**Comment by sesellis** [comment]
Excellent description and solution recommendations!

Sam
