### ISSUE TITLE
With `maxIndex` setting first get call has count 1

### ISSUE THREAD

**Issue by paul-moers** [dhilt/ngx-ui-scroll#75]
I'm optionally only allowing scrolling up and using the newly added setting maxIndex as 

> maxIndex: this.allowDown ? +Infinity : 0

But the result is that the first get call has a count value of only 1 instead of the bufferSize.

In version 0.0.7 I could achieve this by calling success with an empty array and returning form the get callback for a 'down' call, but this now prevents any data load.

**Comment by dhilt** [comment]
@syngi Thanks for the issue! may I ask you to fork [this stackblitz demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-0-0) (it's for v1.0.0 and Angular 7) and add necessary infrastructure to reproduce the issue? I really want to help you and this would save some time...

**Comment by paul-moers** [comment]
@dhilt of course, done [here](https://angular-ngx-ui-scroll-1-0-0-aau597.stackblitz.io). Thanks for the help and for this great script!

As a side note I also had to manipulate the data-padding-forward (set it's display to none) to get the items fill from the bottom of the container on load. I have that working so it's fine for me, but I can raise an issue for it if it's useful. The issue is showing in the forked demo.

**Comment by dhilt** [comment]
@syngi If you define following settings:

```
settings: {
  bufferSize: 10,
  maxIndex: 0,
  startIndex: -9
}
```

you will not need to play with padding elements (if the item height is known). First downward fetch will cover all the viewport. Could you also specify what do we want to achieve from this point? For example, I don't see `this.allowDown` condition...

**Comment by paul-moers** [comment]
@dhilt thanks for the suggestion, thought the issue for being able to use startIndex is that you must know how many items will fit in the viewport, in other words, how heigh each item is. But I'm wrapping the uiScroller in a component adding features (like top and bottom placeholders for e.g. showing a load spinner until that direction of the list is fully loaded; make first element the base element and show top and bottom floating buttons when it's scrolled out of the viewport to onclick scroll to it; provide options to only scroll down or only up (hence the this.allowDow I mentioned before)). So the item template is not fixed and I rather not have startIndex exposed from my wrapping component as that moves the responsibility for the load behaviour to the implementation while the component should take care of it.

I did not have the `this.allowDown` condition in the [stackblitz fork](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-0-0-aau597) as it mimics the result.
In my component I have `@Input() private readonly allowDown = true;` and with uiScroll 1.0.0 I tried `maxIndex: this.allowDown ? +Infinity : 0`. So when allowDown is set to false, setting maxIndex to 0 as in the forked demo, resulting in the batch size issue.

**Comment by dhilt** [comment]
@syngi I've just released v1.0.1 and it became possible to implement autoscroll feature which might be helpful in your case. The thing is we create a subscription to catch the moment when the uiScroll has finished its work (isLoading = false and there is lastVisible row) and then make an adjustment of scroll position in accordance with viewport-lastVisible bottoms difference.

```
autoscroll() {
    const { adapter } = this.datasource;
    const isLoadingSubscription = adapter.isLoading$.subscribe(isLoading => {
      const viewportElement = document.getElementById('my-viewport');
      const lastVisible = adapter.lastVisible.element;
      // if the uiScroll has been stopped
      if (!isLoading && viewportElement && lastVisible && lastVisible.getBoundingClientRect) {
        const lastElementBottom = lastVisible.getBoundingClientRect().bottom;
        const viewportBottom = viewportElement.getBoundingClientRect().bottom;
        const toScroll = viewportBottom - lastElementBottom;
        const diff = viewportElement.scrollTop - toScroll;
        if (viewportElement.scrollTop === diff) {
          isLoadingSubscription.unsubscribe();
        } else {
          // make an adjustment
          adapter.setScrollPosition(diff);
          // if current rows are enough to fill out the viewport
          if (viewportElement.scrollTop === diff) {
            isLoadingSubscription.unsubscribe();
          }
        }
      }
    });
}
```

We use `adapter.setScrollPosition` method which is undocumented but which provides safe continue of the uiScroll workflow after scroll position is changed. Also, we do unsubscribe not immediately (if-else condition) because single fetch could be not enough to cover all the visible part of the viewport.

The demo is available: https://stackblitz.com/edit/angular-ngx-ui-scroll-1-0-1-autoscroll.

**Comment by paul-moers** [comment]
Hi @dhilt, nice to see features being added, and this can be used for having the first item bottom aligned in the list viewport, though it seems not to help with the first get call having count value of 1?

**Comment by dhilt** [comment]
@syngi Current implementation of the uiScroll initialisation process gives us one downward fetch (which will result 1 item in case `maxIndex` is set to minimal possible value) and one upward fetch (which will result at least `bufferSize` items).  In general only `startIndex` might help with the first batch length in your case, but this requires knowing of items height. From the other hand we can autoscroll to the bottom line right after the first cycle (consists of 2 fetches) is done. If it is not something you want to do in your situation, what may we want to achieve?

**Comment by paul-moers** [comment]
@dhilt it's just that to me it seems odd to have a downward fetch at all when maxIndex is 0.
But I understand that the current solution is to work with startIndex and autoscroll after the first cycle. Though as you say for this the height if the items must be known, which is not. So for now work-as-designed I understand.

**Comment by dhilt** [comment]
Currently (v1.1.0) the issue can't be reproduced, and as I see it was fixed with [this commit](https://github.com/dhilt/ngx-ui-scroll/commit/e5d5962b0083ce94a2faa50c8171370afe4c0f18). So no autoscroll is needed, the case should work out-of-box.
