### ISSUE TITLE
Inverted datasource logic

### ISSUE THREAD

**Issue by Avishaidev** [dhilt/ngx-ui-scroll#80]
How can i start the scroll on bottom?
I have items with diffrent height (chat app with messages / images / video etc...)
And why on the page init the datasource run the get function twice?
I set buffer size to 20

**Comment by Avishaidev** [comment]
@dhilt I just figure it out and fix my code to do all i need and its perfect!!!
I have only one thing that i don't find ant thing about it.
How can i add new item (message) to the datasource, i mean all are loaded and new message received, How can i add this message?
Thanks

**Comment by dhilt** [comment]
@Avishaidev Glad to know that you have managed to work through the inverted datasource demo! Issue https://github.com/dhilt/ngx-ui-scroll/issues/55 is about adding new items on-flight, and as I said yesterday we are pretty close to new release that will include this functionality. 

Btw, single item prepending should work, and if you want, you may try it running from [this branch](https://github.com/dhilt/ngx-ui-scroll/tree/prepend)... if it will work for you, I could make an interim (or "@next") release.

**Comment by Avishaidev** [comment]
Thanks for the fast reply, i need the append item function so i will wait for the new release.
Do you know how long it will takes?

**Comment by dhilt** [comment]
@Avishaidev I just released v1.0.2 and you may try Adapter.prepend in action. This functionality is not fully tested/optimized, but basic scenarios should be ok. The documentation also is not updated, but I drafted 2 demos: please follow [prepend demo](https://dhilt.github.io/ngx-ui-scroll/#/adapter#prepend) and  [prepend-sync demo](https://dhilt.github.io/ngx-ui-scroll/#/adapter#prepend-sync).

**Comment by Avishaidev** [comment]
Look perfect, i don't need this right now, i am waiting for the append function.
Please can you say date that "append" will be ready?

**Comment by dhilt** [comment]
@Avishaidev I would say 3-4 hours are needed, because it is much easier than prepend, but I'm not sure, probably I will be able to look at this in 1-2 days... I opened separate issue: https://github.com/dhilt/ngx-ui-scroll/issues/81.
