### ISSUE TITLE
Adapter.append method

### ISSUE THREAD

**Issue by dhilt** [dhilt/ngx-ui-scroll#81]
Need to implement Adapter.append method to be able to add items to the end of the scroller' buffer on-flight.

**Comment by Avishaidev** [comment]
Thanks alot!!!

**Comment by Avishaidev** [comment]
@dhilt any update ?

**Comment by dhilt** [comment]
@Avishaidev I have some time today and opened PR https://github.com/dhilt/ngx-ui-scroll/pull/82, maybe we'll have a luck and it will be done today.

**Comment by Avishaidev** [comment]
@dhilt Thanks alot!
Waiting for you.

**Comment by dhilt** [comment]
@Avishaidev v1.0.4 has been just released. It includes Adapter.append method. Please follow [documentation](https://github.com/dhilt/ngx-ui-scroll#adapter-api) and also [append-prepend](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend-sync) and [append-prepend-sync](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend-sync) demos.

**Comment by Avishaidev** [comment]
@dhilt Thanks works like a charm!!!
can you add option to load more items from index.
Now is load more items when you scroll to bottom / top, i want to load more before the user got top scrolled.

thanks

**Comment by dhilt** [comment]
@Avishaidev Adding more items to the top of the buffer without scrolling can be done via Adapter.prepend method. Also, I opened new issue https://github.com/dhilt/ngx-ui-scroll/issues/83 dedicated to adding items by index.
