### ISSUE TITLE
Adapter.insert method

### ISSUE THREAD

**Issue by dhilt** [dhilt/ngx-ui-scroll#83]
We already have `Adapter.append(items, eof)` and `Adapter.prepend(items, bof)` methods which allow to add new items at the beginning and at the end of the dataset. Now we want to be able to add items by index.

**Comment by taujoey** [comment]
Any update about this? I really like this library, but the 'get' method makes it impossible to insert anything at a specific index, so i actually return an empty list, than use append to populate the list. It works great with a remote db, when some data arrives, but i dont see any solution to perform an insert without any trickery (like insert into a backing array, reload full list, and use the get() megthod to get back to previous number of items in the list, and maybe somehow the same scrolled position?

Also, any other way to have access to the inner array of items in the list would be really good. Other virtual list solutions i tried had this, but they had other problems.. :( I undersand the concecpt that the client has to prepare a datasource for the get() method, and always return something, when it is called, but it is a little too strict, i think.

**Comment by dhilt** [comment]
@taujoey  I waited for such request, so I know what I will do next. I can't estimate the efforts but I think I'll be able to start this task on next week. Also, you may take a look to one experimental feature released recently, `Adapter.fix({ updater })`, [see demo](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater).

It provides an access to current items in the scroller buffer. You can't use it to change the list itself (say, the length of the list will be the same and the references to the list will persist), but you will have items contents which you can read and update. If you will have any issues with .fix method, please open new PR

**Comment by dhilt** [comment]
[ngx-ui-scroll v1.5.0](https://github.com/dhilt/ngx-ui-scroll/releases/tag/v1.5.0) is released, it contains new Adapter.insert method
