### ISSUE TITLE
Rapid scrolling triggered on iOS

### ISSUE THREAD

**Issue by jonnyleeharris** [dhilt/ngx-ui-scroll#87]
I have noticed I can trigger some very rapid data fetching/list population on iOS which causes an inadvertent UX: the upwards scroll gets out of hand and you practically lose control of the list:

Two ways it's evident: If you rapidly scroll upwards, or if you scroll to the top of the viewport, trigger the reload and then maintain your finger position and slightly scroll up and down (a very minimal amount).

I have noticed it happening on a large list starting at a predetermined index.

My datasource (where count is the number of items in the list).

```
new Datasource({
          get: (index:number,count:number, success) => {  
            let r = Array(count).fill(0).map((v,i) => {
              let m:ChatMessage = {
                message: "message "+(index+i),
                senderID: "test"
              }
              return m;
            });
            success(r);
          },
          settings: {
            startIndex: count-1,
            bufferSize: 10,
          },
          devSettings: {
            inertia: false
          }
        })
```

```
<div
         

       #viewport
                fxFill fxFlex
                id="ui-scroll-viewport">
                <div *uiScroll="let item of datasource | async" style="padding: 20px;">
                    <div
                        class="messageBubble"
                        [class.selfMessage]="false">
                        {{item.message}}
                    </div>                    
                </div>
            </div>
```

```
#ui-scroll-viewport {  
  overflow-anchor: none;
  overflow-y: scroll;  
  -webkit-overflow-scrolling: touch;
}
```

![giphy](https://user-images.githubusercontent.com/1674502/54715362-2fe9e980-4b4b-11e9-9c51-502285cb4bcf.gif)

**Comment by dhilt** [comment]
@jonnyleeharris The description makes me me think about inertia scroll issue. What version are you using? v1.1.0-beta is the latest one at this moment and it has a bit different mechanism of inertia processing than 1.0.x. Also, you need to switch `devSettings.inertia` to true.

**Comment by jonnyleeharris** [comment]
> @jonnyleeharris The description makes me me think about inertia scroll issue. What version are you using? v1.1.0-beta is the latest one at this moment and it has a bit different mechanism of inertia processing than 1.0.x. Also, you need to switch `devSettings.inertia` to true.

@dhilt Yes I am on 1.1.0-beta, sorry - forgot to mention that.

Tried with `inertia: true` - the result is the same unfortunately.

Did you intend for it to be used with `-webkit-overflow-scrolling: touch;`?

Is there any more information I could provide or any recommendations you might have that might help me solve this or at the very least figure out why it's happening?

**Comment by dhilt** [comment]
@jonnyleeharris No, I didn't use `-webkit-overflow-scrolling: touch;` and never tried it on iOS. Though I worked a lot with Mac touchpad and I would say it is most painful part of momentum/inertia stuff I have to deal with during my work on ngx-ui-scroll. 

By the way, let's see what [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling) says about `touch`:

>  This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user etc
>

And this one 

> Also creates a new stacking context.
>

might be the cause of many issues.

One of the core idea of the virtual scrolling in case of uncertain dataset boundaries is that we need to make an artificial scrolling down when a user moves up and fetches new items. This situation leads to poorly controlled problems when inertia is in game. From one hand browser serves user up-scroll events, from the other one it serves artificial down-scroll event. Inertia events _might_ have their own bus which conflicts with regular javascript events bus, and artificial down-scroll event might have no priority. It depends on device/browser implementation. But in result we may get down-scroll adjustment not working and unwanted new items fetching on upward direction. Sorry for all these vague words, I hope that you may touch on things  for which I have spent most of my time and which I could not overcome fully.

Speaking of debugging, it can be useful if a log of the scroller when it runs the issue can be provided. You need set `devSettings.debug` to `true`, reproduce the issue, look at console log and copy it.

But I would advice to stay as far away from inertia/momentum scrolling if we are going to do a virtualization with uncertain dataset left boundary. Things  become unstable and unpredictable. And I'm afraid I don't see any trends to address such questions on appropriate layer (devices+browsers+standards) in the nearest future.

**Comment by jonnyleeharris** [comment]
@dhilt Thanks for the insight.

What is your inertia implementation supposed to do?

I'll look into this further, I hope I can somewhat address this so I can use it in a production PWA I am going to make.

**Comment by dhilt** [comment]
@jonnyleeharris Ngx-ui-scroll does not implement inertia, he fights inertia and can't beat it in some cases (I mean the idea is not to remove the inertia, but make it manageable). Dev-log should show something. Ngx-ui-scroll tries to live with different inertia implementations came from different devices/browsers, and Mac experience seems most problematic. And as I noticed, `-webkit-overflow-scrolling: touch;` is not on our side.

**Comment by jonnyleeharris** [comment]
@dhilt I'll update this issue when I figure out what's causing the problem. So far from all the virtual scroller implementations I have tried, yours seems to be the cleanest, and most sensible API - not to mention it works great for lazy loading in both directions - so thanks :)

Back to the issue at hand..

`-webkit-overflow-scrolling: touch` is required on iOS however if you want to have that native user experience people are used to. If you don't have this property set then the viewport scrolls without any native inertia on iOS.

It's worth mentioning that this same issues presents itself on Chrome for iOS too (but I suspect that's because they use the same web view implementation). I haven't had the opportunity to test it on an Android browser yet.

**Comment by dhilt** [comment]
@jonnyleeharris Jonathan, may I ask you also to try the previous `v1.0.4` release and the newest `v1.1.0-beta.1` one? They have some changes around handling the inertia and there is some chance that it may have an impact on your issue. Also, scroll events logging was slightly improved in `v1.1.0-beta.1` and it could be helpful for the debugging purposes.

**Comment by jonnyleeharris** [comment]
@dhilt Sorry I didn't get back to you on this. It became less of a priority for me. I ended up making a virtual list component in React - and guess what... I found the same bug! I think it's related to the way iOS handles the edge bounce scroll event and how we are handling it. When I get to looking into it in my React component I will let you know what I find - maybe it will help.

**Comment by dhilt** [comment]
ngx-ui-scroll v1.6.0 is on npm, it drastically improves iOS behaviour and solves inertia scroll issue

Please, submit new issue if any problems!
