### ISSUE TITLE
Can't use observable which emits more than once

### ISSUE THREAD

**Issue by mbarouski** [dhilt/ngx-ui-scroll#91]
Hey @dhilt 
I have an issue with using of observable which emits more than once:
```javascript
return this.someDataUpdated$.pipe(map(() => anotherData));
...
this.someDataUpdated$.next(...)
this.someDataUpdated$.next(...)
```
UIScroll reacted only once.

Also tried to use `this.datasource.adapter.reload()` but it throws error:
```
TypeError: Cannot read property 'log' of undefined
```
in this code:
```javascript
Adapter.prototype.reload = function (reloadIndex) {
        this.logger.log(function () { return "adapter: reload(" + reloadIndex + ")"; }); <-- this line
        this.callWorkflow((/** @type {?} */ ({
            process: Process.reload,
            status: ProcessStatus.start,
            payload: reloadIndex
        })));
    };
```

UPDATED: `this.datasource.adapter.reload()` works but it's initialized not immediately, isn't there an event to get known that adapter is initialized?

UPDATED: Found `this.datasource.adapter.init$` observable to get known about adapter initialization :)

**Comment by dhilt** [comment]
@maximka777 Sorry for the delay, I was busy with [Adapter.remove](https://github.com/dhilt/ngx-ui-scroll/pull/89) and that story is not finished yet... 

Have the problems been resolved? Does Adapter.init$ satisfy your needs?  I would love to have repro ([stackblitz](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-0-0)?) to investigate how the Adapter might lose its context. Even if you were able to implement some workaround in your app, it could be important to think what can be done in general.

**Comment by mbarouski** [comment]
@dhilt I will make repro of my issue.

**Comment by mbarouski** [comment]
There is repro https://stackblitz.com/edit/angular-ui-scroll-observable-additional-emits-ignore
I return behavior subject in `datasource.get` and do `.next(...)` on button click, but ui scroll view is not updated. I expect that view is updated on new data in subject. 
Maybe there is some workaround to get such behavior?

**Comment by dhilt** [comment]
@maximka777 What a behaviour you are trying to achieve with your `handleClick` method? `Datasource.get` is the legal place where you can get into the uiScroll and tell him what items need to be rendered. This method is being called by the uiScroll automatically when scroll events occur. Also, there are some `Adapter` methods providing scroller-component interaction based on user actions.

For example, if you wish to set the viewport to some random row, you may use `Adapter.reload` method ([forked demo is here](https://stackblitz.com/edit/angular-ui-scroll-observable-additional-emits-ignore-5nrcy8)).

So, the question is what should happen when a user clicks a button?

**Comment by mbarouski** [comment]
Ui-scroll component should show new items according to new index when a user clicks the button. In other words sometimes I need to set items for showing manually (without scrolling).

**Comment by mbarouski** [comment]
I can return observable from `datasource.get` but it is handled like a promise (only one resolve).

**Comment by dhilt** [comment]
@maximka777 In this case `Adapter` is your friend. Append, prepend and reload can be used for updating the viewport without scrolling.

One of the most important things is that external datasource (in component) must be synced with the changes you are making for the uiScroll. The difference between synced and non-synced updates is being discussed on the prepend demos page ([here](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend) and [here](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend-sync)).

Right now we can only append and prepend new rows to the viewport. Insert and delete methods are not implemented. But the workaround is to update the external datasource and make `Adapter.reload`.

 In your demo you have no static datasource on the component layer, the data is being generated runtime. Manual data changes might require a revision of the concept. [This demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-1-0-beta) can help, it has static datasource implementation on the component layer and shows how the items could be changed by reference with no additional efforts. From that point you may implement any logic on the datasource mutating (adding/removing items) and force the uiScroll Adapter reload at a given index.

**Comment by mbarouski** [comment]
Thanks for your answer :)
