### ISSUE TITLE
Problem with scrolling to the bottom of the list

### ISSUE THREAD

**Issue by StriderRanger** [dhilt/ngx-ui-scroll#92]
I need at some point of my app to scroll down to the bottom of the list. It works fine until I add a margin to the items, there the scroll begins to behave unexpectedly.

This behavior can be tested in [this sample](https://stackblitz.com/edit/ngx-ui-scroll-to-bottom), where you can notice two main problems:
- The `startIndex ` does not place the scroll to the bottom of the list even if the last index of the list is passed as a value in the settings
- If you scroll up to the middle of the list and click on the 'Scroll to bottom' button, the scoll is rarely placed at the bottom, but somewhere around 3 to 4 items above.

When the margin is deleted (it's a `12px` of `margin-top` on the `item` class in the only css file in the example), the scrolling to bottom works as expected.

Thank you for your support!

**Comment by dhilt** [comment]
@StriderRanger Looks like we aren't working with margined templates. The average items height is being calculated without taking into account margins, and this breaks internal viewport params calculations (scrollHeight becomes inaccurate). We might try to see what can be done here, but the issue may be very far from easy. For example, [margin collapsing cases](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing). 

As a workaround in your particular case I would recommend to redo the template and expose top margin explicitly:

```
    <div class="item" [style.height]="item.height + margin + 'px'">
      <div [style.height]="margin + 'px'"></div>
      {{item.text}}
    </div>
```

where `margin` variable is defined as an integer on the component's layer:

```
    margin: number = 12;
```

Of course `margin-top: 12px;` should be removed from css.

**Comment by dhilt** [comment]
Also, how did you find `Adapter.setScrollPosition` method? Why don't you use just 

```
this.viewport.nativeElement.scrollTop = this.viewport.nativeElement.scrollHeight;
```
?

**Comment by StriderRanger** [comment]
The workaround solved my problem, thanks! I also changed the margin by the padding property and it worked too.

Between, I found the `setScrollPosition` in [the `Check size`  docs](https://dhilt.github.io/ngx-ui-scroll/#/adapter) example. When my scroll to bottom was not working, I just thought that using an api method would be better. I am using the `scrollTop` now with the working solutions.

**Comment by dhilt** [comment]
@StriderRanger Thank you! Closing this issue... Please feel free to open new one if you have another questions.
