### ISSUE TITLE
Get scroll position for specific element

### ISSUE THREAD

**Issue by aloifolia** [dhilt/ngx-ui-scroll#95]
I was thinking about using ngx-ui-scroll for a pseudo-nested list component which 
- lets the user open and close specific parent elements to see their contained items (while items appear to be nested they are actually all part of one big datasource)
- inserts section headers if desired
- has sticky headers that behave as if a parent element or a section header had the `position: sticky` CSS property

For the last requirement I would need to add some JS/TS magic to mimic the desired behavior since the elements are not actually nested in the DOM. So the idea is to duplicate and stick certain elements to the top as soon as they reach a certain scroll position (and move them manually when the next "stickable" element gets close). For this approach, I would somehow need to be able to determine the scroll position of specific elements after each scroll event. 

Is there an API available for this scenario? If not, would it be feasible to implement?

**Comment by dhilt** [comment]
@aloifolia Basically we have only top and bottom visible items accessible via Adapter. Only that two DOM elements might be received via API:

```
Adapter.firstVisible.element;
Adapter.lastVisible.element;
```

But you always can access any DOM element directly with native browser API. We have [Check size demo](https://dhilt.github.io/ngx-ui-scroll/#/adapter#check-size) that manipulates DOM for autoscroll purpose. With the help of `data-sid` attribute you may receive any visible item's element by item's index:

```
viewportElement.querySelector(`[data-sid="${index}"]`)
```

And then use `scrollTop`, `offsetTop`, `getBoundingClientRect`, whatever you might want. 

If such an approach seems not acceptable for you, which API you might want to have on the UIScroll side? I mean the method description with signature or set of methods, how they should work... doing something after each scroll event might be dangerous, we need to fantasize carefully.
